<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FiltrationClarificationSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        // 1. Create or Update Category "Filtration & Clarification"
        $category = [
            'slug' => 'filtration-clarification',
            'url_path' => '/product-category/filtration-clarification/',
            'name' => 'Filtration & Clarification',
            'summary' => 'High-performance automatic fluid filtration, liquid-solid clarification, self-cleaning scraping, and backwash systems from authorized China principal Shanghai JCI Technology Co., Ltd.',
            'description_html' => '<h2>Engineered Fluid Filtration & Clarification Systems</h2><p>Industrial manufacturing and process operations demand rigorous fluid purity, equipment protection, and waste minimization. PT Misuba Guna Indonesia, in strategic partnership with leading global manufacturer <strong>Shanghai JCI Technology Co., Ltd. (上海久丞工业科技有限公司)</strong>, delivers advanced liquid filtration, precision clarification, and continuous self-cleaning separation systems across Indonesia.</p><p>From high-viscosity resins and crude palm oil (CPO) to circulating cooling water, volatile chemical solvents, and high-purity food and pharmaceutical broths, our engineered systems provide 24/7 uninterrupted operation, zero consumable waste generation, and sealed hermetic operator safety.</p>',
            'parent_group' => 'Filtration & Clarification',
            'sort_order' => 10,
            'meta_title' => 'Filtration & Clarification Systems - PT Misuba Guna Indonesia',
            'meta_description' => 'Industrial fluid filtration and clarification systems manufactured by Shanghai JCI Technology: scraping self-cleaning filters, multi-cartridge backwash, candle and plate filters, bag and cartridge vessels.',
            'canonical_url' => 'https://misubaguna.com/product-category/filtration-clarification/',
            'og_title' => 'Filtration & Clarification Systems - PT Misuba Guna Indonesia',
            'og_description' => 'Industrial fluid filtration and clarification systems manufactured by Shanghai JCI Technology for palm oil, petrochemical, water treatment, and fine chemical applications.',
            'og_image_path' => '/images/products/filtration/principal/jci-manufacturing-workshop.webp',
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.8',
            'sitemap_changefreq' => 'weekly',
            'schema_json' => null,
            'is_published' => true,
        ];

        DB::table('public_product_categories')->updateOrInsert(
            ['url_path' => $category['url_path']],
            array_merge($category, ['created_at' => $now, 'updated_at' => $now])
        );

        // Seed Category "Power Transfer"
        $powerTransferCat = [
            'slug' => 'power-transfer',
            'url_path' => '/product-category/power-transfer/',
            'name' => 'Power Transfer',
            'summary' => 'Mechanical power transfer components including flexible, rigid, gear, and fluid couplings for industrial rotating machinery and drivetrain protection.',
            'description_html' => '<h2>Industrial Power Transfer Solutions</h2><p>PT Misuba Guna Indonesia supplies high-performance mechanical power transfer and drivetrain components engineered to connect driving and driven shafts, compensate for mechanical misalignment, and isolate torsional vibration across demanding industrial applications.</p>',
            'parent_group' => 'Power Transfer',
            'sort_order' => 11,
            'meta_title' => 'Power Transfer Products - PT Misuba Guna Indonesia',
            'meta_description' => 'Industrial power transfer and mechanical coupling solutions for pumps, gearboxes, motors, and rotating equipment.',
            'canonical_url' => 'https://misubaguna.com/product-category/power-transfer/',
            'og_title' => 'Power Transfer Products - PT Misuba Guna Indonesia',
            'og_description' => 'Industrial power transfer and mechanical coupling solutions for pumps, gearboxes, motors, and rotating equipment.',
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.8',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ];

        DB::table('public_product_categories')->updateOrInsert(
            ['url_path' => $powerTransferCat['url_path']],
            array_merge($powerTransferCat, ['created_at' => $now, 'updated_at' => $now])
        );

        // Migrate existing membrane-filter-press product record to filter-plate-press if present
        DB::table('public_products')->where('slug', 'membrane-filter-press')->update([
            'slug' => 'filter-plate-press',
            'url_path' => '/product/filter-plate-press/',
        ]);

        // Add 301 redirect for legacy membrane-filter-press
        DB::table('public_redirects')->updateOrInsert(
            ['source_path' => '/product/membrane-filter-press/'],
            [
                'target_url' => '/product/filter-plate-press/',
                'status_code' => 301,
                'is_active' => true,
                'note' => 'Redirect legacy membrane-filter-press URL to filter-plate-press',
                'created_at' => $now,
                'updated_at' => $now,
            ]
        );

        // 2. Products List
        $products = [
            [
                'slug' => 'scraping-self-cleaning-filter',
                'url_path' => '/product/scraping-self-cleaning-filter/',
                'name' => 'Scraping Self-Cleaning Filter (AF Series)',
                'product_group' => 'Filtration & Clarification',
                'product_subgroup' => 'Self-Cleaning Filters',
                'headline' => 'AF Series Mechanical Scraping Self-Cleaning Liquid Filter',
                'summary' => 'Continuous 24/7 online scraping self-cleaning filter designed for high-viscosity, sticky, or hazardous fluids without filter consumables, downtime, or manual cleaning.',
                'content_html' => '<h1>AF Series Mechanical Scraping Self-Cleaning Filter</h1><p class="product-description">The AF Scraper-type Self-cleaning Filter is engineered to remove impurities and suspended solids on the surface of precision filter screens via highly efficient mechanical scraping. Utilizing intelligent differential pressure (ΔP) and cycle-time automation, the AF filter cleans the screen automatically and expels concentrated impurities without human intervention or consumable filter bags and cartridges.</p><h2>Eliminating the Pain Points of Traditional Filtration</h2><p>Traditional bag, basket, and vibrating-screen filters suffer from low pollutant holding capacity, rapid blinding, and the constant need for manual dismantling, cleaning, and disposable media purchases. In high-viscosity or hazardous services, manual cleanout exposes workers to volatile vapors, skin hazards, and elevated temperatures. The AF Series delivers consecutive online filtration, zero consumable disposal costs, and reliable protection for downstream pumps, valves, and heat exchangers.</p><h2>4 Specialized Subseries for Diverse Fluid Rheologies</h2><ul><li><strong>AFE Series (External Motor-Driven Scraper):</strong> Features an external scraping blade driven by an electric gearmotor across the outer surface of the filter screen. Specially designed for high-viscosity resins, polymers, adhesives, and thick fluids.</li><li><strong>AFC Series (Pneumatic Inner Scraper):</strong> Utilizes a pneumatic air-cylinder to drive vertical scraping movements along the inner surface of the filter screen. Ideal for medium-to-high viscosity fluids, explosive environments (ATEX), and inflammable volatile solvents.</li><li><strong>AFM Series (Internal Motor-Driven Scraper):</strong> Employs an electric gearmotor to rotate heavy-duty scraping blades along the inner screen surface. Designed for medium and high-viscosity materials and general suspended solid filtration.</li><li><strong>AFB Series (Internal Motor-Driven Rotating Brush):</strong> Features high-density stainless steel or nylon scraping brushes rotated by motor along the inner screen surface. Engineered specifically for water, cooling liquids, low-viscosity fluids, and high-precision screening down to 1 micron.</li></ul><h2>Intelligent Self-Cleaning & Purge Operation</h2><p>As impurities accumulate on the screen, differential pressure rises. When the preset ΔP threshold (or timer) is reached, the scraper drive activates, scraping cake and particles toward the bottom accumulation chamber. The automatic drain valve opens briefly, expelling waste fluid containing high-concentration impurities with negligible fluid loss, instantly restoring full screen throughput.</p>',
                'key_features' => [
                    'Continuous 24/7 online filtration without consumable generation or process downtime',
                    'Intelligent automatic cleaning triggered by differential pressure (ΔP) and run timer',
                    '4 specialized subseries (AFE outer, AFC pneumatic, AFM inner, AFB rotating brush)',
                    'Handles extreme viscosity liquids from 1 cP up to 800,000 cP',
                    'Completely enclosed design protects operators from toxic, hot, or volatile liquids',
                    'Concentrated impurity expulsion minimizes product loss and disposal volume',
                    'Directly replaces traditional bag, basket, and vibrating-screen filters with lower TCO',
                ],
                'applications' => [
                    'Resins, polymers, adhesives, sealants, paints, printing inks, and coatings',
                    'Petrochemicals: kerosene, diesel, high-temperature oil, wet-end additives, rubber, ethanol',
                    'Food & Beverage: chocolate, candy, edible oil, citric acid, fermentation broth, sorbitol, fruit juice',
                    'Paper & Pulp: starch slurries, wet-end chemical additives, sizing agents, and coatings',
                    'Biological pharmacy, cosmetics, and environmental water treatment',
                ],
                'materials' => [
                    'Housing Material: Stainless Steel 304, 316, 316L, or Carbon Steel (CS)',
                    'Filter Screen: Precision SS316L V-shaped wedge screen or O-shaped punching hole screen',
                    'Scraper / Brush: Spring-loaded PTFE blades, reinforced polymers, or SS316 wire brushes',
                    'Drive System: Geared electric motor or pneumatic air cylinder (explosion-proof available)',
                    'Seals: Viton, PTFE, EPDM, Silicone',
                ],
                'technical_specs' => [
                    'Filtration Precision: 1 µm to 3,000 µm',
                    'Applicable Fluid Viscosity: 1 to 800,000 cP',
                    'Design Pressure: 0.6 to 2.5 MPa',
                    'Operating Temperature: 0°C to 260°C (higher upon custom engineering)',
                    'Flowrate Capacity: 1 to 500 m³/h per unit',
                    'Cleaning Start Modes: Differential pressure (ΔP), cycle timer, or manual override',
                ],
                'og_image_path' => '/images/products/filtration/scraping-filter/af-series-main.webp',
                'gallery' => [
                    '/images/products/filtration/scraping-filter/af-series-main.webp',
                    '/images/products/filtration/scraping-filter/af-subseries-models.webp',
                    '/images/products/filtration/scraping-filter/af-onsite-installation.webp',
                    '/images/products/filtration/scraping-filter/afm-scraper-elements.webp',
                    '/images/products/filtration/scraping-filter/afe-scraper-elements.webp',
                    '/images/products/filtration/scraping-filter/afb-scraper-elements.webp',
                ],
                'sort_order' => 38,
                'meta_title' => 'AF Series Scraping Self-Cleaning Filter - PT Misuba Guna Indonesia',
                'meta_description' => 'Continuous mechanical scraping self-cleaning filter for high-viscosity liquids, resins, adhesives, and palm oil. Zero consumables, 1-3000 micron, up to 800,000 cP.',
                'canonical_url' => 'https://misubaguna.com/product/scraping-self-cleaning-filter/',
                'og_title' => 'AF Series Scraping Self-Cleaning Filter - PT Misuba Guna Indonesia',
                'og_description' => 'Continuous mechanical scraping self-cleaning filter manufactured by Shanghai JCI Technology for high-viscosity and hazardous fluids.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.9',
                'sitemap_changefreq' => 'monthly',
                'schema_json' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'automated-backwash-filter',
                'url_path' => '/product/automated-backwash-filter/',
                'name' => 'Automated Backwash Filter (AR Series)',
                'product_group' => 'Filtration & Clarification',
                'product_subgroup' => 'Self-Cleaning Filters',
                'headline' => 'AR High-Efficiency Multi-Cartridge Automatic Backwash Water Filter',
                'summary' => 'High-flux automated backwash filter with integrated multi-element wedge screens and rotating recoil arm for continuous 24/7 water and low-viscosity fluid purification.',
                'content_html' => '<h1>AR Series Automated Backwash Filter</h1><p class="product-description">The AR High-efficiency Multi-Cartridge Self-cleaning Backwash Filter integrates multiple precision aperture-type wedge-wire screens within a compact single pressure vessel. When particulate matter blocks screen elements, a motorized rotating recoil device backwashes the filter screens sequentially one by one, while all other screens remain online filtering at full capacity.</p><h2>Large Surface Area & Continuous High-Flux Filtration</h2><p>Unlike standard backwash filters that suffer from rapid blinding and excessive backwash water loss, the AR Series features an ultra-large total filtration area that ensures low face velocity and accurate particulate interception. The entire series spans a precision range of 50 to 3,000 microns and flow rates up to 8,000 m³/h per vessel, making it the premier choice for circulating cooling water, raw water intake, and low-viscosity industrial fluids.</p><h2>8 Standardized Subseries (AR300 through AR1000)</h2><p>Available in eight standardized mechanical configurations (AR300, AR400, AR500, AR600, AR700, AR800, AR900, AR1000), the AR Series accommodates diverse pipeline diameters from DN100 up to DN800+. Each model features rigid stainless steel V-shaped slot wedge-wire screens that prevent clogging and ensure complete release of suspended solids during the reverse recoil flush.</p><h2>Automated Sequential Recoil Operation</h2><p>Differential pressure transmitters monitor pressure across the housing. When the preset ΔP setpoint (typically 0.05 MPa) is met, the gearmotor turns the backwash arm into alignment with the first filter screen, and the drain valve opens. The pressure differential between the vessel interior and the atmospheric drain forces clean filtrate in reverse through the screen, purging trapped solids into the drain header. The arm indexes to each screen in turn until all elements are thoroughly regenerated.</p>',
                'key_features' => [
                    'Continuous 24/7 uninterrupted online filtration during backwash cycles',
                    'Sequential element-by-element backwashing via high-efficiency rotating recoil arm',
                    'Large filtration area ensures low surface velocity and high dirt retention capacity',
                    'Minimal backwash wastewater consumption (< 1% of total treated volume)',
                    '8 standardized subseries (AR300 through AR1000) handling up to 8,000 m³/h',
                    'Siemens/Schneider PLC automated control with ΔP sensor and time-scheduled triggers',
                    'Heavy-duty stainless steel V-shaped wedge-wire screens ensure clog-free performance',
                ],
                'applications' => [
                    'Industrial circulating cooling water, technical circulating water, and chilled water loops',
                    'Power plants & petrochemical: seawater intake, heat exchanger cooling, sealed water',
                    'Paper & pulp: raw river water, white water loops, shower nozzle spray protection',
                    'Iron & steel metallurgy: continuous casting spray water, nozzle descaling, blast furnace cooling',
                    'Oilfield reinjection water, mining, agricultural irrigation, aquaculture, and civil utilities',
                ],
                'materials' => [
                    'Housing Material: Stainless Steel 304, 316, 316L, or Carbon Steel (epoxy/rubber lined)',
                    'Filter Elements: Precision SS316L V-shaped aperture wedge-wire screen cartridges',
                    'Recoil Mechanism & Shaft: Stainless Steel 316 / 316L',
                    'Actuator: High-torque geared electric motor (IP65 / Ex-proof)',
                ],
                'technical_specs' => [
                    'Subseries: AR300, AR400, AR500, AR600, AR700, AR800, AR900, AR1000',
                    'Filtration Precision: 50 µm to 3,000 µm',
                    'Single Unit Flowrate: 1 to 8,000 m³/h',
                    'Applicable Fluid Viscosity: 1 to 40 cP',
                    'Operating Temperature: 1°C to 95°C',
                    'Design Pressure: 0.6 to 1.0 MPa (higher pressure customizable)',
                    'Cleaning Control: Manual, preset timer, or differential pressure switch',
                ],
                'og_image_path' => '/images/products/filtration/backwash-filter/ar-series-main.webp',
                'gallery' => [
                    '/images/products/filtration/backwash-filter/ar-series-main.webp',
                    '/images/products/filtration/backwash-filter/ar-onsite-piping.webp',
                    '/images/products/filtration/backwash-filter/ar-multicartridge-skid.webp',
                    '/images/products/filtration/backwash-filter/ar-water-treatment.webp',
                ],
                'sort_order' => 39,
                'meta_title' => 'AR Series Automated Backwash Filter - PT Misuba Guna Indonesia',
                'meta_description' => 'Multi-cartridge automated backwash water filter manufactured by Shanghai JCI Technology. Up to 8,000 m3/h, 50-3000 micron for cooling water and industrial water loops.',
                'canonical_url' => 'https://misubaguna.com/product/automated-backwash-filter/',
                'og_title' => 'AR Series Automated Backwash Filter - PT Misuba Guna Indonesia',
                'og_description' => 'High-flux multi-cartridge automatic backwash water filter for power plants, refineries, paper mills, and cooling water circuits.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.9',
                'sitemap_changefreq' => 'monthly',
                'schema_json' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'candle-filter',
                'url_path' => '/product/candle-filter/',
                'name' => 'Sealed Candle Filter (CFC Series)',
                'product_group' => 'Filtration & Clarification',
                'product_subgroup' => 'Cake & Clarifying Filters',
                'headline' => 'CFC Series Hermetic Automatic Cake & Pre-Coating Candle Filter',
                'summary' => 'Hermetically sealed pressure candle filter for direct filtration, pre-coat filtration, slurry concentration, cake washing, and automated gas blowback cake discharge.',
                'content_html' => '<h1>CFC Series High-Efficiency Sealed Candle Filter</h1><p class="product-description">The CFC High-efficiency Seal Candle Filter is an enclosed pressure filtration system designed for precise solid-liquid separation, cake washing, and slurry thickening. Material is fed into the filter vessel via feed pump. Prior to normal filtration, fluid undergoes closed cycling until a uniform, porous filter cake forms on vertical candle elements, initiating crystal-clear filtration.</p><h2>Zero-Emission Hermetic Cake Filtration</h2><p>When the filter cake reaches the optimum operating thickness, remaining residual liquid is displaced from the vessel using pressurized gas or recovery pumps. Controlled gas blowback (compressed air, nitrogen, or steam) is applied through the core of the candle tubes, inflating the filter cloth sleeves and instantaneously dislodging the cake. The automated bottom slag-drip cone valve opens to discharge the cake as dry solids or concentrated slurry, returning the vessel to its pristine initial state for the next cycle.</p><h2>Key Process Capabilities</h2><ul><li><strong>Direct Clarifying Filtration:</strong> Intercepts fine particles down to 0.5 microns without filter aids.</li><li><strong>Pre-Coat Filtration:</strong> Facilitates pre-coating with diatomaceous earth (DE), perlite, or activated carbon for colloidal and gelatinous impurities.</li><li><strong>In-Situ Cake Washing & Drying:</strong> Thoroughly washes residual mother liquor from cake and dries cake with hot inert gas or steam.</li><li><strong>Total Containment:</strong> Zero leakage of toxic, flammable, volatile, or odorous liquids, guaranteeing total operator safety.</li></ul>',
                'key_features' => [
                    'Completely sealed pressure vessel guarantees zero product leakage and operator safety',
                    'Multi-stage cycle: direct filtration, pre-coating, slurry concentration, cake washing, and drying',
                    'Reverse gas blowback cake discharge with zero mechanical rotating parts inside vessel',
                    'Seamless filter cloth tubes or porous sintered metal candles with high filtration integrity',
                    'Automated cyclic operation with PLC differential pressure and timer control',
                    'Adaptable to both dry cake discharge and concentrated slurry discharge',
                ],
                'applications' => [
                    'Fine chemicals & catalyst recovery: Raney nickel, palladium, platinum on carbon catalysts',
                    'Resins & polymers: polybutylene resin, alkyd resin, epoxy resin, and acrylic monomers',
                    'Oils & lubricants: beer, gelatin, syrup, recycled wax, cutting oil, fuel, and lube oils',
                    'Coal chemical & petrochemical engineering: coal tar, coal liquids, and specialty solvents',
                    'Water treatment & slurry dewatering: hazardous chemical effluent and slurry concentration',
                ],
                'materials' => [
                    'Vessel Housing: Stainless Steel 304, 316L, Carbon Steel, or Hastelloy',
                    'Filter Elements: Porous candle tubes with PP, PTFE, PVDF, or PA filter cloth socks, or Sintered Metal',
                    'Valves: Automated pneumatic bottom cone dump valve and top blowback valves',
                ],
                'technical_specs' => [
                    'Filter Area: 2 m² to 100 m²',
                    'Filtration Accuracy: 0.5 µm to 800 µm',
                    'Flow Capacity: 1 to 100 m³/h',
                    'Design Pressure: 0.6 to 1.0 MPa',
                    'Operating Temperature: 1°C to 200°C',
                    'Applicable Viscosity: 1 to 2,000 cP',
                    'Cleaning & Slagging: Compressed gas (air/N2/steam) blowback back flushing',
                ],
                'og_image_path' => '/images/products/filtration/candle-filter/cfc-candle-filter-main.webp',
                'gallery' => [
                    '/images/products/filtration/candle-filter/cfc-candle-filter-main.webp',
                    '/images/products/filtration/candle-filter/cfc-candle-elements.webp',
                    '/images/products/filtration/candle-filter/cfc-filter-system.webp',
                ],
                'sort_order' => 40,
                'meta_title' => 'CFC Series Sealed Candle Filter - PT Misuba Guna Indonesia',
                'meta_description' => 'Hermetic automated candle filter for direct filtration, pre-coating, catalyst recovery, and gas blowback cake discharge. Manufactured by Shanghai JCI Technology.',
                'canonical_url' => 'https://misubaguna.com/product/candle-filter/',
                'og_title' => 'CFC Series Sealed Candle Filter - PT Misuba Guna Indonesia',
                'og_description' => 'Hermetically sealed automatic cake and pre-coating candle filter for chemical, pharmaceutical, and oil clarification.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.9',
                'sitemap_changefreq' => 'monthly',
                'schema_json' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'pressure-leaf-filter',
                'url_path' => '/product/pressure-leaf-filter/',
                'name' => 'Pressure Leaf Filter (CFP Series)',
                'product_group' => 'Filtration & Clarification',
                'product_subgroup' => 'Cake & Clarifying Filters',
                'headline' => 'CFP Series Hermetic Vertical Seal Plate & Pressure Leaf Clarifying Filter',
                'summary' => 'High-efficiency hermetic seal plate clarifying filter featuring stainless steel leaf screens, zero cloth/paper consumables, gas blow-drying, and automated high-frequency pneumatic vibration dry cake discharge.',
                'content_html' => '<h1>CFP Series High-Efficiency Seal Plate & Pressure Leaf Filter</h1><p class="product-description">The CFP High-efficiency Seal Plate Filter (Vertical Pressure Leaf Filter) is an advanced precision clarifying filtration system featuring high throughput, energy savings, and airtight sealed operation. Designed with multi-layer stainless steel leaf screens mounted onto a central manifold inside a vertical pressure vessel, the CFP produces crystal-clear filtrate with zero material loss, no consumption of filter cloth or paper, and minimal filter aid usage.</p><h2>The Benchmark for Palm Oil Bleaching Earth Removal & Clarification</h2><p>In edible oil refining, crude palm oil (CPO) clarification, and bleaching earth removal (spent bleaching earth), open filter presses generate massive cloth replacement expenses, hazardous labor, and product leakage. The CFP Series performs the entire filtration process inside a hermetically sealed container. After filtration completes, inert gas or steam blows the cake dry. The dry filter cake is then shaken off the stainless steel leaves via a high-frequency pneumatic vibrator and discharged through a bottom butterfly valve in less than 3 minutes.</p><h2>Distinct Engineering Advantages</h2><ul><li><strong>Consumable-Free Operation:</strong> High-strength, 5-layer stainless steel wire mesh filter leaves eliminate paper, cloth, or cartridge disposal fees.</li><li><strong>High-Frequency Pneumatic Vibrator:</strong> Dislodges stubborn, sticky, or dense filter cakes automatically without opening the vessel.</li><li><strong>Dry Cake Discharge:</strong> Gas displacement and blow-drying achieve extremely low cake oil retention and moisture content.</li><li><strong>Airtight Environmental Protection:</strong> Completely contained system prevents odor release, oil mist, oxidation, and VOC emissions.</li><li><strong>Hydraulic Quick-Open Lid:</strong> Hydraulic lift and swing davit allow effortless vessel opening for periodic internal inspection.</li></ul>',
                'key_features' => [
                    '100% Hermetically sealed container eliminates VOC emissions, leaks, and oxidation',
                    'Zero consumable filter cloth or paper required; utilizes cleanable stainless steel leaf screens',
                    'High-frequency pneumatic vibrator rapidly discharges dry cake in under 3 minutes',
                    'Steam or compressed gas cake blow-drying recovers maximum residual filtrate',
                    'Minimal filter aid consumption (bentonite / diatomaceous earth / perlite)',
                    'Hydraulic cylinder quick-opening shell mechanism facilitates rapid internal inspection',
                    'Food-grade & sanitary construction available with internal electropolishing',
                ],
                'applications' => [
                    'Palm oil milling and refining: CPO clarification, bleaching earth removal, and dry fractionation',
                    'Edible oils & fats: coconut oil, soybean oil, canola, margarine, and recycled cooking oil',
                    'Resins & polymers: alkyd resin, epoxy resin, polyurethane, and varnish clarification',
                    'Biofuels & oleochemicals: biodiesel pre-filtration, fatty acid purification, and glycerin',
                    'Beverage & food processing: glucose syrup, liquid sugar, beer, fruit juices, and citric acid',
                    'Petrochemicals & solvents: plasticizers, organic solvents, and molten sulfur',
                ],
                'materials' => [
                    'Housing & Shell: Stainless Steel 304, 316, 316L, or Heavy Carbon Steel (CS)',
                    'Filter Leaf Screens: 5-Layer Stainless Steel Wire Mesh (SS304 / SS316 / SS316L)',
                    'Vibrator & Actuators: Pneumatic high-frequency piston vibrator with butterfly bottom discharge valve',
                    'Gaskets & O-Rings: Viton, PTFE, Food-Grade Silicone, or EPDM',
                ],
                'technical_specs' => [
                    'Filter Area: 2 m² to 200 m²',
                    'Design Pressure: 0.1 to 0.6 MPa (1 to 6 bar)',
                    'Applicable Fluid Viscosity: 1 to 20,000 cP',
                    'Operating Temperature: 0°C to 150°C',
                    'Filter Screen Type: Multi-layer stainless steel plate filter screen',
                    'Filtration Mode: Hermetic clarifying filtration & automated vibration dry cake expulsion',
                ],
                'og_image_path' => '/images/products/filtration/pressure-leaf-filter/cfp-plate-filter-main.webp',
                'gallery' => [
                    '/images/products/filtration/pressure-leaf-filter/cfp-plate-filter-main.webp',
                    '/images/products/filtration/pressure-leaf-filter/cfp-hermetic-leaf-system.webp',
                    '/images/products/filtration/pressure-leaf-filter/cfp-vibrator-unit.webp',
                ],
                'sort_order' => 34,
                'meta_title' => 'Pressure Leaf Filter (CFP Series) - PT Misuba Guna Indonesia',
                'meta_description' => 'Hermetic vertical seal plate and pressure leaf filter for CPO clarification, bleaching earth removal, and resin clarification. Manufactured by Shanghai JCI Technology.',
                'canonical_url' => 'https://misubaguna.com/product/pressure-leaf-filter/',
                'og_title' => 'Pressure Leaf Filter (CFP Series) - PT Misuba Guna Indonesia',
                'og_description' => 'Fully enclosed pressure leaf filter with vibration dry cake discharge and stainless steel screens. Built by Shanghai JCI Technology.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.9',
                'sitemap_changefreq' => 'monthly',
                'schema_json' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'filter-plate-press',
                'url_path' => '/product/filter-plate-press/',
                'name' => 'Filter Plate Press',
                'product_group' => 'Filtration & Clarification',
                'product_subgroup' => 'Filter Press & Cake Filtration',
                'headline' => 'Automatic High-Pressure Filter Plate Press (Membrane & Chamber System)',
                'summary' => 'High-pressure automatic filter plate press with recessed chamber and secondary membrane diaphragm squeeze for maximum dewatering, ultra-low cake moisture, and automated plate shifting and cloth washing.',
                'content_html' => '<h1>Automatic Filter Plate Press (Membrane & Chamber System)</h1><p class="product-description">The Automatic Filter Plate Press delivers unmatched solid-liquid dewatering efficiency by combining initial high-pressure hydraulic plate clamping with secondary membrane diaphragm inflation. Utilizing water or compressed air squeeze pressures up to 25 bar, this system squeezes mechanically bound moisture from the filter cake, resulting in the lowest residual cake moisture and fastest filtration cycle times in the industry.</p><h2>High-Pressure Chamber & Membrane Squeezing Technology</h2><p>In standard recessed chamber filter presses, cake dewatering is limited by feed pump pressure. The Membrane Filter Plate Press introduces synthetic rubber or reinforced polypropylene flexible membranes on both sides of each filter plate. After initial cavity filling, high-pressure medium inflates the membranes into the cake, reducing final cake moisture by an additional 15% to 25% while reducing overall cycle time by up to 50%.</p><h2>Full Automation & Industrial Reliability</h2><ul><li><strong>Automated Plate Shifting:</strong> Motorized rapid plate shifters release cakes plate by plate without manual operator labor.</li><li><strong>Automated Cloth Washing:</strong> Integrated high-pressure (up to 80 bar) mobile spray bar systematically cleans cloth fibers, preventing blind spots.</li><li><strong>Drip Tray Bomb Doors:</strong> Pneumatically actuated bomb doors collect wash water during cleaning and open during cake discharge.</li><li><strong>Siemens PLC Architecture:</strong> Multi-recipe touch screen interface controls pump ramping, squeeze duration, core blowing, and safety interlocks.</li></ul>',
                'key_features' => [
                    'High-pressure membrane squeeze (16 to 25 bar) reduces cake moisture by an additional 15%–25%',
                    'Fully automated plate shifting, drip tray operation, and high-pressure cloth washing',
                    'Heavy-duty steel structural frame with anti-corrosion epoxy or stainless steel cladding',
                    'Siemens PLC automated control panel with multi-stage recipe pressure management',
                    'High-strength molded polypropylene chamber and membrane plates with flexible elastomer diaphragms',
                ],
                'applications' => [
                    'Palm oil & oleochemicals: palm oil dry fractionation (stearin/olein separation), PKO polishing',
                    'Industrial wastewater & sludge: sewage dewatering, effluent treatment plants (ETP)',
                    'Mining & metallurgy: coal washing, mineral concentrate filtration, tailings dewatering',
                    'Chemical processing: dyes, pigments, titanium dioxide, calcium carbonate, chemical precipitates',
                ],
                'materials' => [
                    'Filter Plates: High-density molded Polypropylene (PP) chamber plates and welded/replaceable TPE/EPDM membranes',
                    'Filter Cloth: Monofilament and multifilament PP, PA (Nylon), or PET polyester',
                    'Frame: High-tensile carbon steel Q345B with 304/316 stainless cladding option',
                ],
                'technical_specs' => [
                    'Filtration Area: 10 m² to 1,000 m²',
                    'Chamber Volume: 0.2 m³ to 20 m³',
                    'Feed Filtration Pressure: 0.6 to 1.6 MPa (6 to 16 bar)',
                    'Membrane Squeeze Pressure: Up to 2.5 MPa (25 bar)',
                    'Plate Sizes: 800×800 mm, 1000×1000 mm, 1250×1250 mm, 1500×1500 mm, 2000×2000 mm',
                ],
                'og_image_path' => '/images/products/filtration/membrane-filter-press/membrane-filter-press-main.webp',
                'gallery' => [
                    '/images/products/filtration/membrane-filter-press/membrane-filter-press-main.webp',
                ],
                'sort_order' => 1,
                'meta_title' => 'Filter Plate Press - PT Misuba Guna Indonesia',
                'meta_description' => 'Automatic high-pressure filter plate press with recessed chamber and membrane squeezing for palm oil fractionation, sludge dewatering, and chemical cake filtration.',
                'canonical_url' => 'https://misubaguna.com/product/filter-plate-press/',
                'og_title' => 'Filter Plate Press - PT Misuba Guna Indonesia',
                'og_description' => 'Heavy-duty automatic filter plate press systems with secondary diaphragm squeezing, recessed chamber plates, and automated plate shifting.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.9',
                'sitemap_changefreq' => 'monthly',
                'schema_json' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'modular-integrated-backwash-filter',
                'url_path' => '/product/modular-integrated-backwash-filter/',
                'name' => 'Modular Integrated Filter (MIF Series)',
                'product_group' => 'Filtration & Clarification',
                'product_subgroup' => 'Self-Cleaning Filters',
                'headline' => 'MIF Series Multi-Station Modular Backwash Filter System',
                'summary' => 'Modular integrated filtration skid combining 2 to 24 standard filter units for low-drop-out continuous online filtration with reverse-flow backwashing.',
                'content_html' => '<h1>MIF Series Module Integrated Filter</h1><p class="product-description">The MIF Module Integrated Filter is engineered around the principle of system integration, combining multiple standardized filter modules (2 to 24 units, MIF2 through MIF24) onto a unified header manifold skid. As process flowrate demands increase, filter stations can be seamlessly scaled up or down without altering core piping layout.</p><h2>Continuous Low Drop-Out Modular Filtration</h2><p>MIF operates automatically without manual intervention and is renowned for its ultra-low pressure drop-out. Each unit houses a high-performance V-shaped aperture stainless steel screen. During backwashing, the system leverages reverse flowage of clean filtrate generated by the other running filter units (internal backwash) or introduces external clean fluid to thoroughly flush the screen surface with minimal effluent volume.</p><h2>High Pressure & Temperature Resilience</h2><p>Engineered for demanding refinery and petrochemical loops, the MIF Series supports operating pressures up to 4.0 MPa (40 bar) and temperatures up to 250°C, providing robust continuous filtration for diesel, gasoline, naphtha, cooling water, and process loops.</p>',
                'key_features' => [
                    'Modular system integration: easily expand from 2 up to 24 stations as plant capacity grows',
                    'Internal reverse flow backwash utilizes clean filtrate from other operational units',
                    'External backwash connection available for sticky, hot, or chemical fluids',
                    'Extremely low pressure drop across the manifold header',
                    'High operating pressure capability (up to 4.0 MPa / 40 bar)',
                    'High operating temperature limit up to 250°C',
                ],
                'applications' => [
                    'Petrochemical refining: diesel, gasoline, naphtha, raw hydrocarbons, quench water',
                    'Industrial water treatment: process water, clean water, super-clean water, spray water',
                    'Paper & pulp: paper machine white water, shower water, and felt cleaning lines',
                    'Power generation: boiler feed water pre-filtration, condensate polishing pre-filters',
                ],
                'materials' => [
                    'Housing & Manifold: Stainless Steel 304, 316L, or Heavy Carbon Steel',
                    'Filter Elements: Precision SS316L V-shaped aperture filter screens',
                ],
                'technical_specs' => [
                    'Subseries: MIF2 to MIF24 (2 to 24 modular stations)',
                    'Unit Filtering Area: 0.267 m² or 0.377 m² per filter module',
                    'Filtration Accuracy: 20 µm to 3,000 µm',
                    'Applicable Fluid Viscosity: 1 to 50 cP',
                    'Operating Temperature: Up to 250°C',
                    'Design Pressure: 1.6 MPa, 2.5 MPa, 4.0 MPa',
                    'Cleaning Start Mode: Differential pressure (ΔP) or programmable timer',
                ],
                'og_image_path' => '/images/products/filtration/modular-filter/mif-modular-system-main.webp',
                'gallery' => [
                    '/images/products/filtration/modular-filter/mif-modular-system-main.webp',
                    '/images/products/filtration/modular-filter/mif-filter-station.webp',
                    '/images/products/filtration/modular-filter/mif-screen-element.webp',
                ],
                'sort_order' => 41,
                'meta_title' => 'MIF Series Modular Integrated Filter - PT Misuba Guna Indonesia',
                'meta_description' => 'Multi-station modular backwash filter system manufactured by Shanghai JCI Technology. Scalable 2-24 units, up to 4.0 MPa and 250°C for petrochemicals and water.',
                'canonical_url' => 'https://misubaguna.com/product/modular-integrated-backwash-filter/',
                'og_title' => 'MIF Series Modular Integrated Filter - PT Misuba Guna Indonesia',
                'og_description' => 'Modular integrated backwash filtration skid for high-pressure and high-temperature industrial fluid applications.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.9',
                'sitemap_changefreq' => 'monthly',
                'schema_json' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'bag-filter-system',
                'url_path' => '/product/bag-filter-system/',
                'name' => 'Industrial Bag Filter System (BT Series)',
                'product_group' => 'Filtration & Clarification',
                'product_subgroup' => 'Vessel & Cartridge Filters',
                'headline' => 'BT Series Single & Multi-Bag Precision Liquid Filter Housings',
                'summary' => 'Versatile pressure vessel bag filter housings supporting 1 to 24 bags with fast-opening davit covers, precision bypass-free sealing, and low operational cost.',
                'content_html' => '<h1>BT Series Industrial Bag Filter System</h1><p class="product-description">The BT Bag Filter is an economical, high-capacity pressure filtration vessel utilizing precision fabric or mesh filter bags supported by heavy-duty stainless steel baskets. Unfiltered fluid flows into the vessel through top or side connections, passing through the bag interior where contaminants are securely held, discharging purified liquid from the outlet with zero bypass.</p><h2>4 Versatile Subseries for Any Flow Capacity</h2><ul><li><strong>BTT Series (Single-Bag Top-Entry):</strong> Features a low-headroom contoured top-entry lid that channels fluid smoothly into the bag collar, providing high-precision filtration with zero bypass.</li><li><strong>BTS Series (Single-Bag Side-Entry):</strong> Standard economical side-inlet configuration for general industrial fluid filtration.</li><li><strong>BTF Series (Quick-Opening Multi-Bag):</strong> Engineered with an innovative rapid-clamping davit mechanism that opens and closes in just 20 seconds, drastically minimizing changeout downtime on high-flow applications.</li><li><strong>BTM Series (Heavy-Duty Multi-Bag):</strong> Multi-bag vessel supporting up to 24 filter bags for high flow capacities up to 1,000 m³/h without frequent bag replacements.</li></ul>',
                'key_features' => [
                    'BTF quick-opening multi-bag mechanism takes only 20 seconds to open and close',
                    'Contoured top-entry lid (BTT) guarantees zero bypass around filter bag collar',
                    'Electropolished stainless steel support basket ensures low pressure drop and easy cleaning',
                    'Accommodates 1 to 24 filter bags for flow rates up to 1,000 m³/h',
                    'Wide micron range from 0.5 µm up to 1,250 µm',
                ],
                'applications' => [
                    'Water treatment, papermaking, fine chemicals, automotive, mechanical processing',
                    'Petrochemical, paint & coatings, inks, resins, adhesives, electronics',
                    'Food & beverage, edible oil, wine, syrups, and parts washing fluids',
                ],
                'materials' => [
                    'Housing Material: Stainless Steel 304, 316L, Carbon Steel, or Plastic Strainer',
                    'Filter Bags: Polypropylene (PP), Polyester (PE), Nylon Monofilament (NO/NMO)',
                    'Seals & O-Rings: EPDM, Viton, PTFE-encapsulated Viton, Silicone',
                ],
                'technical_specs' => [
                    'Subseries: BTT, BTS, BTF, BTM',
                    'Number of Bags: 1 to 24 bags per vessel',
                    'Single Unit Flowrate: 1 to 1,000 m³/h',
                    'Filtration Accuracy: 0.5 µm to 1,250 µm',
                    'Filtering Area: 0.1 m² to 24 m²',
                    'Design Pressure: 0.6 to 1.0 MPa (custom higher ratings available)',
                    'Applicable Fluid Viscosity: 1 to 20,000 cP',
                ],
                'og_image_path' => '/images/products/filtration/bag-filter/bt-multibag-assembly.webp',
                'gallery' => [
                    '/images/products/filtration/bag-filter/bt-multibag-assembly.webp',
                    '/images/products/filtration/bag-filter/bt-series-lineup.webp',
                    '/images/products/filtration/bag-filter/bt-basket-and-bag.webp',
                ],
                'sort_order' => 42,
                'meta_title' => 'BT Series Industrial Bag Filter - PT Misuba Guna Indonesia',
                'meta_description' => 'Single and multi-bag filter vessels manufactured by Shanghai JCI Technology. 1-24 bags, up to 1000 m3/h, 20-second quick-opening davit covers.',
                'canonical_url' => 'https://misubaguna.com/product/bag-filter-system/',
                'og_title' => 'BT Series Industrial Bag Filter - PT Misuba Guna Indonesia',
                'og_description' => 'Industrial liquid bag filter housings with quick-open davit lids and precision bypass-free bag sealing.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.9',
                'sitemap_changefreq' => 'monthly',
                'schema_json' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'basket-strainer-filter',
                'url_path' => '/product/basket-strainer-filter/',
                'name' => 'Basket Strainer & Pipeline Filter (ST Series)',
                'product_group' => 'Filtration & Clarification',
                'product_subgroup' => 'Vessel & Cartridge Filters',
                'headline' => 'ST Series Single & Multi-Basket Heavy-Duty Pipeline Strainers',
                'summary' => 'Heavy-duty stainless steel basket strainers designed for high-capacity debris removal, pump and valve protection, and easy manual basket cleaning with reusable screen elements.',
                'content_html' => '<h1>ST Series Industrial Basket Filter & Strainer</h1><p class="product-description">The ST Basket Filter features heavy-duty stainless steel perforated and mesh filter baskets that intercept large particles and pipe debris. Baskets are easily removed, washed, and reused repeatedly, providing long service life with virtually zero consumable costs while protecting sensitive downstream pumps, flowmeters, and process equipment.</p><h2>4 Specialized Configuration Subseries</h2><ul><li><strong>STS Series (Single-Basket Quick-Open):</strong> Versatile single-basket configuration with quick-open upper cover, applicable across wide industrial process duties.</li><li><strong>STY Series (Inline Pipe Strainer):</strong> Inline horizontal design where inlet and outlet are situated along the same horizontal centerline, eliminating pipeline elbow bends and conserving plant floor space.</li><li><strong>STM Series (Multi-Basket Ultra-Flux):</strong> Multi-basket housing (up to 24 baskets) with quick-opening cover engineered for ultra-high flow capacities up to 33 m² filter area.</li><li><strong>STT Series (Single-Basket Inline):</strong> Single-basket compact inline housing with inlet and outlet along the same horizontal centerline.</li></ul>',
                'key_features' => [
                    'Reusable cleanable stainless steel basket minimizes recurring operational costs',
                    'Inline pipeline models (STY / STT) feature inlet and outlet on same horizontal central line',
                    'Eliminates pipeline elbow fittings, saving installation space and piping material',
                    'Multi-basket configuration (STM) provides ultra-large filtration area up to 33 m²',
                    'Davit arm and quick-open swing bolts allow rapid cleanout without special tools',
                ],
                'applications' => [
                    'Fine chemical engineering, water treatment systems, papermaking, automotive',
                    'Petrochemical engineering, mechanical processing, cooling circuits, machine coolant',
                    'Pump, valve, flowmeter, and spray nozzle protection across chemical plants',
                ],
                'materials' => [
                    'Housing Material: Stainless Steel 304, 316L, or Heavy Carbon Steel',
                    'Basket Construction: Heavy perforated stainless steel basket with wire mesh lining',
                ],
                'technical_specs' => [
                    'Subseries: STS, STT, STY, STM',
                    'Number of Baskets: 1 to 24 baskets',
                    'Filtration Accuracy: 1 µm to 8,000 µm',
                    'Single Filtering Area: 0.05 m² to 33 m²',
                    'Design Pressure: 0.6 to 1.0 MPa (custom higher available)',
                    'Applicable Fluid Viscosity: 1 to 30,000 cP',
                ],
                'og_image_path' => '/images/products/filtration/basket-filter/st-basket-strainer-main.webp',
                'gallery' => [
                    '/images/products/filtration/basket-filter/st-basket-strainer-main.webp',
                    '/images/products/filtration/basket-filter/st-multi-basket-stm.webp',
                    '/images/products/filtration/basket-filter/st-single-basket-sts.webp',
                    '/images/products/filtration/basket-filter/st-inline-pipe-stt.webp',
                    '/images/products/filtration/basket-filter/st-perforated-mesh-basket.webp',
                ],
                'sort_order' => 43,
                'meta_title' => 'ST Series Basket Strainer & Pipeline Filter - PT Misuba Guna Indonesia',
                'meta_description' => 'Heavy-duty stainless steel basket strainers and inline pipe filters manufactured by Shanghai JCI Technology. Up to 24 baskets, reusable mesh elements.',
                'canonical_url' => 'https://misubaguna.com/product/basket-strainer-filter/',
                'og_title' => 'ST Series Basket Strainer & Pipeline Filter - PT Misuba Guna Indonesia',
                'og_description' => 'Industrial basket filters and inline pipe strainers for pipeline and pump protection with reusable elements.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.9',
                'sitemap_changefreq' => 'monthly',
                'schema_json' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'cartridge-filter-housing',
                'url_path' => '/product/cartridge-filter-housing/',
                'name' => 'Precision Cartridge Filter Housing (CT Series)',
                'product_group' => 'Filtration & Clarification',
                'product_subgroup' => 'Vessel & Cartridge Filters',
                'headline' => 'CT Series Sanitary & Industrial Multi-Cartridge Filter Housings',
                'summary' => 'High-precision core filter housings for sub-micron sterile filtration, bacteria removal, and high-purity liquid polishing in industrial and sanitary applications.',
                'content_html' => '<h1>CT Series Industrial Cartridge Filter Housing</h1><p class="product-description">The CT Core Cartridge Filter is engineered for precision liquid clarification, sub-micron particle polishing, and microbial reduction. Accommodating 1 to 200 filter cartridges in vertical or horizontal vessels, the CT series offers superior filtration efficiency, low extractables, and generous dirt-holding capacity.</p><h2>4 Subseries Tailored to Process Specifications</h2><ul><li><strong>CTT Series (Economical Clamp):</strong> Lightweight clamp-closure vessel for low pressure and moderate flowrates.</li><li><strong>CTS Series (Heavy-Duty Clamp / Swing Bolt):</strong> Robust industrial housing designed for rigorous chemical and petrochemical duties.</li><li><strong>CTM Series (Large-Flux Multi-Cartridge):</strong> High-capacity vertical or horizontal housing holding up to 200 cartridges for large process flows.</li><li><strong>CTR Series (Sanitary / Edible-Grade):</strong> Mirror electropolished internal surface (Ra < 0.4 µm) with complete CIP/SIP dismantlement for food, beverage, and biopharmaceutical applications.</li></ul>',
                'key_features' => [
                    'High filtration precision down to 0.05 µm for bacteria and sub-micron particle removal',
                    'Sanitary model CTR features mirror electropolishing (Ra < 0.4 µm) with complete CIP/SIP dismantlement',
                    'Accommodates 1 to 200 filter cartridges in vertical or horizontal orientations',
                    'Compatible with 222, 226, DOE, and fin-type cartridge end-caps',
                    'Accepts all standard cartridge lengths: 10", 20", 30", 40", and 60"',
                ],
                'applications' => [
                    'Food & beverage, edible oils, dairy, beer, wine, bottled water, syrups',
                    'Pharmaceuticals & bioprocessing: sterile water, WFI, APIs, cosmetics',
                    'Fine chemicals, high-purity solvents, semiconductor chemicals, electronics',
                    'Water treatment: RO pre-filtration, EDI polishing, boiler feed pre-treatment',
                ],
                'materials' => [
                    'Housing Material: Stainless Steel 304, 316L, or Carbon Steel',
                    'Internal Finish: Standard industrial pickle/passivate or Sanitary mirror electropolish (Ra < 0.4 µm)',
                    'O-Rings & Gaskets: FDA Silicone, EPDM, Viton, PTFE-encapsulated',
                ],
                'technical_specs' => [
                    'Subseries: CTT, CTS, CTM, CTR',
                    'Number of Cartridges: 1 to 200 cartridges',
                    'Cartridge Lengths: 10", 20", 30", 40", 60"',
                    'Filtration Accuracy: 0.05 µm to 200 µm',
                    'Design Pressure: 0.6 to 1.0 MPa (custom higher customizable)',
                    'Applicable Fluid Viscosity: 1 to 500 cP',
                ],
                'og_image_path' => '/images/products/filtration/cartridge-filter/ct-cartridge-housing-main.webp',
                'gallery' => [
                    '/images/products/filtration/cartridge-filter/ct-cartridge-housing-main.webp',
                    '/images/products/filtration/cartridge-filter/ct-cartridge-elements.webp',
                    '/images/products/filtration/cartridge-filter/ct-multicartridge-ctm.webp',
                    '/images/products/filtration/cartridge-filter/ct-sanitary-ctr.webp',
                ],
                'sort_order' => 44,
                'meta_title' => 'CT Series Cartridge Filter Housing - PT Misuba Guna Indonesia',
                'meta_description' => 'Precision multi-cartridge filter housings manufactured by Shanghai JCI Technology. Industrial and sanitary CTR models holding 1-200 cartridges.',
                'canonical_url' => 'https://misubaguna.com/product/cartridge-filter-housing/',
                'og_title' => 'CT Series Cartridge Filter Housing - PT Misuba Guna Indonesia',
                'og_description' => 'High-precision sanitary and industrial cartridge filter vessels for food, beverage, pharmaceutical, and chemical polishing.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.9',
                'sitemap_changefreq' => 'monthly',
                'schema_json' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'centrifugal-solid-liquid-separator',
                'url_path' => '/product/centrifugal-solid-liquid-separator/',
                'name' => 'Centrifugal Separator & Rotary Filter (CS & RS Series)',
                'product_group' => 'Filtration & Clarification',
                'product_subgroup' => 'Separators & Iron Removers',
                'headline' => 'CS Centrifugal Solid-Liquid Separator & RS Secondary Rotary Filter',
                'summary' => 'Maintenance-free hydrocyclone centrifugal sand separators and rotary secondary screen filters for removing high-density solids without filter media.',
                'content_html' => '<h1>CS Centrifugal Separator & RS Rotary Filter</h1><p class="product-description">The CS Series Solid Separator utilizes centrifugal vortex dynamics to separate precipitable solids and sand without internal moving components or consumable filter elements. The RS Series combines centrifugal pre-separation with a secondary cylindrical stainless steel screen to capture fine solids down to 25 µm with greater than 90% separation efficiency.</p><h2>CS Hydrocyclone Operating Principle</h2><p>Process fluid enters the tangential acceleration chamber at high velocity, generating an intense vortex. Heavy particles (> 40 µm at 98% efficiency down to 5 µm) are forced outward against the conical wall and spiral down into the bottom quiet collection chamber. Purified liquid spirals upward through the central vortex finder. The collection chamber purges accumulated solids automatically via an automated timed ball valve.</p><h2>RS Dual-Stage Rotary Filtration</h2><p>For applications where fine suspended particles must be caught alongside dense grit, the RS Rotary Filter adds a secondary stainless steel filter screen. High-density debris separates centrifugally, while remaining low-density solids are held on the screen without recurring consumables.</p>',
                'key_features' => [
                    'Zero moving parts in CS Separator: maintenance-free operation with no consumable elements',
                    'Separates 98% of solid particles larger than 40 µm, separates particles down to 5 µm',
                    'Continuous automatic discharge via automated bottom purge ball valve',
                    'Extremely low and constant pressure drop: only 0.02 to 0.07 MPa',
                    'RS Rotary Filter adds secondary metal screen stage for solids down to 25 µm',
                    'High flow handling from 4 m³/h up to 1,145 m³/h',
                ],
                'applications' => [
                    'Water treatment: river water, seawater, reservoir water, borehole desanding, groundwater',
                    'Industrial circulating water, cooling tower basin desanding, heat exchanger protection',
                    'Metal processing: machining coolant, parts washing fluids, grinding chips',
                    'Petrochemical engineering, papermaking, biochemical pharmacy, mining slurries',
                ],
                'materials' => [
                    'Housing Material: Stainless Steel 304, 316L, or Heavy Carbon Steel',
                    'Purge Valve: Automated pneumatic or electric full-port ball valve',
                ],
                'technical_specs' => [
                    'Inlet/Outlet Sizes: DN25 to DN300 (CS Series), DN25 to DN80 (RS Series)',
                    'Flowrate Capacity: 4 to 1,145 m³/h (CS), 5 to 55 m³/h (RS)',
                    'Separation Efficiency: Up to 98% for >40 µm particles; separates down to 5 µm',
                    'Applicable Fluid Viscosity: 1 to 40 cP',
                    'Operating Temperature: Up to 200°C (CS), up to 80°C (RS)',
                    'Design Pressure: 0.6 to 1.0 MPa',
                    'Pressure Drop: 0.02 to 0.07 MPa',
                ],
                'og_image_path' => '/images/products/filtration/centrifugal-separator/cs-centrifugal-separator-main.webp',
                'gallery' => [
                    '/images/products/filtration/centrifugal-separator/cs-centrifugal-separator-main.webp',
                    '/images/products/filtration/centrifugal-separator/rs-rotary-filter-main.webp',
                    '/images/products/filtration/centrifugal-separator/cs-separator-onsite.webp',
                ],
                'sort_order' => 45,
                'meta_title' => 'CS Centrifugal Separator & RS Rotary Filter - PT Misuba Guna Indonesia',
                'meta_description' => 'Hydrocyclone sand separator and rotary secondary filter manufactured by Shanghai JCI Technology. Zero moving parts, 98% efficiency down to 5 micron.',
                'canonical_url' => 'https://misubaguna.com/product/centrifugal-solid-liquid-separator/',
                'og_title' => 'CS Centrifugal Separator & RS Rotary Filter - PT Misuba Guna Indonesia',
                'og_description' => 'Maintenance-free centrifugal solid-liquid separators and sand hydrocyclones for water and industrial fluids.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.9',
                'sitemap_changefreq' => 'monthly',
                'schema_json' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'magnetic-iron-remover',
                'url_path' => '/product/magnetic-iron-remover/',
                'name' => 'MS High-Intensity Magnetic Iron Remover',
                'product_group' => 'Filtration & Clarification',
                'product_subgroup' => 'Separators & Iron Removers',
                'headline' => 'MS Series 12,000 Gauss Super-Magnetic Liquid Iron Remover',
                'summary' => 'Ultra-high-intensity 12,000 Gauss NdFeB permanent magnetic separator for capturing microscopic ferromagnetic particles, rust, cobalt, and nickel from liquid streams.',
                'content_html' => '<h1>MS Strong Magnetic Iron Remover</h1><p class="product-description">The MS Iron Remover is engineered to eliminate microscopic ferromagnetic contaminants—such as pipeline rust, weld slag, wear particles, cobalt, and nickel—from liquid product streams. Optimized via 3D finite element magnetic circuit modeling, the MS device houses superpower NdFeB (Neodymium Iron Boron) permanent magnetic bars generating a peak surface field of 12,000 Gauss, the highest permanent magnetic intensity in the world.</p><h2>Protecting High-Value Equipment & Product Purity</h2><p>Sub-micron ferrous particles bypass standard mechanical screens and cause catastrophic wear to downstream homogenizers, progressive cavity pumps, mechanical seals, and nozzles, while spoiling high-purity paints, food, and pharmaceutical formulations. The MS Series traps iron particles tightly against the non-magnetic stainless steel tube sleeves. The quick-open clamp or swing-bolt lid allows rapid removal of the magnetic grid for wipe cleaning.</p>',
                'key_features' => [
                    'Peak magnetic surface intensity of 12,000 Gauss using top-tier NdFeB permanent magnets',
                    '3D finite element optimized magnetic circuit maximizes particle capture field and gradient',
                    'Captures microscopic ferromagnetic impurities (iron, rust, scrap metal, cobalt, nickel)',
                    'Quick-opening sanitary clamp or swing-bolt lid for fast magnetic bar cluster extraction',
                    '100% Stainless steel construction (SS304 / SS316L) with sanitary mirror finish',
                    'Zero electrical power required; permanent magnetic strength never deteriorates',
                ],
                'applications' => [
                    'Food & beverage: chocolate, syrups, dairy, fruit juices, edible oils, infant formula',
                    'Metal processing: machining lubricants, honing fluids, cutting oil, stamped parts wash',
                    'Pharmaceutical & cosmetics: liquid syrups, ointment bases, API suspensions',
                    'Ceramics, glazes, lithium battery slurries, paints, inks, and paper coating color',
                ],
                'materials' => [
                    'Housing Material: Stainless Steel 304, 316L',
                    'Magnetic Rods: Heavy-wall SS316L seamless tubes with NdFeB permanent magnet cores',
                    'Seals: Food-grade Silicone, EPDM, or Viton',
                ],
                'technical_specs' => [
                    'Subseries: MS3 to MS24 (3 to 24 magnetic rods)',
                    'Caliber Sizes: DN25 to DN600 (1" to 24")',
                    'Magnetic Field Peak Intensity: 12,000 Gauss',
                    'Operating Temperature: Less than 80°C (higher temperature up to 250°C customizable)',
                    'Design Pressure: 0.6 to 1.0 MPa (higher pressure customizable)',
                    'Separation Type: Magnetic trapping',
                ],
                'og_image_path' => '/images/products/filtration/magnetic-separator/ms-magnetic-remover-main.webp',
                'gallery' => [
                    '/images/products/filtration/magnetic-separator/ms-magnetic-remover-main.webp',
                    '/images/products/filtration/magnetic-separator/ms-magnetic-bars-cluster.webp',
                    '/images/products/filtration/magnetic-separator/ms-sanitary-housing.webp',
                    '/images/products/filtration/magnetic-separator/ms-magnetic-cartridge.webp',
                ],
                'sort_order' => 46,
                'meta_title' => 'MS Series Magnetic Iron Remover - PT Misuba Guna Indonesia',
                'meta_description' => '12,000 Gauss NdFeB high-intensity permanent magnetic iron remover manufactured by Shanghai JCI Technology. DN25-DN600 for food, paint, chocolate, and lubricants.',
                'canonical_url' => 'https://misubaguna.com/product/magnetic-iron-remover/',
                'og_title' => 'MS Series Magnetic Iron Remover - PT Misuba Guna Indonesia',
                'og_description' => 'Super-power 12,000 Gauss NdFeB permanent magnetic separator for capturing fine iron contaminants in fluid pipelines.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.9',
                'sitemap_changefreq' => 'monthly',
                'schema_json' => null,
                'is_published' => true,
            ],
            [
                'slug' => 'filter-cartridges-bags-consumables',
                'url_path' => '/product/filter-cartridges-bags-consumables/',
                'name' => 'Precision Filter Cartridges & Bags',
                'product_group' => 'Filtration & Clarification',
                'product_subgroup' => 'Consumables & Filter Elements',
                'headline' => 'High-Performance Precision Filter Cartridges, Bags & Replacement Media',
                'summary' => 'Comprehensive range of pleated, melt-blown, wire-wound, sintered metal, titanium rod cartridges and absolute liquid filter bags manufactured under cleanroom standards.',
                'content_html' => '<h1>Precision Filter Cartridges & Bags</h1><p class="product-description">As the core of CT Cartridge Filters and BT Bag Filters, filter cartridges and bags dictate final filtrate clarity and process uptime. Manufactured under strict ISO 9001 and cleanroom quality control, Shanghai JCI filter cartridges and bags utilize premium global base media engineered for high dirt-holding capacity, low initial pressure drop, and extended on-stream life.</p><h2>Comprehensive Filter Cartridge Portfolio</h2><ul><li><strong>Pleated Membrane Cartridges:</strong> High-surface area pleated PP, PES, PTFE, and PVDF membranes for sub-micron sterile and high-clarity filtration (0.05 µm to 50 µm).</li><li><strong>Melt-Blown PP Cartridges:</strong> Thermally bonded virgin polypropylene with graded pore density for depth filtration.</li><li><strong>Wire-Wound Cartridges:</strong> Precision CNC string-wound elements for high-temperature and high-solids fluid service.</li><li><strong>Sintered Metal & Titanium Rods:</strong> Sintered porous SS316L and titanium elements built for extreme temperatures, high differential pressures, and aggressive solvents. Cleanable and backwashable for repeated reuse.</li><li><strong>Large Flow Elements:</strong> 6-inch large diameter pleated elements handling high flux up to 80 m³/h per element.</li></ul><h2>Liquid Filter Bags & Sealing Rings</h2><p>Available in polypropylene needle felt, polyester, and woven nylon monofilament mesh (NMO/NO) from 0.5 to 1,250 microns. Features heavy-duty stainless steel collar rings or molded polypropylene SDS collars with zero-bypass extension lips.</p>',
                'key_features' => [
                    'Manufactured in certified cleanroom environments under strict ISO 9001 and FDA quality control',
                    'Standard cartridge interfaces: Code 7 (226 O-ring/fin), Code 8 (222 O-ring/fin), DOE, and Fin',
                    'Standard lengths: 10", 20", 30", 40", and 60"',
                    'Micron rating spectrum: 0.05 µm up to 1,250 µm (10 to 15,000 mesh)',
                    'Extreme chemical and thermal resistance options (PTFE, Sintered SS316L, Titanium)',
                    'Positive sealing rings and collar designs guarantee 100% bypass-free filtration',
                ],
                'applications' => [
                    'High-purity chemical processing, semiconductor DI water, catalyst recovery',
                    'Food & beverage sterile filtration, beer, wine, bottled water, dairy',
                    'Pharmaceuticals: WFI, sterile venting, bio-solutions, ophthalmic preparations',
                    'Palm oil & oleochemicals: polishing, bleaching earth filtration, fatty acids',
                    'Industrial water treatment: RO pre-filtration, condensate, boiler feedwater',
                ],
                'materials' => [
                    'Cartridge Media: Polypropylene (PP), PES, PTFE, Nylon, Sintered SS316L, Titanium Powder',
                    'Filter Bag Media: Needle-felt PP/PE, Nylon Monofilament (NMO), Multi-layer Melt-Blown',
                    'Collars & Rings: Stainless Steel snap ring, molded polypropylene Polyform collar',
                ],
                'technical_specs' => [
                    'Cartridge Diameters: Standard 2.5" (64 mm) and Large Flow 6" (152 mm)',
                    'Lengths: 10", 20", 30", 40", 60"',
                    'Cartridge Connections: 222 O-ring, 226 O-ring, DOE (Double Open End), Fin',
                    'Bag Sizes: Size 1 (7"x17"), Size 2 (7"x32"), Size 3 (4"x9"), Size 4 (4"x15")',
                    'Micron Ratings: 0.05 µm to 1,250 µm',
                    'Max Operating Temperature: Up to 260°C (metallic/titanium media)',
                ],
                'og_image_path' => '/images/products/filtration/consumables/filter-cartridges-types.webp',
                'gallery' => [
                    '/images/products/filtration/consumables/filter-cartridges-types.webp',
                    '/images/products/filtration/consumables/filter-bags-types.webp',
                    '/images/products/filtration/consumables/pleated-cartridge.webp',
                    '/images/products/filtration/consumables/melt-blown-cartridge.webp',
                    '/images/products/filtration/consumables/titanium-rod-cartridge.webp',
                    '/images/products/filtration/consumables/large-flow-cartridge.webp',
                    '/images/products/filtration/consumables/wire-wound-cartridge.webp',
                    '/images/products/filtration/consumables/sintered-metal-cartridge.webp',
                    '/images/products/filtration/consumables/ss-collar-filter-bag.webp',
                    '/images/products/filtration/consumables/nylon-mesh-filter-bag.webp',
                    '/images/products/filtration/consumables/absolute-liquid-filter-bag.webp',
                ],
                'sort_order' => 47,
                'meta_title' => 'Filter Cartridges & Bags Consumables - PT Misuba Guna Indonesia',
                'meta_description' => 'Precision pleated, melt-blown, sintered metal, titanium filter cartridges and liquid filter bags manufactured by Shanghai JCI Technology.',
                'canonical_url' => 'https://misubaguna.com/product/filter-cartridges-bags-consumables/',
                'og_title' => 'Filter Cartridges & Bags Consumables - PT Misuba Guna Indonesia',
                'og_description' => 'High-performance filter cartridges and bags for industrial fluid filtration, 0.05 to 1,250 micron.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.8',
                'sitemap_changefreq' => 'monthly',
                'schema_json' => null,
                'is_published' => true,
            ],
        ];

        foreach ($products as $product) {
            $payload = [
                'name' => $product['name'],
                'product_group' => $product['product_group'],
                'product_subgroup' => $product['product_subgroup'],
                'headline' => $product['headline'],
                'summary' => $product['summary'],
                'content_html' => $product['content_html'],
                'key_features' => json_encode($product['key_features']),
                'applications' => json_encode($product['applications']),
                'materials' => json_encode($product['materials']),
                'technical_specs' => json_encode($product['technical_specs']),
                'gallery' => $product['gallery'] ? json_encode($product['gallery']) : null,
                'sort_order' => $product['sort_order'],
                'meta_title' => $product['meta_title'],
                'meta_description' => $product['meta_description'],
                'canonical_url' => $product['canonical_url'],
                'og_title' => $product['og_title'],
                'og_description' => $product['og_description'],
                'og_image_path' => $product['og_image_path'],
                'robots_index' => $product['robots_index'],
                'robots_follow' => $product['robots_follow'],
                'sitemap_include' => $product['sitemap_include'],
                'sitemap_priority' => $product['sitemap_priority'],
                'sitemap_changefreq' => $product['sitemap_changefreq'],
                'schema_json' => $product['schema_json'],
                'is_published' => $product['is_published'],
                'updated_at' => $now,
            ];

            $exists = DB::table('public_products')->where('slug', $product['slug'])->first();
            if ($exists) {
                DB::table('public_products')->where('slug', $product['slug'])->update($payload);
            } else {
                DB::table('public_products')->insert(array_merge($payload, [
                    'slug' => $product['slug'],
                    'url_path' => $product['url_path'],
                    'created_at' => $now,
                ]));
            }
        }
    }
}
