<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PublicSiteSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $pages = [
            [
                'page_type' => 'home', 'slug' => 'home', 'url_path' => '/',
                'title' => 'PT Misuba Guna Indonesia - Build on Trust, Driving on Excellence',
                'headline' => 'PT Misuba Guna Indonesia',
                'excerpt' => 'Partner with PT Misuba Guna Indonesia for reliable, high-quality technical solutions. We drive business forward with innovation, excellence, and trust.',
                'content_html' => null, 'sections' => null,
                'meta_title' => 'PT Misuba Guna Indonesia - Build on Trust, Driving on Excellence',
                'meta_description' => 'Partner with PT Misuba Guna Indonesia for reliable, high-quality technical solutions. We drive business forward with innovation, excellence, and trust.',
                'canonical_url' => 'https://misubaguna.com/',
                'og_title' => 'PT Misuba Guna Indonesia - Build on Trust, Driving on Excellence',
                'og_description' => 'Partner with PT Misuba Guna Indonesia for reliable, high-quality technical solutions. We drive business forward with innovation, excellence, and trust.',
                'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true,
                'sitemap_include' => true, 'sitemap_priority' => '1.0', 'sitemap_changefreq' => 'weekly',
                'schema_json' => null, 'is_published' => true, 'published_at' => null, 'sort_order' => 1,
            ],
            [
                'page_type' => 'page', 'slug' => 'about-us', 'url_path' => '/about-us/',
                'title' => 'About Misuba | Quality Engineering Products & Services',
                'headline' => 'About Us / About Misuba',
                'excerpt' => 'PT Misuba Guna Indonesia Providing quality engineering products & services at competitive prices with fast delivery and trusted global partnerships since 2020.',
                'content_html' => null, 'sections' => null,
                'meta_title' => 'About Misuba | Quality Engineering Products & Services',
                'meta_description' => 'PT Misuba Guna Indonesia Providing quality engineering products & services at competitive prices with fast delivery and trusted global partnerships since 2020.',
                'canonical_url' => 'https://misubaguna.com/about-us/',
                'og_title' => 'About Misuba | Quality Engineering Products & Services',
                'og_description' => 'PT Misuba Guna Indonesia Providing quality engineering products & services at competitive prices with fast delivery and trusted global partnerships since 2020.',
                'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true,
                'sitemap_include' => true, 'sitemap_priority' => '0.8', 'sitemap_changefreq' => 'monthly',
                'schema_json' => null, 'is_published' => true, 'published_at' => null, 'sort_order' => 2,
            ],
            [
                'page_type' => 'project_list', 'slug' => 'project-list', 'url_path' => '/project-list/',
                'title' => 'Project List - PT Misuba Guna Indonesia',
                'headline' => 'Project List',
                'excerpt' => 'MGI supports industrial customers through project-based supply, fabrication, repair, and technical sourcing across multiple product groups.',
                'content_html' => null, 'sections' => null,
                'meta_title' => 'Project List - PT Misuba Guna Indonesia',
                'meta_description' => 'MGI supports industrial customers through project-based supply, fabrication, repair, and technical sourcing across multiple product groups.',
                'canonical_url' => 'https://misubaguna.com/project-list/',
                'og_title' => 'Project List - PT Misuba Guna Indonesia',
                'og_description' => 'MGI supports industrial customers through project-based supply, fabrication, repair, and technical sourcing across multiple product groups.',
                'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true,
                'sitemap_include' => true, 'sitemap_priority' => '0.8', 'sitemap_changefreq' => 'monthly',
                'schema_json' => null, 'is_published' => true, 'published_at' => null, 'sort_order' => 3,
            ],
            [
                'page_type' => 'contact', 'slug' => 'contact-us', 'url_path' => '/contact-us/',
                'title' => 'Contact Us - Get in Touch with PT Misuba Guna Indonesia',
                'headline' => 'Contact Us / Get in Touch',
                'excerpt' => 'Contact page with operational office, warehouse, billing address, telephone, WhatsApp, email, website, and inquiry form.',
                'content_html' => null, 'sections' => null,
                'meta_title' => 'Contact Us - Get in Touch with PT Misuba Guna Indonesia',
                'meta_description' => 'Contact PT Misuba Guna Indonesia for engineering products and services. Office, warehouse, telephone, WhatsApp, email, and sales inquiries.',
                'canonical_url' => 'https://misubaguna.com/contact-us/',
                'og_title' => 'Contact Us - Get in Touch with PT Misuba Guna Indonesia',
                'og_description' => 'Contact PT Misuba Guna Indonesia for engineering products and services.',
                'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true,
                'sitemap_include' => true, 'sitemap_priority' => '0.8', 'sitemap_changefreq' => 'monthly',
                'schema_json' => null, 'is_published' => true, 'published_at' => null, 'sort_order' => 4,
            ],
            [
                'page_type' => 'career', 'slug' => 'career', 'url_path' => '/career/',
                'title' => 'Careers at Misuba | Join Our Team & Grow With Us',
                'headline' => 'Careers at Misuba / Join Our Team & Grow With Us',
                'excerpt' => 'Careers at Misuba – Join our team and grow with us. Explore exciting opportunities in engineering, marketing, supply chain, and more.',
                'content_html' => null, 'sections' => null,
                'meta_title' => 'Careers at Misuba | Join Our Team & Grow With Us',
                'meta_description' => 'Careers at Misuba – Join our team and grow with us. Explore exciting opportunities in engineering, marketing, supply chain, and more.',
                'canonical_url' => 'https://misubaguna.com/career/',
                'og_title' => 'Careers at Misuba | Join Our Team & Grow With Us',
                'og_description' => 'Careers at Misuba – Join our team and grow with us. Explore exciting opportunities in engineering, marketing, supply chain, and more.',
                'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true,
                'sitemap_include' => true, 'sitemap_priority' => '0.8', 'sitemap_changefreq' => 'monthly',
                'schema_json' => null, 'is_published' => true, 'published_at' => null, 'sort_order' => 5,
            ],
            [
                'page_type' => 'catalog', 'slug' => 'catalog', 'url_path' => '/catalog/',
                'title' => 'Catalog - PT Misuba Guna Indonesia',
                'headline' => 'Catalog',
                'excerpt' => 'Download or view PT Misuba Guna Indonesia company profile and product catalog documents.',
                'content_html' => null, 'sections' => null,
                'meta_title' => 'Catalog - PT Misuba Guna Indonesia',
                'meta_description' => 'Download or view PT Misuba Guna Indonesia company profile and product catalog documents.',
                'canonical_url' => 'https://misubaguna.com/catalog/',
                'og_title' => 'Catalog - PT Misuba Guna Indonesia',
                'og_description' => 'Download or view PT Misuba Guna Indonesia company profile and product catalog documents.',
                'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true,
                'sitemap_include' => true, 'sitemap_priority' => '0.8', 'sitemap_changefreq' => 'monthly',
                'schema_json' => null, 'is_published' => true, 'published_at' => null, 'sort_order' => 6,
            ],
        ];

        foreach ($pages as $page) {
            DB::table('public_pages')->updateOrInsert(
                ['url_path' => $page['url_path']],
                array_merge($page, ['created_at' => $now, 'updated_at' => $now])
            );
        }

        $categories = [
            ['slug' => 'corrosion-protection', 'url_path' => '/product-category/corrosion-protection/', 'name' => 'Corrosion Protection', 'summary' => 'Products and services for protecting industrial equipment against corrosion, abrasion, chemical attack, and severe operating conditions.', 'description_html' => null, 'parent_group' => 'Corrosion Protection', 'sort_order' => 1, 'meta_title' => 'Corrosion Protection Products - PT Misuba Guna Indonesia', 'meta_description' => 'Products and services for protecting industrial equipment against corrosion, abrasion, chemical attack, and severe operating conditions.', 'canonical_url' => 'https://misubaguna.com/product-category/corrosion-protection/', 'og_title' => 'Corrosion Protection Products - PT Misuba Guna Indonesia', 'og_description' => 'Products and services for protecting industrial equipment against corrosion, abrasion, chemical attack, and severe operating conditions.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.5', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'coating', 'url_path' => '/product-category/coating/', 'name' => 'Coating', 'summary' => 'Ceramic coating and PTFE coating options for surface protection in industrial applications.', 'description_html' => null, 'parent_group' => null, 'sort_order' => 2, 'meta_title' => 'Coating Products - PT Misuba Guna Indonesia', 'meta_description' => 'Ceramic coating and PTFE coating options for surface protection in industrial applications.', 'canonical_url' => 'https://misubaguna.com/product-category/coating/', 'og_title' => 'Coating Products - PT Misuba Guna Indonesia', 'og_description' => 'Ceramic coating and PTFE coating options for surface protection in industrial applications.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.5', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'rubber-hose', 'url_path' => '/product-category/rubber-hose/', 'name' => 'Rubber Hose', 'summary' => 'Industrial rubber hose products for air, water, oil, fuel, steam, chemical, food-grade, and general transfer applications.', 'description_html' => null, 'parent_group' => null, 'sort_order' => 3, 'meta_title' => 'Rubber Hose Products - PT Misuba Guna Indonesia', 'meta_description' => 'Industrial rubber hose products for air, water, oil, fuel, steam, chemical, food-grade, and general transfer applications.', 'canonical_url' => 'https://misubaguna.com/product-category/rubber-hose/', 'og_title' => 'Rubber Hose Products - PT Misuba Guna Indonesia', 'og_description' => 'Industrial rubber hose products for air, water, oil, fuel, steam, chemical, food-grade, and general transfer applications.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.5', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'ptfe-expansion-joint', 'url_path' => '/product-category/ptfe-expansion-joint/', 'name' => 'PTFE Expansion Joint', 'summary' => 'PTFE expansion joint products for chemical-resistant, clean, and high-purity piping applications.', 'description_html' => null, 'parent_group' => null, 'sort_order' => 4, 'meta_title' => 'PTFE Expansion Joint Products - PT Misuba Guna Indonesia', 'meta_description' => 'PTFE expansion joint products for chemical-resistant, clean, and high-purity piping applications.', 'canonical_url' => 'https://misubaguna.com/product-category/ptfe-expansion-joint/', 'og_title' => 'PTFE Expansion Joint Products - PT Misuba Guna Indonesia', 'og_description' => 'PTFE expansion joint products for chemical-resistant, clean, and high-purity piping applications.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.5', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'sealing-system', 'url_path' => '/product-category/sealing-system/', 'name' => 'Sealing System', 'summary' => 'Industrial sealing products including gland packing, oil seals, O-rings, gasket sheets, and mechanical seals.', 'description_html' => null, 'parent_group' => 'Sealing System', 'sort_order' => 5, 'meta_title' => 'Sealing System Products - PT Misuba Guna Indonesia', 'meta_description' => 'Industrial sealing products including gland packing, oil seals, O-rings, gasket sheets, and mechanical seals.', 'canonical_url' => 'https://misubaguna.com/product-category/sealing-system/', 'og_title' => 'Sealing System Products - PT Misuba Guna Indonesia', 'og_description' => 'Industrial sealing products including gland packing, oil seals, O-rings, gasket sheets, and mechanical seals.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.5', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'gasket-sheet', 'url_path' => '/product-category/gasket-sheet/', 'name' => 'Gasket Sheet', 'summary' => 'Gasket sheet materials and custom-cut gasket supply for industrial sealing applications.', 'description_html' => null, 'parent_group' => null, 'sort_order' => 6, 'meta_title' => 'Gasket Sheet Products - PT Misuba Guna Indonesia', 'meta_description' => 'Gasket sheet materials and custom-cut gasket supply for industrial sealing applications.', 'canonical_url' => 'https://misubaguna.com/product-category/gasket-sheet/', 'og_title' => 'Gasket Sheet Products - PT Misuba Guna Indonesia', 'og_description' => 'Gasket sheet materials and custom-cut gasket supply for industrial sealing applications.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.5', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
        ];

        foreach ($categories as $category) {
            DB::table('public_product_categories')->updateOrInsert(
                ['url_path' => $category['url_path']],
                array_merge($category, ['created_at' => $now, 'updated_at' => $now])
            );
        }

        $products = [
            ['slug' => 'fabric-expansion-joint', 'url_path' => '/product/fabric-expansion-joint/', 'name' => 'Fabric Expansion Joint', 'product_group' => 'Flexible Joint', 'product_subgroup' => null, 'headline' => 'Fabric Expansion Joint', 'summary' => 'Flexible non-metallic expansion joints for ducting and piping systems that need movement absorption, vibration isolation, and high-temperature sealing.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 1, 'meta_title' => 'Fabric Expansion Joint - PT Misuba Guna Indonesia', 'meta_description' => 'Flexible non-metallic expansion joints for ducting and piping systems that need movement absorption, vibration isolation, and high-temperature sealing.', 'canonical_url' => 'https://misubaguna.com/product/fabric-expansion-joint/', 'og_title' => 'Fabric Expansion Joint - PT Misuba Guna Indonesia', 'og_description' => 'Flexible non-metallic expansion joints for ducting and piping systems that need movement absorption, vibration isolation, and high-temperature sealing.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'metal-expansion-joint', 'url_path' => '/product/metal-expansion-joint/', 'name' => 'Metal Expansion Joint', 'product_group' => 'Flexible Joint', 'product_subgroup' => null, 'headline' => 'Metal Expansion Joint', 'summary' => 'Precision-engineered metal bellows expansion joints for absorbing thermal expansion, vibration, and mechanical movement in piping and duct systems.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 2, 'meta_title' => 'Metal Expansion Joint - PT Misuba Guna Indonesia', 'meta_description' => 'Precision-engineered metal bellows expansion joints for absorbing thermal expansion, vibration, and mechanical movement in piping and duct systems.', 'canonical_url' => 'https://misubaguna.com/product/metal-expansion-joint/', 'og_title' => 'Metal Expansion Joint - PT Misuba Guna Indonesia', 'og_description' => 'Precision-engineered metal bellows expansion joints for absorbing thermal expansion, vibration, and mechanical movement in piping and duct systems.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'rubber-expansion-joint', 'url_path' => '/product/rubber-expansion-joint/', 'name' => 'Rubber Expansion Joint', 'product_group' => 'Flexible Joint', 'product_subgroup' => null, 'headline' => 'Rubber Expansion Joint', 'summary' => 'Flexible rubber connectors for piping systems that absorb movement, isolate vibration, and compensate for thermal expansion or misalignment.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 3, 'meta_title' => 'Rubber Expansion Joint - PT Misuba Guna Indonesia', 'meta_description' => 'Flexible rubber connectors for piping systems that absorb movement, isolate vibration, and compensate for thermal expansion or misalignment.', 'canonical_url' => 'https://misubaguna.com/product/rubber-expansion-joint/', 'og_title' => 'Rubber Expansion Joint - PT Misuba Guna Indonesia', 'og_description' => 'Flexible rubber connectors for piping systems that absorb movement, isolate vibration, and compensate for thermal expansion or misalignment.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'ptfe-expansion-joint', 'url_path' => '/product/ptfe-expansion-joint/', 'name' => 'PTFE Expansion Joint', 'product_group' => 'Flexible Joint', 'product_subgroup' => null, 'headline' => 'PTFE Expansion Joint', 'summary' => 'PTFE expansion joints for clean, corrosive, high-purity, and chemically aggressive service where non-stick and chemical resistance are required.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 4, 'meta_title' => 'PTFE Expansion Joint - PT Misuba Guna Indonesia', 'meta_description' => 'PTFE expansion joints for clean, corrosive, high-purity, and chemically aggressive service where non-stick and chemical resistance are required.', 'canonical_url' => 'https://misubaguna.com/product/ptfe-expansion-joint/', 'og_title' => 'PTFE Expansion Joint - PT Misuba Guna Indonesia', 'og_description' => 'PTFE expansion joints for clean, corrosive, high-purity, and chemically aggressive service where non-stick and chemical resistance are required.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'ptfe-lined-rubber-metal-expansion-joint', 'url_path' => '/product/ptfe-lined-rubber-metal-expansion-joint/', 'name' => 'PTFE Lined Expansion Joint (Rubber and Metal)', 'product_group' => 'Flexible Joint', 'product_subgroup' => null, 'headline' => 'PTFE Lined Expansion Joint (Rubber and Metal)', 'summary' => 'PTFE-lined rubber or metal expansion joints that combine movement absorption with internal chemical protection for aggressive media.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 5, 'meta_title' => 'PTFE Lined Expansion Joint (Rubber and Metal) - PT Misuba Guna Indonesia', 'meta_description' => 'PTFE-lined rubber or metal expansion joints that combine movement absorption with internal chemical protection for aggressive media.', 'canonical_url' => 'https://misubaguna.com/product/ptfe-lined-rubber-metal-expansion-joint/', 'og_title' => 'PTFE Lined Expansion Joint (Rubber and Metal) - PT Misuba Guna Indonesia', 'og_description' => 'PTFE-lined rubber or metal expansion joints that combine movement absorption with internal chemical protection for aggressive media.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'rubber-hose', 'url_path' => '/product/rubber-hose/', 'name' => 'Rubber Hose', 'product_group' => 'Flexible Joint', 'product_subgroup' => null, 'headline' => 'Rubber Hose', 'summary' => 'Industrial rubber hoses for transferring air, water, oil, fuel, steam, chemicals, food-grade materials, and other process media.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 6, 'meta_title' => 'Rubber Hose - PT Misuba Guna Indonesia', 'meta_description' => 'Industrial rubber hoses for transferring air, water, oil, fuel, steam, chemicals, food-grade materials, and other process media.', 'canonical_url' => 'https://misubaguna.com/product/rubber-hose/', 'og_title' => 'Rubber Hose - PT Misuba Guna Indonesia', 'og_description' => 'Industrial rubber hoses for transferring air, water, oil, fuel, steam, chemicals, food-grade materials, and other process media.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'flexible-metal-hose', 'url_path' => '/product/flexible-metal-hose/', 'name' => 'Flexible Metal Hose', 'product_group' => 'Flexible Joint', 'product_subgroup' => null, 'headline' => 'Flexible Metal Hose', 'summary' => 'Stainless steel flexible metal hoses designed for demanding temperature, pressure, vibration, and corrosive service.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 7, 'meta_title' => 'Flexible Metal Hose - PT Misuba Guna Indonesia', 'meta_description' => 'Stainless steel flexible metal hoses designed for demanding temperature, pressure, vibration, and corrosive service.', 'canonical_url' => 'https://misubaguna.com/product/flexible-metal-hose/', 'og_title' => 'Flexible Metal Hose - PT Misuba Guna Indonesia', 'og_description' => 'Stainless steel flexible metal hoses designed for demanding temperature, pressure, vibration, and corrosive service.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'ptfe-lining', 'url_path' => '/product/ptfe-lining/', 'name' => 'PTFE Lining', 'product_group' => 'Corrosion Protection', 'product_subgroup' => 'Lining', 'headline' => 'PTFE Lining', 'summary' => 'PTFE lining for corrosive, reactive, or ultra-pure media where chemical resistance and a smooth non-stick surface are required.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 8, 'meta_title' => 'PTFE Lining - PT Misuba Guna Indonesia', 'meta_description' => 'PTFE lining for corrosive, reactive, or ultra-pure media where chemical resistance and a smooth non-stick surface are required.', 'canonical_url' => 'https://misubaguna.com/product/ptfe-lining/', 'og_title' => 'PTFE Lining - PT Misuba Guna Indonesia', 'og_description' => 'PTFE lining for corrosive, reactive, or ultra-pure media where chemical resistance and a smooth non-stick surface are required.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'rubber-lining', 'url_path' => '/product/rubber-lining/', 'name' => 'Rubber Lining', 'product_group' => 'Corrosion Protection', 'product_subgroup' => 'Lining', 'headline' => 'Rubber Lining', 'summary' => 'Protective rubber lining applied to equipment surfaces to resist corrosion, abrasion, impact, and chemical attack.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 9, 'meta_title' => 'Rubber Lining - PT Misuba Guna Indonesia', 'meta_description' => 'Protective rubber lining applied to equipment surfaces to resist corrosion, abrasion, impact, and chemical attack.', 'canonical_url' => 'https://misubaguna.com/product/rubber-lining/', 'og_title' => 'Rubber Lining - PT Misuba Guna Indonesia', 'og_description' => 'Protective rubber lining applied to equipment surfaces to resist corrosion, abrasion, impact, and chemical attack.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'ceramic-lining', 'url_path' => '/product/ceramic-lining/', 'name' => 'Ceramic Lining', 'product_group' => 'Corrosion Protection', 'product_subgroup' => 'Lining', 'headline' => 'Ceramic Lining', 'summary' => 'Ceramic lining for industrial equipment that needs high abrasion and wear protection in severe service.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 10, 'meta_title' => 'Ceramic Lining - PT Misuba Guna Indonesia', 'meta_description' => 'Ceramic lining for industrial equipment that needs high abrasion and wear protection in severe service.', 'canonical_url' => 'https://misubaguna.com/product/ceramic-lining/', 'og_title' => 'Ceramic Lining - PT Misuba Guna Indonesia', 'og_description' => 'Ceramic lining for industrial equipment that needs high abrasion and wear protection in severe service.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'frp-lining', 'url_path' => '/product/frp-lining/', 'name' => 'FRP Lining', 'product_group' => 'Corrosion Protection', 'product_subgroup' => 'Lining', 'headline' => 'FRP Lining', 'summary' => 'FRP lining for corrosion-resistant protection of tanks, vessels, ducts, and process equipment.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 11, 'meta_title' => 'FRP Lining - PT Misuba Guna Indonesia', 'meta_description' => 'FRP lining for corrosion-resistant protection of tanks, vessels, ducts, and process equipment.', 'canonical_url' => 'https://misubaguna.com/product/frp-lining/', 'og_title' => 'FRP Lining - PT Misuba Guna Indonesia', 'og_description' => 'FRP lining for corrosion-resistant protection of tanks, vessels, ducts, and process equipment.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'ceramic-coating', 'url_path' => '/product/ceramic-coating/', 'name' => 'Ceramic Coating', 'product_group' => 'Corrosion Protection', 'product_subgroup' => 'Coating', 'headline' => 'Ceramic Coating', 'summary' => 'Ceramic coating for surface protection against heat, corrosion, wear, and chemical exposure.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 12, 'meta_title' => 'Ceramic Coating - PT Misuba Guna Indonesia', 'meta_description' => 'Ceramic coating for surface protection against heat, corrosion, wear, and chemical exposure.', 'canonical_url' => 'https://misubaguna.com/product/ceramic-coating/', 'og_title' => 'Ceramic Coating - PT Misuba Guna Indonesia', 'og_description' => 'Ceramic coating for surface protection against heat, corrosion, wear, and chemical exposure.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'ptfe-coating', 'url_path' => '/product/ptfe-coating/', 'name' => 'PTFE Coating', 'product_group' => 'Corrosion Protection', 'product_subgroup' => 'Coating', 'headline' => 'PTFE Coating', 'summary' => 'PTFE coating for chemical-resistant, non-stick, low-friction surface protection in industrial applications.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 13, 'meta_title' => 'PTFE Coating - PT Misuba Guna Indonesia', 'meta_description' => 'PTFE coating for chemical-resistant, non-stick, low-friction surface protection in industrial applications.', 'canonical_url' => 'https://misubaguna.com/product/ptfe-coating/', 'og_title' => 'PTFE Coating - PT Misuba Guna Indonesia', 'og_description' => 'PTFE coating for chemical-resistant, non-stick, low-friction surface protection in industrial applications.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'gland-packing', 'url_path' => '/product/gland-packing/', 'name' => 'Gland Packing', 'product_group' => 'Sealing System', 'product_subgroup' => null, 'headline' => 'Gland Packing', 'summary' => 'Braided or woven gland packing for preventing leakage along shafts in pumps, valves, mixers, and other rotating or reciprocating equipment.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 14, 'meta_title' => 'Gland Packing - PT Misuba Guna Indonesia', 'meta_description' => 'Braided or woven gland packing for preventing leakage along shafts in pumps, valves, mixers, and other rotating or reciprocating equipment.', 'canonical_url' => 'https://misubaguna.com/product/gland-packing/', 'og_title' => 'Gland Packing - PT Misuba Guna Indonesia', 'og_description' => 'Braided or woven gland packing for preventing leakage along shafts in pumps, valves, mixers, and other rotating or reciprocating equipment.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'oil-seal', 'url_path' => '/product/oil-seal/', 'name' => 'Oil Seal', 'product_group' => 'Sealing System', 'product_subgroup' => null, 'headline' => 'Oil Seal', 'summary' => 'Rotary shaft/radial lip seals for retaining lubricants and preventing dirt, dust, and moisture from entering machinery.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 15, 'meta_title' => 'Oil Seal - PT Misuba Guna Indonesia', 'meta_description' => 'Rotary shaft/radial lip seals for retaining lubricants and preventing dirt, dust, and moisture from entering machinery.', 'canonical_url' => 'https://misubaguna.com/product/oil-seal/', 'og_title' => 'Oil Seal - PT Misuba Guna Indonesia', 'og_description' => 'Rotary shaft/radial lip seals for retaining lubricants and preventing dirt, dust, and moisture from entering machinery.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'o-ring', 'url_path' => '/product/o-ring/', 'name' => 'O-Ring', 'product_group' => 'Sealing System', 'product_subgroup' => null, 'headline' => 'O-Ring', 'summary' => 'Elastomer O-rings for sealing fluids or gases in static and dynamic applications across pumps, valves, cylinders, and industrial systems.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 16, 'meta_title' => 'O-Ring - PT Misuba Guna Indonesia', 'meta_description' => 'Elastomer O-rings for sealing fluids or gases in static and dynamic applications across pumps, valves, cylinders, and industrial systems.', 'canonical_url' => 'https://misubaguna.com/product/o-ring/', 'og_title' => 'O-Ring - PT Misuba Guna Indonesia', 'og_description' => 'Elastomer O-rings for sealing fluids or gases in static and dynamic applications across pumps, valves, cylinders, and industrial systems.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'gasket-sheet', 'url_path' => '/product/gasket-sheet/', 'name' => 'Gasket Sheet', 'product_group' => 'Sealing System', 'product_subgroup' => null, 'headline' => 'Gasket Sheet', 'summary' => 'Gasket sheet materials for cutting seals used between flanges, pipe joints, equipment covers, and machinery surfaces.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 17, 'meta_title' => 'Gasket Sheet - PT Misuba Guna Indonesia', 'meta_description' => 'Gasket sheet materials for cutting seals used between flanges, pipe joints, equipment covers, and machinery surfaces.', 'canonical_url' => 'https://misubaguna.com/product/gasket-sheet/', 'og_title' => 'Gasket Sheet - PT Misuba Guna Indonesia', 'og_description' => 'Gasket sheet materials for cutting seals used between flanges, pipe joints, equipment covers, and machinery surfaces.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'mechanical-seal', 'url_path' => '/product/mechanical-seal/', 'name' => 'Mechanical Seal', 'product_group' => 'Sealing System', 'product_subgroup' => null, 'headline' => 'Mechanical Seal', 'summary' => 'Mechanical seals for preventing leakage in rotating equipment such as pumps, mixers, and compressors.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 18, 'meta_title' => 'Mechanical Seal - PT Misuba Guna Indonesia', 'meta_description' => 'Mechanical seals for preventing leakage in rotating equipment such as pumps, mixers, and compressors.', 'canonical_url' => 'https://misubaguna.com/product/mechanical-seal/', 'og_title' => 'Mechanical Seal - PT Misuba Guna Indonesia', 'og_description' => 'Mechanical seals for preventing leakage in rotating equipment such as pumps, mixers, and compressors.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'coupling', 'url_path' => '/product/coupling/', 'name' => 'Coupling', 'product_group' => 'Power Transfer', 'product_subgroup' => null, 'headline' => 'Coupling', 'summary' => 'Mechanical couplings for connecting shafts and transmitting torque while accommodating alignment and vibration conditions.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 19, 'meta_title' => 'Coupling - PT Misuba Guna Indonesia', 'meta_description' => 'Mechanical couplings for connecting shafts and transmitting torque while accommodating alignment and vibration conditions.', 'canonical_url' => 'https://misubaguna.com/product/coupling/', 'og_title' => 'Coupling - PT Misuba Guna Indonesia', 'og_description' => 'Mechanical couplings for connecting shafts and transmitting torque while accommodating alignment and vibration conditions.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
        ];

        foreach ($products as $product) {
            DB::table('public_products')->updateOrInsert(
                ['url_path' => $product['url_path']],
                array_merge($product, ['created_at' => $now, 'updated_at' => $now])
            );
        }

        $redirects = [
            [
                'source_path' => '/indexpage/',
                'target_url' => '/',
                'status_code' => 301,
                'is_active' => false,
                'note' => 'Legacy duplicate homepage-like page. Enable after checking Google Search Console traffic/backlinks.',
            ],
        ];

        foreach ($redirects as $redirect) {
            DB::table('public_redirects')->updateOrInsert(
                ['source_path' => $redirect['source_path']],
                array_merge($redirect, ['created_at' => $now, 'updated_at' => $now])
            );
        }

        $settings = [
            ['key' => 'company_name', 'value' => 'PT Misuba Guna Indonesia', 'type' => 'string', 'description' => 'Public company name for SEO/schema.'],
            ['key' => 'company_email', 'value' => 'marketing@misubaguna.com', 'type' => 'string', 'description' => 'Public contact email.'],
            ['key' => 'company_phone', 'value' => '+62 21 55660700', 'type' => 'string', 'description' => 'Public telephone.'],
            ['key' => 'company_whatsapp', 'value' => '+62 811-8715-671', 'type' => 'string', 'description' => 'Public WhatsApp.'],
            ['key' => 'company_website', 'value' => 'https://misubaguna.com', 'type' => 'string', 'description' => 'Public website URL.'],
            ['key' => 'operational_address', 'value' => 'Ruko Mutiara Karawaci Blok C29, Bencongan Indah, Kecamatan Kelapa Dua, Tangerang, Banten 15810', 'type' => 'string', 'description' => 'Operational address from current public site.'],
            ['key' => 'warehouse_address', 'value' => 'Ruko Mutiara Karawaci Blok B36, Bencongan Indah, Kecamatan Kelapa Dua, Tangerang, Banten 15810', 'type' => 'string', 'description' => 'Warehouse address.'],
            ['key' => 'billing_address', 'value' => 'NEEDS_CONFIRMATION: public site has conflict between STC Senayan Lantai 4 No 80 and Lantai 2 No 89', 'type' => 'string', 'description' => 'Fix before rendering schema or footer.'],
        ];

        foreach ($settings as $setting) {
            DB::table('site_settings')->updateOrInsert(
                ['key' => $setting['key']],
                array_merge($setting, ['created_at' => $now, 'updated_at' => $now])
            );
        }
    }
}
