<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PublicSiteContentSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();
        $rows = [
        [
            'table' => 'public_pages',
            'slug' => 'home',
            'url_path' => '/',
            'title' => 'PT Misuba Guna Indonesia',
            'summary' => 'Partnering with industries, PT Misuba Guna Indonesia provides reliable technical solutions for mechanical engineering, electrical service, industrial supply, and custom project support.',
            'content_html' => '<h1>PT Misuba Guna Indonesia</h1><p>Partnering with industries, we deliver reliable, high-quality technical solutions to support business operations with innovation, excellence, and trust.</p><h2>Core Product Groups</h2><ul><li>Flexible Joints</li><li>Corrosion Protection</li><li>Sealing System</li><li>Power Transfer</li><li>General industrial supply and project support</li></ul>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Cleaned page content prepared for Laravel import.',
        ],
        [
            'table' => 'public_pages',
            'slug' => 'about-us',
            'url_path' => '/about-us/',
            'title' => 'About Misuba',
            'summary' => 'MGI was established in 2020 and focuses on quality engineering products and services, reasonable pricing, fast delivery, accurate response, and global manufacturer partnerships.',
            'content_html' => '<h1>About Misuba</h1><p>PT Misuba Guna Indonesia provides quality engineering products and services at competitive prices with fast delivery and trusted global partnerships. Since its establishment in 2020, the company has focused on improving product and service quality while maintaining reasonable pricing and fast, precise response to customer needs.</p><h2>Vision</h2><p>Become the first choice and most trusted company for mechanical engineering, electrical service, and supply.</p><h2>Mission</h2><ul><li>Provide high-quality products and services at reasonable prices.</li><li>Provide fast and accurate response to customer requests.</li><li>Extend and expand the business through global manufacturer partnerships.</li></ul>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Cleaned page content prepared for Laravel import.',
        ],
        [
            'table' => 'public_pages',
            'slug' => 'project-list',
            'url_path' => '/project-list/',
            'title' => 'Project List',
            'summary' => 'Project and supply examples across expansion joints, corrosion protection, material handling, sealing systems, heat transfer, pumps, valves, and industrial components.',
            'content_html' => '<h1>Project List</h1><p>MGI supports industrial customers through project-based supply, fabrication, repair, and technical sourcing across multiple product groups.</p><h2>Main Project Groups</h2><ul><li>Vibration absorber and expansion joints</li><li>Corrosion and abrasion resistance</li><li>Material handling and industrial components</li><li>Sealing systems and seals</li><li>Heat transfer equipment</li><li>Miscellaneous industrial products and technical supply</li></ul>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Cleaned page content prepared for Laravel import.',
        ],
        [
            'table' => 'public_pages',
            'slug' => 'contact-us',
            'url_path' => '/contact-us/',
            'title' => 'Contact Us',
            'summary' => 'Contact page with operational office, warehouse, billing address, telephone, WhatsApp, email, website, and inquiry form.',
            'content_html' => '<h1>Contact Us</h1><h2>Operational Office</h2><p>Ruko Mutiara Karawaci Blok C29, Bencongan Indah, Kecamatan Kelapa Dua, Tangerang, Banten 15810.</p><h2>Warehouse</h2><p>Ruko Mutiara Karawaci Blok B36, Bencongan Indah, Kecamatan Kelapa Dua, Tangerang, Banten 15810.</p><h2>Contact</h2><ul><li>Telephone: +62 21 55660700</li><li>WhatsApp: +62 811 8715 671</li><li>Email: marketing@misubaguna.com</li><li>Website: www.misubaguna.com</li></ul><p><strong>Billing address must be confirmed before launch because current site has conflicting floor/room information.</strong></p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => true,
            'notes' => 'Cleaned page content prepared for Laravel import.',
        ],
        [
            'table' => 'public_pages',
            'slug' => 'career',
            'url_path' => '/career/',
            'title' => 'Careers at Misuba',
            'summary' => 'Career page for recruitment and employment opportunities at PT Misuba Guna Indonesia.',
            'content_html' => '<h1>Careers at Misuba</h1><p>Join PT Misuba Guna Indonesia and grow with a team focused on industrial service, engineering support, marketing, supply chain, and customer satisfaction.</p><p>Open positions should be managed from the Laravel admin and expired vacancies should be hidden or marked closed.</p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => true,
            'notes' => 'Cleaned page content prepared for Laravel import.',
        ],
        [
            'table' => 'public_pages',
            'slug' => 'catalog',
            'url_path' => '/catalog/',
            'title' => 'Catalog',
            'summary' => 'Catalog page should provide company profile/catalog download and product document access.',
            'content_html' => '<h1>Catalog</h1><p>Download or view PT Misuba Guna Indonesia company profile and product catalog documents.</p><p>This page must not be left broken during the Laravel migration.</p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => true,
            'notes' => 'Cleaned page content prepared for Laravel import.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'fabric-expansion-joint',
            'url_path' => '/product/fabric-expansion-joint/',
            'title' => 'Fabric Expansion Joint',
            'summary' => 'Custom non-metallic fabric expansion joints designed by PT Misuba Guna Indonesia for high-temperature ductwork, boiler exhaust lines, and severe vibration isolation.',
            'content_html' => '<h1>Fabric Expansion Joint</h1><p class="product-description">Custom-fabricated multi-layer fabric expansion joints built by PT Misuba Guna Indonesia for absorbing severe thermal growth, duct misalignment, and low-pressure gas vibrations. Unlike metal bellows, our non-metallic fabric joints absorb simultaneous multi-directional movements (axial, lateral, angular) with minimal spring rate reaction forces on boiler casings, ID/FD fan housings, and turbine exhaust stacks.</p><p>Built with high-grade outer elastomeric covers (silicone, fluoroelastomer, or EPDM), gastight PTFE chemical barriers, and thick thermal insulation belts (needle-felted ceramic fiber and high-silica fiberglass cloth).</p><h3>Custom Engineering Consultation & Ordering Guide</h3><p>When requesting a custom fabric expansion joint quote, please provide your duct flange dimensions (round or rectangular), normal & maximum operating temperature, flue gas media composition (SOx, NOx, fly ash abrasive concentration), and expected movement range. Our technical team will recommend the optimal multi-layer fabric build for your ducting layout.</p>',
            'key_features_json' => '["Absorbs multi-directional thermal movement (axial, lateral, angular) without inducing spring rate stress on duct supports", "Custom multi-layer composite belting tailored for continuous operating temperatures from 150°C to over 1000°C", "Integrated ceramic fiber insulating belt protects gastight outer layers from direct thermal radiation", "Easily field-welded or bolted to existing companion flanges with internal metal liner sleeves to prevent ash erosion", "Zero maintenance fabric construction that eliminates fatigue cracking common in thin-gauge metal duct bellows"]',
            'applications_json' => '["Power plant boiler flue gas and turbine exhaust ducting (PLTU, PLTG, PLTU Biomass)", "Cement plant kiln preheaters, calciner ducts, and raw mill dust extraction lines", "Steel mill sintering lines and blast furnace flue gas ductwork", "Petrochemical incinerators and flare stack gas lines", "Industrial boiler ID fan and FD fan inlet/outlet isolation joints"]',
            'materials_json' => '["Outer Cover: Silicone-coated glass cloth, Fluoroelastomer canvas, EPDM", "Gas Barrier: Solid PTFE sheet foil, PTFE-impregnated fiberglass", "Thermal Insulation: Needle-felted ceramic fiber blanket, high-silica glass mat", "Reinforcement & Liner: SS304/SS316 wire mesh, internal SS304 flow sleeve, carbon steel backing bars"]',
            'technical_specs_json' => '["Duct Geometry: Custom round (DN200 to DN4000+) or rectangular (any aspect ratio)", "Operating Pressure: Low pressure ducting (-0.5 bar to +0.8 bar)", "Temperature Capability: Up to 1100°C continuous service with multi-layer ceramic insulation"]',
            'needs_manual_review' => false,
            'notes' => 'Personalized engineering content for Fabric Expansion Joint.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'metal-expansion-joint',
            'url_path' => '/product/metal-expansion-joint/',
            'title' => 'Metal Expansion Joint',
            'summary' => 'High-precision stainless steel and high-alloy bellows expansion joints engineered for thermal expansion compensation in high-pressure steam, oil, and gas piping.',
            'content_html' => '<h1>Metal Expansion Joint</h1><p class="product-description">Precision-engineered stainless steel and high-alloy bellows expansion joints manufactured to absorb severe thermal expansion, pipe stress, and vibration in pressurized liquid and steam piping. PT Misuba Guna Indonesia supplies custom metal expansion joints featuring hydroformed or roll-formed multi-ply bellows (SS304, SS316L, SS321, or Inconel 625) engineered to withstand cyclic thermal fatigue and high working pressures.</p><p>Available in axial, tied-lateral, universal, hinged, and gimbal configurations to resolve complex thermal growth in restricted pipe runs.</p><h3>Custom Engineering Consultation & Ordering Guide</h3><p>To receive a precise engineering proposal for metal expansion joints, please submit your pipe nominal bore (DN/NB), design pressure (PN rating or ANSI class), design temperature, fluid media, and target cycle life. If your piping layout includes anchors and guides, share the isometric drawing for optimal bellows selection.</p>',
            'key_features_json' => '["Multi-ply bellows design provides high pressure capacity combined with low axial spring rate and maximum flex fatigue life", "SS321 and SS316L standard bellows offer exceptional resistance to high-temperature scaling and stress corrosion cracking", "Internal flow sleeves minimize pressure drop and prevent flow-induced vibration in high-velocity steam lines", "External protective covers prevent external mechanical damage and debris accumulation in bellows convolutions", "Available with fixed/floating flanges, butt-weld ends, or threaded pipe stubs matching international standards (DIN, ANSI, JIS)"]',
            'applications_json' => '["High-pressure steam distribution headers and condensate return lines", "Thermal oil heating systems in palm oil refineries (PKS) and oleochemical plants", "Petrochemical refinery process piping and heat exchanger nozzle connections", "District heating pipelines and power plant steam turbine cross-over piping", "Marine engine exhaust manifolds and ballast water piping"]',
            'materials_json' => '["Bellows: SS304, SS316L, SS321, SS310S, Inconel 625, Hastelloy C-276", "End Fittings: Carbon steel (A105, A234 WPB), SS304, SS316, or alloy steel", "Internal Sleeve / External Shroud: SS304, SS316L, Heavy carbon steel"]',
            'technical_specs_json' => '["Nominal Sizes: DN15 (1/2\\\") to DN3000 (120\\\")", "Pressure Ratings: PN6, PN10, PN16, PN25, PN40, Class 150#, Class 300#, up to 60 bar custom rating", "Operating Temperature: -200°C (cryogenic) to +850°C"]',
            'needs_manual_review' => false,
            'notes' => 'Personalized engineering content for Metal Expansion Joint.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'rubber-expansion-joint',
            'url_path' => '/product/rubber-expansion-joint/',
            'title' => 'Rubber Expansion Joint',
            'summary' => 'Heavy-duty elastomeric rubber expansion joints designed to isolate pump vibration, absorb pipe movement, and compensate for misalignment in industrial water and fluid piping.',
            'content_html' => '<h1>Rubber Expansion Joint</h1><p class="product-description">Heavy-duty elastomeric rubber expansion joints designed to isolate pump vibration, absorb pipe movement, and compensate for axial, lateral, and angular misalignment in liquid piping systems. PT Misuba Guna Indonesia supplies single-arch, double-arch, and wide-arch rubber flexible joints molded with synthetic rubber tubes (EPDM, NBR/Nitrile, Neoprene, Natural Rubber, or Viton/FKM) and high-tensile fabric/wire reinforcement.</p><p>Featuring full-face integral rubber flanges with floating metal retaining rings, our rubber expansion joints eliminate metal-to-fluid contact and provide superior noise and shock suppression.</p><h3>Custom Engineering Consultation & Ordering Guide</h3><p>For immediate assistance with pump suction/discharge rubber joints, specify your line size (e.g. DN80 3-inch or DN200 8-inch), working fluid (e.g. seawater, cooling water, palm oil slurry, dilute acid), working pressure, and flange drilling (JIS 10K, ANSI 150#, DIN PN16). We stock standard sizes for quick dispatch across Indonesia.</p>',
            'key_features_json' => '["Outstanding vibration and sound attenuation for cooling water pumps, chillers, and compressors", "High-tensile nylon cord and steel wire reinforcement prevents ballooning under surge pressure and vacuum conditions", "Full-face rubber flange design creates a self-sealing joint, eliminating separate gasket requirements during installation", "Elastomer tube options tailored for specific chemical resistance, oil compatibility, or potable water certification", "Available with control rods (limit bolts) to prevent pipe over-extension and protect unanchored pump nozzles"]',
            'applications_json' => '["Main cooling water pumps and condenser lines in power plants and manufacturing facilities", "Water and wastewater treatment plant piping (WTP & WWTP)", "Palm oil mill effluent (POME) lines and raw water intake systems", "Marine engine room sea chest cooling lines and bilge pumps", "Industrial HVAC chilled water and condenser water circuits"]',
            'materials_json' => '["Inner Tube / Outer Cover: EPDM (water/steam), NBR (oil/fuel), Neoprene, Viton/FKM, Natural Rubber", "Reinforcement: Nylon fabric cord, synthetic polyester yarn, spiral steel wire reinforcement rings", "Retaining Flanges: Galvanized carbon steel, SS304, SS316"]',
            'technical_specs_json' => '["Nominal Sizes: DN25 (1\\\") to DN1200 (48\\\")", "Working Pressure: 10 bar (150 psi), 16 bar (230 psi), custom up to 25 bar; full vacuum options available", "Operating Temperature: -10°C to +115°C (EPDM/NBR), up to +180°C (Viton)"]',
            'needs_manual_review' => false,
            'notes' => 'Personalized engineering content for Rubber Expansion Joint.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'ptfe-expansion-joint',
            'url_path' => '/product/ptfe-expansion-joint/',
            'title' => 'PTFE Expansion Joint',
            'summary' => 'Molded virgin PTFE expansion joints engineered for ultra-pure liquids, highly aggressive acids, solvents, and reactive chemical piping lines.',
            'content_html' => '<h1>PTFE Expansion Joint</h1><p class="product-description">Molded virgin PTFE expansion joints designed specifically for ultra-pure liquids, highly aggressive acids, solvents, and reactive chemical piping lines. PT Misuba Guna Indonesia delivers precision-molded multi-convolution PTFE expansion joints that offer complete chemical inertness across virtually all industrial media.</p><p>Engineered with a low spring rate to protect fragile plastic, FRP, glass-lined, or graphite piping systems from thermal movement and pump vibration, our PTFE joints feature external stainless steel limit bolts and corrosion-resistant steel backing flanges.</p><h3>Custom Engineering Consultation & Ordering Guide</h3><p>When inquiring about PTFE expansion joints for corrosive media, let us know your chemical fluid concentration, operating temperature, vacuum requirements, and mating flange standards. Our engineering specialists will verify convolution wall thickness and reinforcement rings for your operating conditions.</p>',
            'key_features_json' => '["100% virgin PTFE construction provides total corrosion resistance against concentrated acids (HCl, H2SO4, HNO3), alkalis, and solvents", "Non-contaminating, smooth non-stick inner surface prevents product build-up and complies with high-purity chemical standards", "Low flexural modulus minimizes stress on delicate FRP, PVC, CPVC, and glass-lined vessel nozzles", "Fitted with stainless steel tie-rods and limit washers to regulate axial compression, extension, and angular movement limits", "Standard metallic root rings placed between convolutions prevent vacuum collapse and over-expansion under pressure"]',
            'applications_json' => '["Chemical synthesis plants, acid pickling lines, and chlorine/caustic electrolysis facilities", "Semiconductor and electronic chemical delivery systems", "Fertilizer and phosphoric acid production lines", "Pharmaceutical API manufacturing and ultra-pure water distribution", "Pulp bleaching operations using chlorine dioxide"]',
            'materials_json' => '["Bellows Body: 100% Virgin PTFE (molded or machined convolutions), optional antistatic conductive PTFE", "External Root Rings: SS304 or SS316 stainless steel wire rings", "Backing Flanges: Ductile iron, Carbon steel with epoxy coating, SS304, or SS316", "Tie-Rods: SS304/SS316 control tie-rods with rubber isolation bushings"]',
            'technical_specs_json' => '["Sizes: DN20 (3/4\\\") to DN600 (24\\\") in 2-convolution, 3-convolution, and 5-convolution styles", "Working Pressure: Full vacuum up to 10 bar (depending on temperature and convolution count)", "Temperature Range: -50°C to +230°C continuous service"]',
            'needs_manual_review' => false,
            'notes' => 'Personalized engineering content for PTFE Expansion Joint.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'ptfe-lined-rubber-metal-expansion-joint',
            'url_path' => '/product/ptfe-lined-rubber-metal-expansion-joint/',
            'title' => 'PTFE Lined Expansion Joint (Rubber and Metal)',
            'summary' => 'Hybrid expansion joints combining outer metal or rubber pressure strength with an internal continuous PTFE liner for severe chemical and high-pressure service.',
            'content_html' => '<h1>PTFE Lined Expansion Joint (Rubber and Metal)</h1><p class="product-description">Hybrid expansion joints combining the heavy mechanical pressure rating and movement absorption of an outer rubber or metal bellows with an internal continuous PTFE liner. Designed by PT Misuba Guna Indonesia for severe duty applications where aggressive chemical corrosion occurs simultaneously with high mechanical pressure, surge, or severe vibration.</p><p>The inner PTFE liner creates a seamless barrier protecting the outer elastomeric or stainless steel body from chemical attack, extending service life in demanding industrial process loops.</p><h3>Custom Engineering Consultation & Ordering Guide</h3><p>Need a heavy-duty PTFE lined joint for a high-pressure acid pump or slurry line? Contact PT Misuba Guna Indonesia with your media temperature, line pressure, and line size. We custom configure rubber-bodied or metal-bellows-bodied PTFE lined expansion joints tailored to your piping geometry.</p>',
            'key_features_json' => '["Dual protection: Impermeable PTFE inner liner handles severe chemicals while outer elastomer/metal body bears high pressure and vibration", "Seamless flare-over PTFE sealing faces fit directly against companion pipe flanges without needing separate gaskets", "Eliminates chemical degradation of rubber compounds in hot hydrocarbon, solvent, or mixed acid applications", "Absorbs high lateral displacement and vibration in dynamic chemical transfer lines", "Vacuum-resistant liner configurations equipped with internal metallic or PTFE support rings"]',
            'applications_json' => '["Petrochemical refinery acid gas scrubber lines and hydro-cracking chemical feeds", "Steel plant pickling bath recirculation pumps and waste acid lines", "Mining slurry treatment facilities with high chemical and abrasive content", "Chemical tanker ship unloading manifolds and offshore chemical dosing lines"]',
            'materials_json' => '["Liner: Virgin PTFE sheet flare-formed into flange faces", "Outer Body: EPDM / NBR rubber matrix with steel wire reinforcement, OR SS304/SS316 hydroformed bellows", "Flanges: Carbon steel, Ductile Iron, SS304, or SS316"]',
            'technical_specs_json' => '["Sizes: DN25 (1\\\") to DN800 (32\\\")", "Pressure Rating: Up to 16 bar for rubber-bodied, up to 25 bar for metal-bodied", "Temperature Range: -30°C to +180°C"]',
            'needs_manual_review' => false,
            'notes' => 'Personalized engineering content for PTFE Lined Expansion Joint.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'rubber-hose',
            'url_path' => '/product/rubber-hose/',
            'title' => 'Rubber Hose',
            'summary' => 'Industrial-grade reinforced rubber hoses for safe, reliable transfer of water, oil, fuel, steam, food materials, and chemicals across manufacturing and mining sites.',
            'content_html' => '<h1>Rubber Hose</h1><p class="product-description">Industrial-grade reinforced rubber hoses engineered for safe, reliable fluid and material transfer across manufacturing, agricultural, mining, and oil & gas operations. PT Misuba Guna Indonesia supplies high-performance rubber hoses built with specialized tube compounds (EPDM, NBR, SBR, Neoprene, Food-Grade White Rubber) reinforced with high-density textile plies or helical steel wire for suction and discharge service.</p><p>Supplied as bulk hose rolls or fully tested custom assemblies fitted with crimped or clamped couplings (Camlock, Flanged, NPT/BSP thread, Bauer).</p><h3>Custom Engineering Consultation & Ordering Guide</h3><p>Tell us your hose application details—internal diameter (ID), working pressure, suction or discharge requirement, media (air, water, oil, cement powder, steam), and preferred end fittings (e.g. Camlock Type C/E, ANSI Flanges). PT Misuba Guna Indonesia provides quick custom assembly, pressure testing, and delivery.</p>',
            'key_features_json' => '["Specialized tube compounds engineered for specific resistance to oils, petroleum fuels, hot water, steam, chemicals, or abrasive slurries", "Heavy-duty outer cover resists weather, UV, ozone, abrasion, and dragging across rough industrial concrete floors", "Steel wire helix reinforced options support full vacuum suction service without collapsing or kinking", "Factory-crimped safety couplings ensure leak-free operation under high working pressures and pressure spikes", "Wide range of flex tolerance for tight bend radius requirements in mobile equipment and factory drop lines"]',
            'applications_json' => '["Plant air lines, water washdown, and pneumatic tool supply", "Diesel fuel, lubricant, and hydraulic oil transfer in palm oil mills and mining fleets", "Cement powder, dry fly ash, and sand suction/discharge lines", "Food & beverage liquid transfer (milk, palm olein, syrup, potable water)", "Chemical transfer hoses for chemical dosing stations and tank truck unloading"]',
            'materials_json' => '["Inner Tube: NBR (Oil/Fuel), EPDM (Steam/Hot Water), SBR (Abrasives/Water), White FDA EPDM (Food), Hypalon", "Reinforcement: High-tensile synthetic cord, steel wire helix", "Cover: Weather & abrasion resistant EPDM, NBR/PVC blend, Neoprene", "Fittings: Stainless steel SS316, SS304, Aluminum, Brass, Carbon Steel"]',
            'technical_specs_json' => '["Hose ID: 1/4\\\" (6mm) to 12\\\" (300mm)", "Working Pressure: 10 bar (150 psi), 20 bar (300 psi), up to 40 bar heavy discharge", "Temperature Range: -40°C to +150°C (up to +210°C for saturated steam hoses)"]',
            'needs_manual_review' => false,
            'notes' => 'Personalized engineering content for Rubber Hose.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'flexible-metal-hose',
            'url_path' => '/product/flexible-metal-hose/',
            'title' => 'Flexible Metal Hose',
            'summary' => 'Precision corrugated stainless steel flexible hose assemblies designed for severe thermal cycles, extreme high pressures, cryogenic media, and gas-tight fluid transfer.',
            'content_html' => '<h1>Flexible Metal Hose</h1><p class="product-description">Precision corrugated stainless steel flexible hose assemblies designed for severe thermal cycles, extreme high pressures, cryogenic media, and gas-tight fluid transfer. PT Misuba Guna Indonesia custom fabricates flexible metal hoses using annular corrugated thin-wall stainless steel tubing (SS304, SS316L, or SS321) encased in single or double high-density stainless steel wire braiding (SS304 or SS316).</p><p>Every hose assembly is TIG welded with custom end fittings, offering 100% leak-proof flexibility where rubber or synthetic hoses fail due to high temperature, chemical attack, or flame exposure.</p><h3>Custom Engineering Consultation & Ordering Guide</h3><p>Looking for custom flexible metal hose assemblies with quick turnaround? Provide your hose size (DN), overall length (OAL), working pressure, operating temperature, and end fitting configuration (e.g. Swivel Flange, Union, Male NPT, Tri-clamp). Our welding shop builds and hydrostatic tests every assembly prior to shipment.</p>',
            'key_features_json' => '["100% gas-tight annular corrugated stainless steel tube eliminates permeation of hazardous gases and liquids", "High-density SS wire braiding absorbs internal hoop stress, allowing working pressures up to 300+ bar", "Unmatched temperature resilience from cryogenic liquid nitrogen (-200°C) to high-temperature engine exhaust (+600°C)", "Fire-safe construction prevents sudden rupture during plant emergency fire conditions", "Custom welded end fittings (ANSI/JIS flanges, unions, thread nipples, quick couplers) tested per ISO 10380 standards"]',
            'applications_json' => '["Steam header connections to moving press platens in plywood and palm oil plants", "Gas turbine fuel supply lines, burner hoses, and generator vibration isolation", "Chemical reactor feed lines, acid loading arms, and LPG/LNG transfer hoses", "High-pressure hydraulic and compressor discharge lines", "Thermal expansion loops for solar thermal and power plant piping"]',
            'materials_json' => '["Corrugated Hose Tube: SS304, SS316L, SS321", "Braid Mesh: SS304 or SS316 stainless steel wire braid (Single or Double layer)", "End Fittings: Carbon Steel, SS304, SS316L (Flanged, Union, BSP/NPT Threaded, Weld Ends, Camlock)"]',
            'technical_specs_json' => '["Nominal Sizes: DN6 (1/4\\\") to DN250 (10\\\")", "Working Pressure: Vacuum up to 350 bar (depending on hose size and braid density)", "Operating Temperature: -200°C to +600°C"]',
            'needs_manual_review' => false,
            'notes' => 'Personalized engineering content for Flexible Metal Hose.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'ptfe-lining',
            'url_path' => '/product/ptfe-lining/',
            'title' => 'PTFE Lining',
            'summary' => 'Our advanced PTFE lining services provide exceptional protection against aggressive chemicals and extreme temperatures. This seamless, non-stick barrier significantly extends the service life of pipes and process equipment.',
            'content_html' => '<h1>PTFE Lining</h1><p class="product-description">Our advanced PTFE lining services provide exceptional protection against aggressive chemicals and extreme temperatures. This seamless, non-stick barrier significantly extends the service life of pipes and process equipment.</p><p class="product-placeholder">[Placeholder: Insert detailed operational context, manufacturing standards, and specific dimensions or variants available for this product line. This text area is reserved for comprehensive product documentation.]</p><h2>Key Features and Benefits</h2><ul><li>Resists acids, bases, solvents, and aggressive mixtures</li><li>Non-stick surface reduces buildup and simplifies cleaning</li><li>Continuous temperature capability up to 260°C depending on design</li><li>Food and pharmaceutical grade options</li><li>Long service life in critical systems</li></ul><h2>Applications</h2><ul><li>Corrosive piping</li><li>Chemical process equipment</li><li>High purity transfer lines</li><li>Lined hose and joint assemblies</li><li>Equipment protection against aggressive media</li></ul><h2>Construction and Material</h2><ul><li>Virgin PTFE smooth or convoluted liner</li><li>Stainless steel or carbon steel shell</li><li>Flange, threaded, tri-clamp, or custom ends</li></ul><h2>Technical Notes</h2><ul><li>DN15 to DN300 size range</li><li>Working temperature -70°C to +260°C</li><li>Pressure rating up to 20 bar depending on design</li></ul>',
            'key_features_json' => '["Resists acids, bases, solvents, and aggressive mixtures", "Non-stick surface reduces buildup and simplifies cleaning", "Continuous temperature capability up to 260°C depending on design", "Food and pharmaceutical grade options", "Long service life in critical systems"]',
            'applications_json' => '["Corrosive piping", "Chemical process equipment", "High purity transfer lines", "Lined hose and joint assemblies", "Equipment protection against aggressive media"]',
            'materials_json' => '["Virgin PTFE smooth or convoluted liner", "Stainless steel or carbon steel shell", "Flange, threaded, tri-clamp, or custom ends"]',
            'technical_specs_json' => '["DN15 to DN300 size range", "Working temperature -70°C to +260°C", "Pressure rating up to 20 bar depending on design"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'rubber-lining',
            'url_path' => '/product/rubber-lining/',
            'title' => 'Rubber Lining',
            'summary' => 'Providing a resilient shield against abrasion, impact, and chemical attack, our rubber lining solutions safeguard heavy industrial equipment. This protective layer is essential for maintaining asset integrity in harsh environments.',
            'content_html' => '<h1>Rubber Lining</h1><p class="product-description">Providing a resilient shield against abrasion, impact, and chemical attack, our rubber lining solutions safeguard heavy industrial equipment. This protective layer is essential for maintaining asset integrity in harsh environments.</p><p class="product-placeholder">[Placeholder: Insert detailed operational context, manufacturing standards, and specific dimensions or variants available for this product line. This text area is reserved for comprehensive product documentation.]</p><h2>Key Features and Benefits</h2><ul><li>High flexibility</li><li>Impact resistance</li><li>Corrosion protection</li><li>Abrasion resistance</li><li>Noise and vibration reduction</li><li>Cost-effective equipment protection</li></ul><h2>Applications</h2><ul><li>Chemical processing tanks and pipes</li><li>Mining slurry pipes and hoppers</li><li>Water treatment equipment</li><li>Oil and gas vessels and pipelines</li><li>Power plant acidic or alkaline service equipment</li></ul><h2>Construction and Material</h2><ul><li>Natural rubber</li><li>Neoprene</li><li>EPDM</li><li>Butyl</li><li>Nitrile</li></ul><h2>Technical Notes</h2><ul><li>Typical thickness 3–25 mm depending on application</li><li>Cold bonding or hot vulcanizing</li><li>Grit blasting surface preparation required</li></ul>',
            'key_features_json' => '["High flexibility", "Impact resistance", "Corrosion protection", "Abrasion resistance", "Noise and vibration reduction", "Cost-effective equipment protection"]',
            'applications_json' => '["Chemical processing tanks and pipes", "Mining slurry pipes and hoppers", "Water treatment equipment", "Oil and gas vessels and pipelines", "Power plant acidic or alkaline service equipment"]',
            'materials_json' => '["Natural rubber", "Neoprene", "EPDM", "Butyl", "Nitrile"]',
            'technical_specs_json' => '["Typical thickness 3–25 mm depending on application", "Cold bonding or hot vulcanizing", "Grit blasting surface preparation required"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'ceramic-lining',
            'url_path' => '/product/ceramic-lining/',
            'title' => 'Ceramic Lining',
            'summary' => 'Engineered for extreme wear resistance, our ceramic lining systems protect critical components from severe abrasion and erosion. They are a proven solution for extending equipment life in heavy material handling applications.',
            'content_html' => '<h1>Ceramic Lining</h1><p class="product-description">Engineered for extreme wear resistance, our ceramic lining systems protect critical components from severe abrasion and erosion. They are a proven solution for extending equipment life in heavy material handling applications.</p><p class="product-placeholder">[Placeholder: Insert detailed operational context, manufacturing standards, and specific dimensions or variants available for this product line. This text area is reserved for comprehensive product documentation.]</p><h2>Key Features and Benefits</h2><ul><li>High wear resistance</li><li>Suitable for abrasive material handling</li><li>Protects equipment surfaces from erosion</li><li>Can extend equipment service life</li><li>Useful for severe slurry or particulate service</li></ul><h2>Applications</h2><ul><li>Chutes</li><li>Hoppers</li><li>Cyclones</li><li>Pipes and elbows</li><li>Mining and cement handling equipment</li><li>Power plant ash or coal handling</li></ul><h2>Construction and Material</h2><ul><li>Alumina ceramic tiles or liners</li><li>Rubber-backed ceramic options</li><li>Adhesive or mechanically fixed lining options</li></ul><h2>Technical Notes</h2><ul><li>Needs manual confirmation from original page before final import</li></ul>',
            'key_features_json' => '["High wear resistance", "Suitable for abrasive material handling", "Protects equipment surfaces from erosion", "Can extend equipment service life", "Useful for severe slurry or particulate service"]',
            'applications_json' => '["Chutes", "Hoppers", "Cyclones", "Pipes and elbows", "Mining and cement handling equipment", "Power plant ash or coal handling"]',
            'materials_json' => '["Alumina ceramic tiles or liners", "Rubber-backed ceramic options", "Adhesive or mechanically fixed lining options"]',
            'technical_specs_json' => '["Needs manual confirmation from original page before final import"]',
            'needs_manual_review' => true,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'frp-lining',
            'url_path' => '/product/frp-lining/',
            'title' => 'FRP Lining',
            'summary' => 'Our fiberglass reinforced plastic (FRP) lining offers a lightweight yet highly durable barrier against corrosion. It is an effective, long-term protective solution for tanks, vessels, and complex process structures.',
            'content_html' => '<h1>FRP Lining</h1><p class="product-description">Our fiberglass reinforced plastic (FRP) lining offers a lightweight yet highly durable barrier against corrosion. It is an effective, long-term protective solution for tanks, vessels, and complex process structures.</p><p class="product-placeholder">[Placeholder: Insert detailed operational context, manufacturing standards, and specific dimensions or variants available for this product line. This text area is reserved for comprehensive product documentation.]</p><h2>Key Features and Benefits</h2><ul><li>Corrosion resistant composite layer</li><li>Lightweight protection</li><li>Suitable for chemical exposure depending on resin system</li><li>Can be applied to complex surfaces</li><li>Useful for repair and lifetime extension</li></ul><h2>Applications</h2><ul><li>Chemical tanks</li><li>Wastewater treatment equipment</li><li>Ducting and scrubbers</li><li>Piping and vessels</li><li>Corrosive process areas</li></ul><h2>Construction and Material</h2><ul><li>Fiberglass reinforcement</li><li>Resin system selected by chemical exposure</li><li>Surface preparation and laminate build-up</li></ul><h2>Technical Notes</h2><ul><li>Needs manual confirmation from original page before final import</li></ul>',
            'key_features_json' => '["Corrosion resistant composite layer", "Lightweight protection", "Suitable for chemical exposure depending on resin system", "Can be applied to complex surfaces", "Useful for repair and lifetime extension"]',
            'applications_json' => '["Chemical tanks", "Wastewater treatment equipment", "Ducting and scrubbers", "Piping and vessels", "Corrosive process areas"]',
            'materials_json' => '["Fiberglass reinforcement", "Resin system selected by chemical exposure", "Surface preparation and laminate build-up"]',
            'technical_specs_json' => '["Needs manual confirmation from original page before final import"]',
            'needs_manual_review' => true,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'ceramic-coating',
            'url_path' => '/product/ceramic-coating/',
            'title' => 'Ceramic Coating',
            'summary' => 'Our high-performance ceramic coatings deliver a durable surface treatment that resists heat, wear, and chemical degradation. They are formulated to enhance the reliability of components operating in severe industrial conditions.',
            'content_html' => '<h1>Ceramic Coating</h1><p class="product-description">Our high-performance ceramic coatings deliver a durable surface treatment that resists heat, wear, and chemical degradation. They are formulated to enhance the reliability of components operating in severe industrial conditions.</p><p class="product-placeholder">[Placeholder: Insert detailed operational context, manufacturing standards, and specific dimensions or variants available for this product line. This text area is reserved for comprehensive product documentation.]</p><h2>Key Features and Benefits</h2><ul><li>Wear resistance</li><li>Heat resistance</li><li>Corrosion protection</li><li>Surface durability improvement</li><li>Suitable for harsh industrial operating environments</li></ul><h2>Applications</h2><ul><li>Power generation</li><li>Petrochemical equipment</li><li>Marine and offshore components</li><li>Piping and valves</li><li>Heat exchangers and boilers</li><li>Automotive or aerospace components</li></ul><h2>Construction and Material</h2><ul><li>Ceramic-based coating system</li><li>Surface preparation required before coating</li></ul><h2>Technical Notes</h2><ul><li>Needs manual confirmation from original page before final import</li></ul>',
            'key_features_json' => '["Wear resistance", "Heat resistance", "Corrosion protection", "Surface durability improvement", "Suitable for harsh industrial operating environments"]',
            'applications_json' => '["Power generation", "Petrochemical equipment", "Marine and offshore components", "Piping and valves", "Heat exchangers and boilers", "Automotive or aerospace components"]',
            'materials_json' => '["Ceramic-based coating system", "Surface preparation required before coating"]',
            'technical_specs_json' => '["Needs manual confirmation from original page before final import"]',
            'needs_manual_review' => true,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'ptfe-coating',
            'url_path' => '/product/ptfe-coating/',
            'title' => 'PTFE Coating',
            'summary' => 'Offering superior non-stick and low-friction characteristics, our PTFE coatings are applied to optimize surface performance. They provide excellent chemical resistance and simplify maintenance across various industrial parts.',
            'content_html' => '<h1>PTFE Coating</h1><p class="product-description">Offering superior non-stick and low-friction characteristics, our PTFE coatings are applied to optimize surface performance. They provide excellent chemical resistance and simplify maintenance across various industrial parts.</p><p class="product-placeholder">[Placeholder: Insert detailed operational context, manufacturing standards, and specific dimensions or variants available for this product line. This text area is reserved for comprehensive product documentation.]</p><h2>Key Features and Benefits</h2><ul><li>Chemical resistance</li><li>Non-stick surface</li><li>Low friction</li><li>Electrical insulation properties</li><li>Useful for clean and corrosive service</li></ul><h2>Applications</h2><ul><li>Chemical process components</li><li>Food processing equipment</li><li>Pharmaceutical equipment</li><li>Electrical insulation parts</li><li>Corrosion-prone bolts, tools, or components</li></ul><h2>Construction and Material</h2><ul><li>PTFE coating system</li><li>Prepared metal substrate</li></ul><h2>Technical Notes</h2><ul><li>Needs manual confirmation from original page before final import</li></ul>',
            'key_features_json' => '["Chemical resistance", "Non-stick surface", "Low friction", "Electrical insulation properties", "Useful for clean and corrosive service"]',
            'applications_json' => '["Chemical process components", "Food processing equipment", "Pharmaceutical equipment", "Electrical insulation parts", "Corrosion-prone bolts, tools, or components"]',
            'materials_json' => '["PTFE coating system", "Prepared metal substrate"]',
            'technical_specs_json' => '["Needs manual confirmation from original page before final import"]',
            'needs_manual_review' => true,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'gland-packing',
            'url_path' => '/product/gland-packing/',
            'title' => 'Gland Packing',
            'summary' => 'Our premium gland packing solutions provide dependable, low-friction sealing for rotating and reciprocating shafts. Available in diverse materials, they are engineered to minimize leakage and reduce equipment wear.',
            'content_html' => '<h1>Gland Packing</h1><p class="product-description">Our premium gland packing solutions provide dependable, low-friction sealing for rotating and reciprocating shafts. Available in diverse materials, they are engineered to minimize leakage and reduce equipment wear.</p><p class="product-placeholder">[Placeholder: Insert detailed operational context, manufacturing standards, and specific dimensions or variants available for this product line. This text area is reserved for comprehensive product documentation.]</p><h2>Key Features and Benefits</h2><ul><li>Effective sealing under various pressure and temperature conditions</li><li>Graphite, PTFE, aramid, carbon fiber, and other material options</li><li>Chemical and temperature resistance options</li><li>Durable construction</li><li>Easy maintenance and repacking</li></ul><h2>Applications</h2><ul><li>Centrifugal, reciprocating, and screw pumps</li><li>Industrial valves</li><li>Mixers and agitators</li><li>Marine and offshore equipment</li><li>Petrochemical processing</li><li>Power generation</li><li>Pulp and paper</li><li>Mining and mineral processing</li></ul><h2>Construction and Material</h2><ul><li>Graphite</li><li>PTFE</li><li>Aramid</li><li>Carbon fiber</li><li>Lubricants and special coatings</li></ul><h2>Technical Notes</h2><ul><li>Material selection depends on media, shaft speed, temperature, pressure, and equipment type</li></ul>',
            'key_features_json' => '["Effective sealing under various pressure and temperature conditions", "Graphite, PTFE, aramid, carbon fiber, and other material options", "Chemical and temperature resistance options", "Durable construction", "Easy maintenance and repacking"]',
            'applications_json' => '["Centrifugal, reciprocating, and screw pumps", "Industrial valves", "Mixers and agitators", "Marine and offshore equipment", "Petrochemical processing", "Power generation", "Pulp and paper", "Mining and mineral processing"]',
            'materials_json' => '["Graphite", "PTFE", "Aramid", "Carbon fiber", "Lubricants and special coatings"]',
            'technical_specs_json' => '["Material selection depends on media, shaft speed, temperature, pressure, and equipment type"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'oil-seal',
            'url_path' => '/product/oil-seal/',
            'title' => 'Oil Seal',
            'summary' => 'Designed to retain critical lubricants while excluding environmental contaminants, our radial oil seals ensure the smooth operation of rotating machinery. They are manufactured to strict tolerances for reliable, long-term performance.',
            'content_html' => '<h1>Oil Seal</h1><p class="product-description">Designed to retain critical lubricants while excluding environmental contaminants, our radial oil seals ensure the smooth operation of rotating machinery. They are manufactured to strict tolerances for reliable, long-term performance.</p><p class="product-placeholder">[Placeholder: Insert detailed operational context, manufacturing standards, and specific dimensions or variants available for this product line. This text area is reserved for comprehensive product documentation.]</p><h2>Key Features and Benefits</h2><ul><li>Prevents lubricant leakage</li><li>Blocks contaminant entry</li><li>Extends equipment life</li><li>Available in many sizes, designs, and materials</li><li>High-temperature and chemical-resistant material options</li></ul><h2>Applications</h2><ul><li>Automotive engines, transmissions, and axles</li><li>Industrial pumps and compressors</li><li>Gearboxes and drive motors</li><li>Agricultural and construction machinery</li><li>Marine propulsion systems</li><li>Wind turbines and heavy-duty equipment</li></ul><h2>Construction and Material</h2><ul><li>Metal case</li><li>Elastomer sealing lip</li><li>Garter spring</li><li>NBR</li><li>FKM/Viton</li><li>Silicone rubber</li><li>PTFE</li></ul><h2>Technical Notes</h2><ul><li>Material and profile depend on speed, temperature, media, shaft condition, and operating environment</li></ul>',
            'key_features_json' => '["Prevents lubricant leakage", "Blocks contaminant entry", "Extends equipment life", "Available in many sizes, designs, and materials", "High-temperature and chemical-resistant material options"]',
            'applications_json' => '["Automotive engines, transmissions, and axles", "Industrial pumps and compressors", "Gearboxes and drive motors", "Agricultural and construction machinery", "Marine propulsion systems", "Wind turbines and heavy-duty equipment"]',
            'materials_json' => '["Metal case", "Elastomer sealing lip", "Garter spring", "NBR", "FKM/Viton", "Silicone rubber", "PTFE"]',
            'technical_specs_json' => '["Material and profile depend on speed, temperature, media, shaft condition, and operating environment"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'o-ring',
            'url_path' => '/product/o-ring/',
            'title' => 'O-Ring',
            'summary' => 'Our comprehensive range of elastomer O-rings provides versatile, high-integrity sealing for both static and dynamic applications. They are available in precise formulations to meet specific pressure and media requirements.',
            'content_html' => '<h1>O-Ring</h1><p class="product-description">Our comprehensive range of elastomer O-rings provides versatile, high-integrity sealing for both static and dynamic applications. They are available in precise formulations to meet specific pressure and media requirements.</p><p class="product-placeholder">[Placeholder: Insert detailed operational context, manufacturing standards, and specific dimensions or variants available for this product line. This text area is reserved for comprehensive product documentation.]</p><h2>Key Features and Benefits</h2><ul><li>Simple and reliable sealing element</li><li>Wide material compatibility</li><li>Suitable for static and dynamic sealing</li><li>Easy installation and replacement</li><li>Available in many sizes and hardness options</li></ul><h2>Applications</h2><ul><li>Pumps</li><li>Valves</li><li>Hydraulic cylinders</li><li>Pneumatic equipment</li><li>Flanges and couplings</li><li>General industrial sealing</li></ul><h2>Construction and Material</h2><ul><li>NBR</li><li>FKM/Viton</li><li>EPDM</li><li>Silicone</li><li>Other elastomers by application</li></ul><h2>Technical Notes</h2><ul><li>Needs final size/material standards added from catalogue or supplier data</li></ul>',
            'key_features_json' => '["Simple and reliable sealing element", "Wide material compatibility", "Suitable for static and dynamic sealing", "Easy installation and replacement", "Available in many sizes and hardness options"]',
            'applications_json' => '["Pumps", "Valves", "Hydraulic cylinders", "Pneumatic equipment", "Flanges and couplings", "General industrial sealing"]',
            'materials_json' => '["NBR", "FKM/Viton", "EPDM", "Silicone", "Other elastomers by application"]',
            'technical_specs_json' => '["Needs final size/material standards added from catalogue or supplier data"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'gasket-sheet',
            'url_path' => '/product/gasket-sheet/',
            'title' => 'Gasket Sheet',
            'summary' => 'Supplying versatile sealing for flanged connections, our gasket sheet materials are formulated to handle a wide spectrum of pressures, temperatures, and industrial media. They ensure a secure, leak-free joint in critical assemblies.',
            'content_html' => '<h1>Gasket Sheet</h1><p class="product-description">Supplying versatile sealing for flanged connections, our gasket sheet materials are formulated to handle a wide spectrum of pressures, temperatures, and industrial media. They ensure a secure, leak-free joint in critical assemblies.</p><p class="product-placeholder">[Placeholder: Insert detailed operational context, manufacturing standards, and specific dimensions or variants available for this product line. This text area is reserved for comprehensive product documentation.]</p><h2>Key Features and Benefits</h2><ul><li>Flexible sealing material for custom gasket shapes</li><li>Helps prevent leakage between mating surfaces</li><li>Material options for temperature, pressure, and media compatibility</li><li>Can be cut to drawing or sample</li><li>Useful for maintenance and repair stock</li></ul><h2>Applications</h2><ul><li>Pipe flanges</li><li>Pump and valve covers</li><li>Heat exchanger joints</li><li>Equipment manholes and covers</li><li>General industrial sealing</li></ul><h2>Construction and Material</h2><ul><li>Compressed fiber</li><li>Rubber sheet</li><li>PTFE sheet</li><li>Graphite sheet</li><li>Non-asbestos sheet depending on service</li></ul><h2>Technical Notes</h2><ul><li>Current page may have repeated heading/content; verify before final import</li></ul>',
            'key_features_json' => '["Flexible sealing material for custom gasket shapes", "Helps prevent leakage between mating surfaces", "Material options for temperature, pressure, and media compatibility", "Can be cut to drawing or sample", "Useful for maintenance and repair stock"]',
            'applications_json' => '["Pipe flanges", "Pump and valve covers", "Heat exchanger joints", "Equipment manholes and covers", "General industrial sealing"]',
            'materials_json' => '["Compressed fiber", "Rubber sheet", "PTFE sheet", "Graphite sheet", "Non-asbestos sheet depending on service"]',
            'technical_specs_json' => '["Current page may have repeated heading/content; verify before final import"]',
            'needs_manual_review' => true,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'mechanical-seal',
            'url_path' => '/product/mechanical-seal/',
            'title' => 'Mechanical Seal',
            'summary' => 'Engineered to provide advanced fluid containment, our mechanical seals minimize leakage and friction in rotating equipment. They are a highly efficient, low-maintenance upgrade for critical pumps and mixers.',
            'content_html' => '<h1>Mechanical Seal</h1><p class="product-description">Engineered to provide advanced fluid containment, our mechanical seals minimize leakage and friction in rotating equipment. They are a highly efficient, low-maintenance upgrade for critical pumps and mixers.</p><p class="product-placeholder">[Placeholder: Insert detailed operational context, manufacturing standards, and specific dimensions or variants available for this product line. This text area is reserved for comprehensive product documentation.]</p><h2>Key Features and Benefits</h2><ul><li>Reliable fluid/gas leakage prevention</li><li>Reduces wear compared with traditional packing</li><li>Improves operating efficiency</li><li>Low maintenance when correctly selected</li><li>Suitable for broad industrial media</li></ul><h2>Applications</h2><ul><li>Pumps</li><li>Mixers</li><li>Compressors</li><li>Chemical process equipment</li><li>Water treatment equipment</li><li>Power and general industry rotating equipment</li></ul><h2>Construction and Material</h2><ul><li>Seal faces selected by media and duty</li><li>Elastomers selected by chemical/temperature service</li><li>Metal parts selected by corrosion requirement</li></ul><h2>Technical Notes</h2><ul><li>Selection depends on shaft size, pressure, temperature, speed, and media</li></ul>',
            'key_features_json' => '["Reliable fluid/gas leakage prevention", "Reduces wear compared with traditional packing", "Improves operating efficiency", "Low maintenance when correctly selected", "Suitable for broad industrial media"]',
            'applications_json' => '["Pumps", "Mixers", "Compressors", "Chemical process equipment", "Water treatment equipment", "Power and general industry rotating equipment"]',
            'materials_json' => '["Seal faces selected by media and duty", "Elastomers selected by chemical/temperature service", "Metal parts selected by corrosion requirement"]',
            'technical_specs_json' => '["Selection depends on shaft size, pressure, temperature, speed, and media"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'coupling',
            'url_path' => '/product/coupling/',
            'title' => 'Coupling',
            'summary' => 'Our industrial couplings deliver smooth, reliable torque transmission while accommodating necessary shaft misalignment. They are essential components for protecting drivetrains and reducing mechanical shock.',
            'content_html' => '<h1>Coupling</h1><p class="product-description">Our industrial couplings deliver smooth, reliable torque transmission while accommodating necessary shaft misalignment. They are essential components for protecting drivetrains and reducing mechanical shock.</p><p class="product-placeholder">[Placeholder: Insert detailed operational context, manufacturing standards, and specific dimensions or variants available for this product line. This text area is reserved for comprehensive product documentation.]</p><h2>Key Features and Benefits</h2><ul><li>Smooth torque transfer</li><li>Compensates misalignment depending on type</li><li>Reduces shock load transmission</li><li>Multiple type options for different equipment duty</li><li>Supports maintenance and reliability of rotating machinery</li></ul><h2>Applications</h2><ul><li>Pumps</li><li>Motors</li><li>Gearboxes</li><li>Compressors</li><li>Conveyors</li><li>General rotating equipment</li></ul><h2>Construction and Material</h2><ul><li>Rigid coupling options</li><li>Flexible coupling options</li><li>Gear coupling options</li><li>Grid coupling options</li><li>Fluid coupling options</li></ul><h2>Technical Notes</h2><ul><li>Selection depends on torque, speed, shaft size, alignment, and operating environment</li></ul>',
            'key_features_json' => '["Smooth torque transfer", "Compensates misalignment depending on type", "Reduces shock load transmission", "Multiple type options for different equipment duty", "Supports maintenance and reliability of rotating machinery"]',
            'applications_json' => '["Pumps", "Motors", "Gearboxes", "Compressors", "Conveyors", "General rotating equipment"]',
            'materials_json' => '["Rigid coupling options", "Flexible coupling options", "Gear coupling options", "Grid coupling options", "Fluid coupling options"]',
            'technical_specs_json' => '["Selection depends on torque, speed, shaft size, alignment, and operating environment"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_product_categories',
            'slug' => 'corrosion-protection',
            'url_path' => '/product-category/corrosion-protection/',
            'title' => 'Corrosion Protection',
            'summary' => 'High-quality industrial product designed for reliability and efficiency in demanding operational environments.',
            'content_html' => '<h1>Corrosion Protection</h1><p>High-quality industrial product designed for reliability and efficiency in demanding operational environments.</p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Category intro text prepared to reduce thin archive risk.',
        ],
        [
            'table' => 'public_product_categories',
            'slug' => 'coating',
            'url_path' => '/product-category/coating/',
            'title' => 'Coating',
            'summary' => 'High-quality industrial product designed for reliability and efficiency in demanding operational environments.',
            'content_html' => '<h1>Coating</h1><p>High-quality industrial product designed for reliability and efficiency in demanding operational environments.</p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Category intro text prepared to reduce thin archive risk.',
        ],
        [
            'table' => 'public_product_categories',
            'slug' => 'rubber-hose',
            'url_path' => '/product-category/rubber-hose/',
            'title' => 'Rubber Hose',
            'summary' => 'Manufactured for industrial durability, our rubber hoses facilitate the safe and efficient transfer of various media including water, air, and chemicals. Each hose is engineered with specialized tube compounds and robust reinforcement.',
            'content_html' => '<h1>Rubber Hose</h1><p>Manufactured for industrial durability, our rubber hoses facilitate the safe and efficient transfer of various media including water, air, and chemicals. Each hose is engineered with specialized tube compounds and robust reinforcement.</p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Category intro text prepared to reduce thin archive risk.',
        ],
        [
            'table' => 'public_product_categories',
            'slug' => 'ptfe-expansion-joint',
            'url_path' => '/product-category/ptfe-expansion-joint/',
            'title' => 'PTFE Expansion Joint',
            'summary' => 'Designed for highly corrosive and ultra-pure applications, our PTFE expansion joints deliver unmatched chemical resistance. Their low-friction, non-stick properties ensure long-lasting integrity in critical process lines.',
            'content_html' => '<h1>PTFE Expansion Joint</h1><p>Designed for highly corrosive and ultra-pure applications, our PTFE expansion joints deliver unmatched chemical resistance. Their low-friction, non-stick properties ensure long-lasting integrity in critical process lines.</p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Category intro text prepared to reduce thin archive risk.',
        ],
        [
            'table' => 'public_product_categories',
            'slug' => 'sealing-system',
            'url_path' => '/product-category/sealing-system/',
            'title' => 'Sealing System',
            'summary' => 'High-quality industrial product designed for reliability and efficiency in demanding operational environments.',
            'content_html' => '<h1>Sealing System</h1><p>High-quality industrial product designed for reliability and efficiency in demanding operational environments.</p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Category intro text prepared to reduce thin archive risk.',
        ],
        [
            'table' => 'public_product_categories',
            'slug' => 'gasket-sheet',
            'url_path' => '/product-category/gasket-sheet/',
            'title' => 'Gasket Sheet',
            'summary' => 'Supplying versatile sealing for flanged connections, our gasket sheet materials are formulated to handle a wide spectrum of pressures, temperatures, and industrial media. They ensure a secure, leak-free joint in critical assemblies.',
            'content_html' => '<h1>Gasket Sheet</h1><p>Supplying versatile sealing for flanged connections, our gasket sheet materials are formulated to handle a wide spectrum of pressures, temperatures, and industrial media. They ensure a secure, leak-free joint in critical assemblies.</p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Category intro text prepared to reduce thin archive risk.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'cooling-tower',
            'url_path' => '/product/cooling-tower/',
            'title' => 'Cooling Tower',
            'summary' => 'High-efficiency cooling towers designed for industrial heat rejection and HVAC thermal management.',
            'content_html' => '<h1>Cooling Tower</h1><p class="product-description">High-efficiency cooling towers designed for industrial heat rejection and HVAC thermal management. Engineered to provide optimum heat transfer, water saving, and long-term durability in challenging operating environments.</p><h2>Key Features and Benefits</h2><ul><li>High thermal performance fill material</li><li>Corrosion-resistant casing options (FRP / Stainless Steel / Galvanized Steel)</li><li>Low noise axial fan assemblies</li><li>Water-saving drift eliminator design</li><li>Modular installation and low maintenance</li></ul><h2>Applications</h2><ul><li>Power generation plants</li><li>Petrochemical and chemical refineries</li><li>HVAC and commercial refrigeration</li><li>Plastic molding and steel manufacturing</li><li>Food processing facilities</li></ul><h2>Technical Specifications</h2><ul><li>Counterflow and crossflow design options</li><li>Open circuit and closed circuit systems</li><li>Custom flow capacity from 10 m³/h to 1000+ m³/h</li></ul>',
            'key_features_json' => '["High thermal performance fill material", "Corrosion-resistant casing options (FRP / Stainless Steel / Galvanized Steel)", "Low noise axial fan assemblies", "Water-saving drift eliminator design", "Modular installation and low maintenance"]',
            'applications_json' => '["Power generation plants", "Petrochemical and chemical refineries", "HVAC and commercial refrigeration", "Plastic molding and steel manufacturing", "Food processing facilities"]',
            'materials_json' => '["FRP (Fiber Reinforced Plastic)", "SS304 / SS316", "Galvanized Steel", "PVC Fill Packs"]',
            'technical_specs_json' => '["Counterflow and crossflow design options", "Open circuit and closed circuit systems", "Custom flow capacity from 10 m³/h to 1000+ m³/h"]',
            'needs_manual_review' => false,
            'notes' => 'Thermal Systems product content added.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'heat-exchanger',
            'url_path' => '/product/heat-exchanger/',
            'title' => 'Heat Exchanger',
            'summary' => 'Custom shell and tube heat exchangers designed for high temperature, pressure, and fluid process energy recovery.',
            'content_html' => '<h1>Heat Exchanger</h1><p class="product-description">Custom shell and tube heat exchangers designed for high temperature, pressure, and fluid process energy recovery. Engineered according to ASME and TEMA standards to maximize heat transfer efficiency and equipment uptime.</p><h2>Key Features and Benefits</h2><ul><li>Robust shell and tube construction</li><li>Optimized baffle spacing for fluid velocity and turbulence</li><li>High pressure and temperature resistance</li><li>Easy tube bundle inspection and cleaning</li><li>Custom materials for corrosive or erosive process fluids</li></ul><h2>Applications</h2><ul><li>Oil refineries and chemical processing</li><li>Steam generation and boiler feed systems</li><li>Power plants and marine propulsion</li><li>Hydraulic oil cooling and turbine systems</li></ul><h2>Technical Specifications</h2><ul><li>Fixed tubesheet, floating head, or U-tube bundle configurations</li><li>Working pressure up to 100+ bar</li><li>Design temperature up to 500°C</li></ul>',
            'key_features_json' => '["Robust shell and tube construction", "Optimized baffle spacing for fluid velocity and turbulence", "High pressure and temperature resistance", "Easy tube bundle inspection and cleaning", "Custom materials for corrosive or erosive process fluids"]',
            'applications_json' => '["Oil refineries and chemical processing", "Steam generation and boiler feed systems", "Power plants and marine propulsion", "Hydraulic oil cooling and turbine systems"]',
            'materials_json' => '["Carbon Steel", "SS304 / SS316 / SS316L", "Titanium", "Copper Alloy / Brass"]',
            'technical_specs_json' => '["Fixed tubesheet, floating head, or U-tube bundle configurations", "Working pressure up to 100+ bar", "Design temperature up to 500°C"]',
            'needs_manual_review' => false,
            'notes' => 'Thermal Systems product content added.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'plate-heat-exchanger',
            'url_path' => '/product/plate-heat-exchanger/',
            'title' => 'Plate Heat Exchanger',
            'summary' => 'Compact gasketed and brazed plate heat exchangers delivering rapid thermal response and high efficiency.',
            'content_html' => '<h1>Plate Heat Exchanger</h1><p class="product-description">Compact gasketed and brazed plate heat exchangers delivering rapid thermal response and high efficiency. Provides superior heat transfer coefficient in a footprint significantly smaller than shell and tube exchangers.</p><h2>Key Features and Benefits</h2><ul><li>High thermal efficiency with minimal temperature approach</li><li>Compact footprint saving installation space</li><li>Expandable frame design (add/remove plates as capacity changes)</li><li>Corrosion-resistant titanium and stainless plates</li><li>Quick disassembly for servicing and plate cleaning</li></ul><h2>Applications</h2><ul><li>HVAC water chillers and district heating</li><li>Food, dairy, and beverage pasteurization</li><li>Pharmaceutical pure water heat exchange</li><li>Marine engine jacket water cooling</li></ul><h2>Technical Specifications</h2><ul><li>Gasketed, brazed, or semi-welded plate types</li><li>Plate thickness 0.5 mm to 0.8 mm</li><li>EPDM, NBR, and Viton gasket materials</li></ul>',
            'key_features_json' => '["High thermal efficiency with minimal temperature approach", "Compact footprint saving installation space", "Expandable frame design (add/remove plates as capacity changes)", "Corrosion-resistant titanium and stainless plates", "Quick disassembly for servicing and plate cleaning"]',
            'applications_json' => '["HVAC water chillers and district heating", "Food, dairy, and beverage pasteurization", "Pharmaceutical pure water heat exchange", "Marine engine jacket water cooling"]',
            'materials_json' => '["SS304", "SS316L", "Titanium", "Hastelloy", "EPDM / NBR / Viton Gaskets"]',
            'technical_specs_json' => '["Gasketed, brazed, or semi-welded plate types", "Plate thickness 0.5 mm to 0.8 mm", "EPDM, NBR, and Viton gasket materials"]',
            'needs_manual_review' => false,
            'notes' => 'Thermal Systems product content added.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'oil-cooler',
            'url_path' => '/product/oil-cooler/',
            'title' => 'Oil Cooler',
            'summary' => 'High-performance air and water-cooled oil exchangers for hydraulic systems, gearboxes, and heavy machinery.',
            'content_html' => '<h1>Oil Cooler</h1><p class="product-description">High-performance air and water-cooled oil exchangers for hydraulic systems, gearboxes, and heavy machinery. Maintains optimum oil viscosity and prevents thermal breakdown in continuous industrial operations.</p><h2>Key Features and Benefits</h2><ul><li>Prevents fluid degradation and seals damage from overheating</li><li>Air-cooled (aluminum fin bar) and water-cooled options</li><li>Integrated bypass valve options for cold startup protection</li><li>Compact, vibration-resistant construction</li><li>Suitable for mineral oils, synthetic fluids, and water-glycol mixtures</li></ul><h2>Applications</h2><ul><li>Hydraulic power units and presses</li><li>Industrial gearboxes and drive systems</li><li>Injection molding machinery</li><li>Construction equipment and marine thrusters</li></ul><h2>Technical Specifications</h2><ul><li>Air-cooled fan drive options (12V/24V DC, 230V/400V AC, hydraulic motor)</li><li>Max operating pressure up to 26 bar</li><li>Flow rates from 10 L/min to 800+ L/min</li></ul>',
            'key_features_json' => '["Prevents fluid degradation and seals damage from overheating", "Air-cooled (aluminum fin bar) and water-cooled options", "Integrated bypass valve options for cold startup protection", "Compact, vibration-resistant construction", "Suitable for mineral oils, synthetic fluids, and water-glycol mixtures"]',
            'applications_json' => '["Hydraulic power units and presses", "Industrial gearboxes and drive systems", "Injection molding machinery", "Construction equipment and marine thrusters"]',
            'materials_json' => '["Aluminum Fin & Bar Matrix", "Copper-Nickel Tubes", "Carbon Steel Casing"]',
            'technical_specs_json' => '["Air-cooled fan drive options (12V/24V DC, 230V/400V AC, hydraulic motor)", "Max operating pressure up to 26 bar", "Flow rates from 10 L/min to 800+ L/min"]',
            'needs_manual_review' => false,
            'notes' => 'Thermal Systems product content added.',
        ]
    ];

        foreach ($rows as $row) {
            $table = $row['table'];
            unset($row['table']);

            $summaryColumn = $table === 'public_pages' ? 'excerpt' : 'summary';
            $contentColumn = $table === 'public_product_categories' ? 'description_html' : 'content_html';

            $payload = [
                $summaryColumn => $row['summary'] ?? null,
                $contentColumn => $row['content_html'] ?? null,
                'updated_at' => $now,
            ];

            if ($table === 'public_products') {
                $payload['key_features'] = $row['key_features_json'] ? json_decode($row['key_features_json'], true) : null;
                $payload['applications'] = $row['applications_json'] ? json_decode($row['applications_json'], true) : null;
                $payload['materials'] = $row['materials_json'] ? json_decode($row['materials_json'], true) : null;
                $payload['technical_specs'] = $row['technical_specs_json'] ? json_decode($row['technical_specs_json'], true) : null;
            }

            DB::table($table)->where('url_path', $row['url_path'])->update($payload);
        }
    }
}
