<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PublicSiteContentSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();
        $rows = [
        [
            'table' => 'public_pages',
            'slug' => 'home',
            'url_path' => '/',
            'title' => 'PT Misuba Guna Indonesia',
            'summary' => 'Partnering with industries, PT Misuba Guna Indonesia provides reliable technical solutions for mechanical engineering, electrical service, industrial supply, and custom project support.',
            'content_html' => '<h1>PT Misuba Guna Indonesia</h1><p>Partnering with industries, we deliver reliable, high-quality technical solutions to support business operations with innovation, excellence, and trust.</p><h2>Core Product Groups</h2><ul><li>Flexible Joints</li><li>Corrosion Protection</li><li>Sealing System</li><li>Power Transfer</li><li>General industrial supply and project support</li></ul>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Cleaned page content prepared for Laravel import.',
        ],
        [
            'table' => 'public_pages',
            'slug' => 'about-us',
            'url_path' => '/about-us/',
            'title' => 'About Misuba',
            'summary' => 'MGI was established in 2020 and focuses on quality engineering products and services, reasonable pricing, fast delivery, accurate response, and global manufacturer partnerships.',
            'content_html' => '<h1>About Misuba</h1><p>PT Misuba Guna Indonesia provides quality engineering products and services at competitive prices with fast delivery and trusted global partnerships. Since its establishment in 2020, the company has focused on improving product and service quality while maintaining reasonable pricing and fast, precise response to customer needs.</p><h2>Vision</h2><p>Become the first choice and most trusted company for mechanical engineering, electrical service, and supply.</p><h2>Mission</h2><ul><li>Provide high-quality products and services at reasonable prices.</li><li>Provide fast and accurate response to customer requests.</li><li>Extend and expand the business through global manufacturer partnerships.</li></ul>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Cleaned page content prepared for Laravel import.',
        ],
        [
            'table' => 'public_pages',
            'slug' => 'project-list',
            'url_path' => '/project-list/',
            'title' => 'Project List',
            'summary' => 'Project and supply examples across expansion joints, corrosion protection, material handling, sealing systems, heat transfer, pumps, valves, and industrial components.',
            'content_html' => '<h1>Project List</h1><p>MGI supports industrial customers through project-based supply, fabrication, repair, and technical sourcing across multiple product groups.</p><h2>Main Project Groups</h2><ul><li>Vibration absorber and expansion joints</li><li>Corrosion and abrasion resistance</li><li>Material handling and industrial components</li><li>Sealing systems and seals</li><li>Heat transfer equipment</li><li>Miscellaneous industrial products and technical supply</li></ul>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Cleaned page content prepared for Laravel import.',
        ],
        [
            'table' => 'public_pages',
            'slug' => 'contact-us',
            'url_path' => '/contact-us/',
            'title' => 'Contact Us',
            'summary' => 'Contact page with operational office, warehouse, billing address, telephone, WhatsApp, email, website, and inquiry form.',
            'content_html' => '<h1>Contact Us</h1><h2>Operational Office</h2><p>Ruko Mutiara Karawaci Blok C29, Bencongan Indah, Kecamatan Kelapa Dua, Tangerang, Banten 15810.</p><h2>Warehouse</h2><p>Ruko Mutiara Karawaci Blok B36, Bencongan Indah, Kecamatan Kelapa Dua, Tangerang, Banten 15810.</p><h2>Contact</h2><ul><li>Telephone: +62 21 55660700</li><li>WhatsApp: +62 811 8715 671</li><li>Email: marketing@misubaguna.com</li><li>Website: www.misubaguna.com</li></ul><p><strong>Billing address must be confirmed before launch because current site has conflicting floor/room information.</strong></p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => true,
            'notes' => 'Cleaned page content prepared for Laravel import.',
        ],
        [
            'table' => 'public_pages',
            'slug' => 'career',
            'url_path' => '/career/',
            'title' => 'Careers at Misuba',
            'summary' => 'Career page for recruitment and employment opportunities at PT Misuba Guna Indonesia.',
            'content_html' => '<h1>Careers at Misuba</h1><p>Join PT Misuba Guna Indonesia and grow with a team focused on industrial service, engineering support, marketing, supply chain, and customer satisfaction.</p><p>Open positions should be managed from the Laravel admin and expired vacancies should be hidden or marked closed.</p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => true,
            'notes' => 'Cleaned page content prepared for Laravel import.',
        ],
        [
            'table' => 'public_pages',
            'slug' => 'catalog',
            'url_path' => '/catalog/',
            'title' => 'Catalog',
            'summary' => 'Catalog page should provide company profile/catalog download and product document access.',
            'content_html' => '<h1>Catalog</h1><p>Download or view PT Misuba Guna Indonesia company profile and product catalog documents.</p><p>This page must not be left broken during the Laravel migration.</p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => true,
            'notes' => 'Cleaned page content prepared for Laravel import.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'fabric-expansion-joint',
            'url_path' => '/product/fabric-expansion-joint/',
            'title' => 'Fabric Expansion Joint',
            'summary' => 'Flexible non-metallic expansion joints for ducting and piping systems that need movement absorption, vibration isolation, and high-temperature sealing.',
            'content_html' => '<h1>Fabric Expansion Joint</h1><p>Flexible non-metallic expansion joints for ducting and piping systems that need movement absorption, vibration isolation, and high-temperature sealing.</p><h2>Key Features and Benefits</h2><ul><li>Handles axial, lateral, and angular movement</li><li>High-temperature material options for demanding exhaust and process systems</li><li>Corrosion and chemical resistant fabric layer options</li><li>Customizable dimensions, movements, and layer construction</li><li>Damps vibration and helps protect connected equipment</li></ul><h2>Applications</h2><ul><li>Power generation plants</li><li>Petrochemical and chemical processing</li><li>HVAC systems</li><li>Cement and steel industries</li><li>Gas turbine exhaust systems</li><li>Pulp and paper plants</li></ul><h2>Construction and Material</h2><ul><li>Fiberglass cloth</li><li>Ceramic blanket</li><li>PTFE-coated fiberglass</li><li>Silicone-coated fiberglass</li><li>SS304 wire mesh reinforcement</li><li>PTFE sheet gas-tight layer</li></ul><h2>Technical Notes</h2><ul><li>Temperature options depend on material layer selection</li><li>Designed based on movement, temperature, pressure, and media conditions</li></ul>',
            'key_features_json' => '["Handles axial, lateral, and angular movement", "High-temperature material options for demanding exhaust and process systems", "Corrosion and chemical resistant fabric layer options", "Customizable dimensions, movements, and layer construction", "Damps vibration and helps protect connected equipment"]',
            'applications_json' => '["Power generation plants", "Petrochemical and chemical processing", "HVAC systems", "Cement and steel industries", "Gas turbine exhaust systems", "Pulp and paper plants"]',
            'materials_json' => '["Fiberglass cloth", "Ceramic blanket", "PTFE-coated fiberglass", "Silicone-coated fiberglass", "SS304 wire mesh reinforcement", "PTFE sheet gas-tight layer"]',
            'technical_specs_json' => '["Temperature options depend on material layer selection", "Designed based on movement, temperature, pressure, and media conditions"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'metal-expansion-joint',
            'url_path' => '/product/metal-expansion-joint/',
            'title' => 'Metal Expansion Joint',
            'summary' => 'Precision-engineered metal bellows expansion joints for absorbing thermal expansion, vibration, and mechanical movement in piping and duct systems.',
            'content_html' => '<h1>Metal Expansion Joint</h1><p>Precision-engineered metal bellows expansion joints for absorbing thermal expansion, vibration, and mechanical movement in piping and duct systems.</p><h2>Key Features and Benefits</h2><ul><li>Strong stainless steel construction</li><li>Handles axial, lateral, angular, universal, hinged, and gimbal movement requirements</li><li>Suitable for high-temperature service</li><li>Suitable for demanding pressure applications</li><li>Protects piping and connected equipment from stress</li></ul><h2>Applications</h2><ul><li>Power generation</li><li>Petrochemical and chemical processing</li><li>HVAC and exhaust systems</li><li>Refineries and steel plants</li><li>Marine engineering</li><li>LNG and cryogenic systems</li></ul><h2>Construction and Material</h2><ul><li>SS304</li><li>SS316</li><li>SS321</li><li>SS310</li><li>Inconel or special alloys when required</li><li>Flanged or weld end fittings</li></ul><h2>Technical Notes</h2><ul><li>Round or rectangular construction available</li><li>Protective covers optional</li></ul>',
            'key_features_json' => '["Strong stainless steel construction", "Handles axial, lateral, angular, universal, hinged, and gimbal movement requirements", "Suitable for high-temperature service", "Suitable for demanding pressure applications", "Protects piping and connected equipment from stress"]',
            'applications_json' => '["Power generation", "Petrochemical and chemical processing", "HVAC and exhaust systems", "Refineries and steel plants", "Marine engineering", "LNG and cryogenic systems"]',
            'materials_json' => '["SS304", "SS316", "SS321", "SS310", "Inconel or special alloys when required", "Flanged or weld end fittings"]',
            'technical_specs_json' => '["Round or rectangular construction available", "Protective covers optional"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'rubber-expansion-joint',
            'url_path' => '/product/rubber-expansion-joint/',
            'title' => 'Rubber Expansion Joint',
            'summary' => 'Flexible rubber connectors for piping systems that absorb movement, isolate vibration, and compensate for thermal expansion or misalignment.',
            'content_html' => '<h1>Rubber Expansion Joint</h1><p>Flexible rubber connectors for piping systems that absorb movement, isolate vibration, and compensate for thermal expansion or misalignment.</p><h2>Key Features and Benefits</h2><ul><li>Excellent flexibility for axial, lateral, and angular movement</li><li>Vibration and shock absorption</li><li>Rubber compound options for chemical, oil, fuel, and waste exposure</li><li>Weather, UV, ozone, and temperature resilience depending on compound</li><li>Low-maintenance construction with long service life</li></ul><h2>Applications</h2><ul><li>Power plants</li><li>Pulp and paper plants</li><li>Mining</li><li>LNG facilities</li><li>Palm oil refineries</li><li>Water and wastewater treatment</li><li>Petrochemical and chemical industries</li><li>Marine engineering</li></ul><h2>Construction and Material</h2><ul><li>EPDM</li><li>NBR</li><li>Neoprene</li><li>Fabric reinforcement</li><li>Rubber body with flange or clamp connections</li></ul><h2>Technical Notes</h2><ul><li>Single arch and multiple arch options</li><li>Spool type, sleeve/clamp type, and tapered options</li></ul>',
            'key_features_json' => '["Excellent flexibility for axial, lateral, and angular movement", "Vibration and shock absorption", "Rubber compound options for chemical, oil, fuel, and waste exposure", "Weather, UV, ozone, and temperature resilience depending on compound", "Low-maintenance construction with long service life"]',
            'applications_json' => '["Power plants", "Pulp and paper plants", "Mining", "LNG facilities", "Palm oil refineries", "Water and wastewater treatment", "Petrochemical and chemical industries", "Marine engineering"]',
            'materials_json' => '["EPDM", "NBR", "Neoprene", "Fabric reinforcement", "Rubber body with flange or clamp connections"]',
            'technical_specs_json' => '["Single arch and multiple arch options", "Spool type, sleeve/clamp type, and tapered options"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'ptfe-expansion-joint',
            'url_path' => '/product/ptfe-expansion-joint/',
            'title' => 'PTFE Expansion Joint',
            'summary' => 'PTFE expansion joints for clean, corrosive, high-purity, and chemically aggressive service where non-stick and chemical resistance are required.',
            'content_html' => '<h1>PTFE Expansion Joint</h1><p>PTFE expansion joints for clean, corrosive, high-purity, and chemically aggressive service where non-stick and chemical resistance are required.</p><h2>Key Features and Benefits</h2><ul><li>Excellent chemical resistance</li><li>Temperature tolerance typically from -200°C to +260°C depending on design</li><li>Flexible movement compensation</li><li>Low friction and non-stick surface</li><li>Lightweight compared with metal alternatives</li></ul><h2>Applications</h2><ul><li>Pulp and paper plants</li><li>Palm oil refineries</li><li>Power plants</li><li>Chemical processing</li><li>Pharmaceutical manufacturing</li><li>Food and beverage industry</li><li>Water treatment</li><li>Mining and mineral processing</li><li>HVAC systems</li><li>Oil and gas</li></ul><h2>Construction and Material</h2><ul><li>Virgin PTFE</li><li>Antistatic PTFE where required</li><li>Optional stainless steel reinforcement</li><li>PTFE-coated or steel backing flanges</li></ul><h2>Technical Notes</h2><ul><li>Convoluted PTFE type</li><li>Molded PTFE type</li><li>Reinforced PTFE type</li></ul>',
            'key_features_json' => '["Excellent chemical resistance", "Temperature tolerance typically from -200°C to +260°C depending on design", "Flexible movement compensation", "Low friction and non-stick surface", "Lightweight compared with metal alternatives"]',
            'applications_json' => '["Pulp and paper plants", "Palm oil refineries", "Power plants", "Chemical processing", "Pharmaceutical manufacturing", "Food and beverage industry", "Water treatment", "Mining and mineral processing", "HVAC systems", "Oil and gas"]',
            'materials_json' => '["Virgin PTFE", "Antistatic PTFE where required", "Optional stainless steel reinforcement", "PTFE-coated or steel backing flanges"]',
            'technical_specs_json' => '["Convoluted PTFE type", "Molded PTFE type", "Reinforced PTFE type"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'ptfe-lined-rubber-metal-expansion-joint',
            'url_path' => '/product/ptfe-lined-rubber-metal-expansion-joint/',
            'title' => 'PTFE Lined Expansion Joint (Rubber and Metal)',
            'summary' => 'PTFE-lined rubber or metal expansion joints that combine movement absorption with internal chemical protection for aggressive media.',
            'content_html' => '<h1>PTFE Lined Expansion Joint (Rubber and Metal)</h1><p>PTFE-lined rubber or metal expansion joints that combine movement absorption with internal chemical protection for aggressive media.</p><h2>Key Features and Benefits</h2><ul><li>PTFE lining protects against corrosive media</li><li>Outer rubber or metal body provides strength and pressure resistance</li><li>Absorbs mechanical movement and vibration</li><li>Suitable for vacuum and pressure systems depending on design</li></ul><h2>Applications</h2><ul><li>Petrochemical and refinery acid/solvent pipelines</li><li>Waste treatment dosing and neutralization lines</li><li>Steel and cement plant corrosive gas or slurry service</li><li>Marine and offshore chemical or saltwater exposure</li></ul><h2>Construction and Material</h2><ul><li>Virgin PTFE sleeve</li><li>Rubber body</li><li>Stainless steel or carbon steel outer body</li><li>Vacuum support rings</li><li>Flanged ends</li><li>Protective coating options</li></ul><h2>Technical Notes</h2><ul><li>Rubber-based PTFE-lined joint options</li><li>Metal-based axial/universal/lateral/hinged options</li></ul>',
            'key_features_json' => '["PTFE lining protects against corrosive media", "Outer rubber or metal body provides strength and pressure resistance", "Absorbs mechanical movement and vibration", "Suitable for vacuum and pressure systems depending on design"]',
            'applications_json' => '["Petrochemical and refinery acid/solvent pipelines", "Waste treatment dosing and neutralization lines", "Steel and cement plant corrosive gas or slurry service", "Marine and offshore chemical or saltwater exposure"]',
            'materials_json' => '["Virgin PTFE sleeve", "Rubber body", "Stainless steel or carbon steel outer body", "Vacuum support rings", "Flanged ends", "Protective coating options"]',
            'technical_specs_json' => '["Rubber-based PTFE-lined joint options", "Metal-based axial/universal/lateral/hinged options"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'rubber-hose',
            'url_path' => '/product/rubber-hose/',
            'title' => 'Rubber Hose',
            'summary' => 'Industrial rubber hoses for transferring air, water, oil, fuel, steam, chemicals, food-grade materials, and other process media.',
            'content_html' => '<h1>Rubber Hose</h1><p>Industrial rubber hoses for transferring air, water, oil, fuel, steam, chemicals, food-grade materials, and other process media.</p><h2>Key Features and Benefits</h2><ul><li>Flexible and pressure-capable construction</li><li>Abrasion, UV, and weather-resistant cover options</li><li>Media-specific tube options for fuel, steam, food, chemical, and general service</li><li>Textile or steel wire reinforcement options</li><li>Custom lengths and end fittings</li></ul><h2>Applications</h2><ul><li>Workshop air lines and pneumatic tools</li><li>Fuel and oil transfer</li><li>Steam lines</li><li>Chemical dosing</li><li>Food and beverage transfer</li><li>Cooling water and hydraulic return lines</li><li>Construction and heavy equipment</li></ul><h2>Construction and Material</h2><ul><li>EPDM</li><li>NBR</li><li>Natural rubber</li><li>Butyl</li><li>Neoprene</li><li>Polyester yarn reinforcement</li><li>Spiral steel wire reinforcement</li></ul><h2>Technical Notes</h2><ul><li>Typical sizes from 1/4 inch to 4 inch with custom lengths on request</li></ul>',
            'key_features_json' => '["Flexible and pressure-capable construction", "Abrasion, UV, and weather-resistant cover options", "Media-specific tube options for fuel, steam, food, chemical, and general service", "Textile or steel wire reinforcement options", "Custom lengths and end fittings"]',
            'applications_json' => '["Workshop air lines and pneumatic tools", "Fuel and oil transfer", "Steam lines", "Chemical dosing", "Food and beverage transfer", "Cooling water and hydraulic return lines", "Construction and heavy equipment"]',
            'materials_json' => '["EPDM", "NBR", "Natural rubber", "Butyl", "Neoprene", "Polyester yarn reinforcement", "Spiral steel wire reinforcement"]',
            'technical_specs_json' => '["Typical sizes from 1/4 inch to 4 inch with custom lengths on request"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'flexible-metal-hose',
            'url_path' => '/product/flexible-metal-hose/',
            'title' => 'Flexible Metal Hose',
            'summary' => 'Stainless steel flexible metal hoses designed for demanding temperature, pressure, vibration, and corrosive service.',
            'content_html' => '<h1>Flexible Metal Hose</h1><p>Stainless steel flexible metal hoses designed for demanding temperature, pressure, vibration, and corrosive service.</p><h2>Key Features and Benefits</h2><ul><li>SS304/SS316 corrosion-resistant construction</li><li>Corrugated body for bending and movement</li><li>High and low temperature capability</li><li>High-pressure braided options</li><li>Leak-resistant construction with suitable fittings</li></ul><h2>Applications</h2><ul><li>Chemical processing</li><li>Oil and gas</li><li>Food and beverage</li><li>Pharmaceutical production</li><li>Aerospace and automotive fuel, exhaust, and hydraulic systems</li></ul><h2>Construction and Material</h2><ul><li>Corrugated SS304 or SS316L hose body</li><li>SS304 or SS316 wire braid</li><li>Flange, union, BSP/NPT threaded, or custom welded fittings</li></ul><h2>Technical Notes</h2><ul><li>DN6 to DN100 size range</li><li>Working pressure up to 300 bar depending on size and braid</li><li>Temperature range -200°C to +600°C</li></ul>',
            'key_features_json' => '["SS304/SS316 corrosion-resistant construction", "Corrugated body for bending and movement", "High and low temperature capability", "High-pressure braided options", "Leak-resistant construction with suitable fittings"]',
            'applications_json' => '["Chemical processing", "Oil and gas", "Food and beverage", "Pharmaceutical production", "Aerospace and automotive fuel, exhaust, and hydraulic systems"]',
            'materials_json' => '["Corrugated SS304 or SS316L hose body", "SS304 or SS316 wire braid", "Flange, union, BSP/NPT threaded, or custom welded fittings"]',
            'technical_specs_json' => '["DN6 to DN100 size range", "Working pressure up to 300 bar depending on size and braid", "Temperature range -200°C to +600°C"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'ptfe-lining',
            'url_path' => '/product/ptfe-lining/',
            'title' => 'PTFE Lining',
            'summary' => 'PTFE lining for corrosive, reactive, or ultra-pure media where chemical resistance and a smooth non-stick surface are required.',
            'content_html' => '<h1>PTFE Lining</h1><p>PTFE lining for corrosive, reactive, or ultra-pure media where chemical resistance and a smooth non-stick surface are required.</p><h2>Key Features and Benefits</h2><ul><li>Resists acids, bases, solvents, and aggressive mixtures</li><li>Non-stick surface reduces buildup and simplifies cleaning</li><li>Continuous temperature capability up to 260°C depending on design</li><li>Food and pharmaceutical grade options</li><li>Long service life in critical systems</li></ul><h2>Applications</h2><ul><li>Corrosive piping</li><li>Chemical process equipment</li><li>High purity transfer lines</li><li>Lined hose and joint assemblies</li><li>Equipment protection against aggressive media</li></ul><h2>Construction and Material</h2><ul><li>Virgin PTFE smooth or convoluted liner</li><li>Stainless steel or carbon steel shell</li><li>Flange, threaded, tri-clamp, or custom ends</li></ul><h2>Technical Notes</h2><ul><li>DN15 to DN300 size range</li><li>Working temperature -70°C to +260°C</li><li>Pressure rating up to 20 bar depending on design</li></ul>',
            'key_features_json' => '["Resists acids, bases, solvents, and aggressive mixtures", "Non-stick surface reduces buildup and simplifies cleaning", "Continuous temperature capability up to 260°C depending on design", "Food and pharmaceutical grade options", "Long service life in critical systems"]',
            'applications_json' => '["Corrosive piping", "Chemical process equipment", "High purity transfer lines", "Lined hose and joint assemblies", "Equipment protection against aggressive media"]',
            'materials_json' => '["Virgin PTFE smooth or convoluted liner", "Stainless steel or carbon steel shell", "Flange, threaded, tri-clamp, or custom ends"]',
            'technical_specs_json' => '["DN15 to DN300 size range", "Working temperature -70°C to +260°C", "Pressure rating up to 20 bar depending on design"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'rubber-lining',
            'url_path' => '/product/rubber-lining/',
            'title' => 'Rubber Lining',
            'summary' => 'Protective rubber lining applied to equipment surfaces to resist corrosion, abrasion, impact, and chemical attack.',
            'content_html' => '<h1>Rubber Lining</h1><p>Protective rubber lining applied to equipment surfaces to resist corrosion, abrasion, impact, and chemical attack.</p><h2>Key Features and Benefits</h2><ul><li>High flexibility</li><li>Impact resistance</li><li>Corrosion protection</li><li>Abrasion resistance</li><li>Noise and vibration reduction</li><li>Cost-effective equipment protection</li></ul><h2>Applications</h2><ul><li>Chemical processing tanks and pipes</li><li>Mining slurry pipes and hoppers</li><li>Water treatment equipment</li><li>Oil and gas vessels and pipelines</li><li>Power plant acidic or alkaline service equipment</li></ul><h2>Construction and Material</h2><ul><li>Natural rubber</li><li>Neoprene</li><li>EPDM</li><li>Butyl</li><li>Nitrile</li></ul><h2>Technical Notes</h2><ul><li>Typical thickness 3–25 mm depending on application</li><li>Cold bonding or hot vulcanizing</li><li>Grit blasting surface preparation required</li></ul>',
            'key_features_json' => '["High flexibility", "Impact resistance", "Corrosion protection", "Abrasion resistance", "Noise and vibration reduction", "Cost-effective equipment protection"]',
            'applications_json' => '["Chemical processing tanks and pipes", "Mining slurry pipes and hoppers", "Water treatment equipment", "Oil and gas vessels and pipelines", "Power plant acidic or alkaline service equipment"]',
            'materials_json' => '["Natural rubber", "Neoprene", "EPDM", "Butyl", "Nitrile"]',
            'technical_specs_json' => '["Typical thickness 3–25 mm depending on application", "Cold bonding or hot vulcanizing", "Grit blasting surface preparation required"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'ceramic-lining',
            'url_path' => '/product/ceramic-lining/',
            'title' => 'Ceramic Lining',
            'summary' => 'Ceramic lining for industrial equipment that needs high abrasion and wear protection in severe service.',
            'content_html' => '<h1>Ceramic Lining</h1><p>Ceramic lining for industrial equipment that needs high abrasion and wear protection in severe service.</p><h2>Key Features and Benefits</h2><ul><li>High wear resistance</li><li>Suitable for abrasive material handling</li><li>Protects equipment surfaces from erosion</li><li>Can extend equipment service life</li><li>Useful for severe slurry or particulate service</li></ul><h2>Applications</h2><ul><li>Chutes</li><li>Hoppers</li><li>Cyclones</li><li>Pipes and elbows</li><li>Mining and cement handling equipment</li><li>Power plant ash or coal handling</li></ul><h2>Construction and Material</h2><ul><li>Alumina ceramic tiles or liners</li><li>Rubber-backed ceramic options</li><li>Adhesive or mechanically fixed lining options</li></ul><h2>Technical Notes</h2><ul><li>Needs manual confirmation from original page before final import</li></ul>',
            'key_features_json' => '["High wear resistance", "Suitable for abrasive material handling", "Protects equipment surfaces from erosion", "Can extend equipment service life", "Useful for severe slurry or particulate service"]',
            'applications_json' => '["Chutes", "Hoppers", "Cyclones", "Pipes and elbows", "Mining and cement handling equipment", "Power plant ash or coal handling"]',
            'materials_json' => '["Alumina ceramic tiles or liners", "Rubber-backed ceramic options", "Adhesive or mechanically fixed lining options"]',
            'technical_specs_json' => '["Needs manual confirmation from original page before final import"]',
            'needs_manual_review' => true,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'frp-lining',
            'url_path' => '/product/frp-lining/',
            'title' => 'FRP Lining',
            'summary' => 'FRP lining for corrosion-resistant protection of tanks, vessels, ducts, and process equipment.',
            'content_html' => '<h1>FRP Lining</h1><p>FRP lining for corrosion-resistant protection of tanks, vessels, ducts, and process equipment.</p><h2>Key Features and Benefits</h2><ul><li>Corrosion resistant composite layer</li><li>Lightweight protection</li><li>Suitable for chemical exposure depending on resin system</li><li>Can be applied to complex surfaces</li><li>Useful for repair and lifetime extension</li></ul><h2>Applications</h2><ul><li>Chemical tanks</li><li>Wastewater treatment equipment</li><li>Ducting and scrubbers</li><li>Piping and vessels</li><li>Corrosive process areas</li></ul><h2>Construction and Material</h2><ul><li>Fiberglass reinforcement</li><li>Resin system selected by chemical exposure</li><li>Surface preparation and laminate build-up</li></ul><h2>Technical Notes</h2><ul><li>Needs manual confirmation from original page before final import</li></ul>',
            'key_features_json' => '["Corrosion resistant composite layer", "Lightweight protection", "Suitable for chemical exposure depending on resin system", "Can be applied to complex surfaces", "Useful for repair and lifetime extension"]',
            'applications_json' => '["Chemical tanks", "Wastewater treatment equipment", "Ducting and scrubbers", "Piping and vessels", "Corrosive process areas"]',
            'materials_json' => '["Fiberglass reinforcement", "Resin system selected by chemical exposure", "Surface preparation and laminate build-up"]',
            'technical_specs_json' => '["Needs manual confirmation from original page before final import"]',
            'needs_manual_review' => true,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'ceramic-coating',
            'url_path' => '/product/ceramic-coating/',
            'title' => 'Ceramic Coating',
            'summary' => 'Ceramic coating for surface protection against heat, corrosion, wear, and chemical exposure.',
            'content_html' => '<h1>Ceramic Coating</h1><p>Ceramic coating for surface protection against heat, corrosion, wear, and chemical exposure.</p><h2>Key Features and Benefits</h2><ul><li>Wear resistance</li><li>Heat resistance</li><li>Corrosion protection</li><li>Surface durability improvement</li><li>Suitable for harsh industrial operating environments</li></ul><h2>Applications</h2><ul><li>Power generation</li><li>Petrochemical equipment</li><li>Marine and offshore components</li><li>Piping and valves</li><li>Heat exchangers and boilers</li><li>Automotive or aerospace components</li></ul><h2>Construction and Material</h2><ul><li>Ceramic-based coating system</li><li>Surface preparation required before coating</li></ul><h2>Technical Notes</h2><ul><li>Needs manual confirmation from original page before final import</li></ul>',
            'key_features_json' => '["Wear resistance", "Heat resistance", "Corrosion protection", "Surface durability improvement", "Suitable for harsh industrial operating environments"]',
            'applications_json' => '["Power generation", "Petrochemical equipment", "Marine and offshore components", "Piping and valves", "Heat exchangers and boilers", "Automotive or aerospace components"]',
            'materials_json' => '["Ceramic-based coating system", "Surface preparation required before coating"]',
            'technical_specs_json' => '["Needs manual confirmation from original page before final import"]',
            'needs_manual_review' => true,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'ptfe-coating',
            'url_path' => '/product/ptfe-coating/',
            'title' => 'PTFE Coating',
            'summary' => 'PTFE coating for chemical-resistant, non-stick, low-friction surface protection in industrial applications.',
            'content_html' => '<h1>PTFE Coating</h1><p>PTFE coating for chemical-resistant, non-stick, low-friction surface protection in industrial applications.</p><h2>Key Features and Benefits</h2><ul><li>Chemical resistance</li><li>Non-stick surface</li><li>Low friction</li><li>Electrical insulation properties</li><li>Useful for clean and corrosive service</li></ul><h2>Applications</h2><ul><li>Chemical process components</li><li>Food processing equipment</li><li>Pharmaceutical equipment</li><li>Electrical insulation parts</li><li>Corrosion-prone bolts, tools, or components</li></ul><h2>Construction and Material</h2><ul><li>PTFE coating system</li><li>Prepared metal substrate</li></ul><h2>Technical Notes</h2><ul><li>Needs manual confirmation from original page before final import</li></ul>',
            'key_features_json' => '["Chemical resistance", "Non-stick surface", "Low friction", "Electrical insulation properties", "Useful for clean and corrosive service"]',
            'applications_json' => '["Chemical process components", "Food processing equipment", "Pharmaceutical equipment", "Electrical insulation parts", "Corrosion-prone bolts, tools, or components"]',
            'materials_json' => '["PTFE coating system", "Prepared metal substrate"]',
            'technical_specs_json' => '["Needs manual confirmation from original page before final import"]',
            'needs_manual_review' => true,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'gland-packing',
            'url_path' => '/product/gland-packing/',
            'title' => 'Gland Packing',
            'summary' => 'Braided or woven gland packing for preventing leakage along shafts in pumps, valves, mixers, and other rotating or reciprocating equipment.',
            'content_html' => '<h1>Gland Packing</h1><p>Braided or woven gland packing for preventing leakage along shafts in pumps, valves, mixers, and other rotating or reciprocating equipment.</p><h2>Key Features and Benefits</h2><ul><li>Effective sealing under various pressure and temperature conditions</li><li>Graphite, PTFE, aramid, carbon fiber, and other material options</li><li>Chemical and temperature resistance options</li><li>Durable construction</li><li>Easy maintenance and repacking</li></ul><h2>Applications</h2><ul><li>Centrifugal, reciprocating, and screw pumps</li><li>Industrial valves</li><li>Mixers and agitators</li><li>Marine and offshore equipment</li><li>Petrochemical processing</li><li>Power generation</li><li>Pulp and paper</li><li>Mining and mineral processing</li></ul><h2>Construction and Material</h2><ul><li>Graphite</li><li>PTFE</li><li>Aramid</li><li>Carbon fiber</li><li>Lubricants and special coatings</li></ul><h2>Technical Notes</h2><ul><li>Material selection depends on media, shaft speed, temperature, pressure, and equipment type</li></ul>',
            'key_features_json' => '["Effective sealing under various pressure and temperature conditions", "Graphite, PTFE, aramid, carbon fiber, and other material options", "Chemical and temperature resistance options", "Durable construction", "Easy maintenance and repacking"]',
            'applications_json' => '["Centrifugal, reciprocating, and screw pumps", "Industrial valves", "Mixers and agitators", "Marine and offshore equipment", "Petrochemical processing", "Power generation", "Pulp and paper", "Mining and mineral processing"]',
            'materials_json' => '["Graphite", "PTFE", "Aramid", "Carbon fiber", "Lubricants and special coatings"]',
            'technical_specs_json' => '["Material selection depends on media, shaft speed, temperature, pressure, and equipment type"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'oil-seal',
            'url_path' => '/product/oil-seal/',
            'title' => 'Oil Seal',
            'summary' => 'Rotary shaft/radial lip seals for retaining lubricants and preventing dirt, dust, and moisture from entering machinery.',
            'content_html' => '<h1>Oil Seal</h1><p>Rotary shaft/radial lip seals for retaining lubricants and preventing dirt, dust, and moisture from entering machinery.</p><h2>Key Features and Benefits</h2><ul><li>Prevents lubricant leakage</li><li>Blocks contaminant entry</li><li>Extends equipment life</li><li>Available in many sizes, designs, and materials</li><li>High-temperature and chemical-resistant material options</li></ul><h2>Applications</h2><ul><li>Automotive engines, transmissions, and axles</li><li>Industrial pumps and compressors</li><li>Gearboxes and drive motors</li><li>Agricultural and construction machinery</li><li>Marine propulsion systems</li><li>Wind turbines and heavy-duty equipment</li></ul><h2>Construction and Material</h2><ul><li>Metal case</li><li>Elastomer sealing lip</li><li>Garter spring</li><li>NBR</li><li>FKM/Viton</li><li>Silicone rubber</li><li>PTFE</li></ul><h2>Technical Notes</h2><ul><li>Material and profile depend on speed, temperature, media, shaft condition, and operating environment</li></ul>',
            'key_features_json' => '["Prevents lubricant leakage", "Blocks contaminant entry", "Extends equipment life", "Available in many sizes, designs, and materials", "High-temperature and chemical-resistant material options"]',
            'applications_json' => '["Automotive engines, transmissions, and axles", "Industrial pumps and compressors", "Gearboxes and drive motors", "Agricultural and construction machinery", "Marine propulsion systems", "Wind turbines and heavy-duty equipment"]',
            'materials_json' => '["Metal case", "Elastomer sealing lip", "Garter spring", "NBR", "FKM/Viton", "Silicone rubber", "PTFE"]',
            'technical_specs_json' => '["Material and profile depend on speed, temperature, media, shaft condition, and operating environment"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'o-ring',
            'url_path' => '/product/o-ring/',
            'title' => 'O-Ring',
            'summary' => 'Elastomer O-rings for sealing fluids or gases in static and dynamic applications across pumps, valves, cylinders, and industrial systems.',
            'content_html' => '<h1>O-Ring</h1><p>Elastomer O-rings for sealing fluids or gases in static and dynamic applications across pumps, valves, cylinders, and industrial systems.</p><h2>Key Features and Benefits</h2><ul><li>Simple and reliable sealing element</li><li>Wide material compatibility</li><li>Suitable for static and dynamic sealing</li><li>Easy installation and replacement</li><li>Available in many sizes and hardness options</li></ul><h2>Applications</h2><ul><li>Pumps</li><li>Valves</li><li>Hydraulic cylinders</li><li>Pneumatic equipment</li><li>Flanges and couplings</li><li>General industrial sealing</li></ul><h2>Construction and Material</h2><ul><li>NBR</li><li>FKM/Viton</li><li>EPDM</li><li>Silicone</li><li>Other elastomers by application</li></ul><h2>Technical Notes</h2><ul><li>Needs final size/material standards added from catalogue or supplier data</li></ul>',
            'key_features_json' => '["Simple and reliable sealing element", "Wide material compatibility", "Suitable for static and dynamic sealing", "Easy installation and replacement", "Available in many sizes and hardness options"]',
            'applications_json' => '["Pumps", "Valves", "Hydraulic cylinders", "Pneumatic equipment", "Flanges and couplings", "General industrial sealing"]',
            'materials_json' => '["NBR", "FKM/Viton", "EPDM", "Silicone", "Other elastomers by application"]',
            'technical_specs_json' => '["Needs final size/material standards added from catalogue or supplier data"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'gasket-sheet',
            'url_path' => '/product/gasket-sheet/',
            'title' => 'Gasket Sheet',
            'summary' => 'Gasket sheet materials for cutting seals used between flanges, pipe joints, equipment covers, and machinery surfaces.',
            'content_html' => '<h1>Gasket Sheet</h1><p>Gasket sheet materials for cutting seals used between flanges, pipe joints, equipment covers, and machinery surfaces.</p><h2>Key Features and Benefits</h2><ul><li>Flexible sealing material for custom gasket shapes</li><li>Helps prevent leakage between mating surfaces</li><li>Material options for temperature, pressure, and media compatibility</li><li>Can be cut to drawing or sample</li><li>Useful for maintenance and repair stock</li></ul><h2>Applications</h2><ul><li>Pipe flanges</li><li>Pump and valve covers</li><li>Heat exchanger joints</li><li>Equipment manholes and covers</li><li>General industrial sealing</li></ul><h2>Construction and Material</h2><ul><li>Compressed fiber</li><li>Rubber sheet</li><li>PTFE sheet</li><li>Graphite sheet</li><li>Non-asbestos sheet depending on service</li></ul><h2>Technical Notes</h2><ul><li>Current page may have repeated heading/content; verify before final import</li></ul>',
            'key_features_json' => '["Flexible sealing material for custom gasket shapes", "Helps prevent leakage between mating surfaces", "Material options for temperature, pressure, and media compatibility", "Can be cut to drawing or sample", "Useful for maintenance and repair stock"]',
            'applications_json' => '["Pipe flanges", "Pump and valve covers", "Heat exchanger joints", "Equipment manholes and covers", "General industrial sealing"]',
            'materials_json' => '["Compressed fiber", "Rubber sheet", "PTFE sheet", "Graphite sheet", "Non-asbestos sheet depending on service"]',
            'technical_specs_json' => '["Current page may have repeated heading/content; verify before final import"]',
            'needs_manual_review' => true,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'mechanical-seal',
            'url_path' => '/product/mechanical-seal/',
            'title' => 'Mechanical Seal',
            'summary' => 'Mechanical seals for preventing leakage in rotating equipment such as pumps, mixers, and compressors.',
            'content_html' => '<h1>Mechanical Seal</h1><p>Mechanical seals for preventing leakage in rotating equipment such as pumps, mixers, and compressors.</p><h2>Key Features and Benefits</h2><ul><li>Reliable fluid/gas leakage prevention</li><li>Reduces wear compared with traditional packing</li><li>Improves operating efficiency</li><li>Low maintenance when correctly selected</li><li>Suitable for broad industrial media</li></ul><h2>Applications</h2><ul><li>Pumps</li><li>Mixers</li><li>Compressors</li><li>Chemical process equipment</li><li>Water treatment equipment</li><li>Power and general industry rotating equipment</li></ul><h2>Construction and Material</h2><ul><li>Seal faces selected by media and duty</li><li>Elastomers selected by chemical/temperature service</li><li>Metal parts selected by corrosion requirement</li></ul><h2>Technical Notes</h2><ul><li>Selection depends on shaft size, pressure, temperature, speed, and media</li></ul>',
            'key_features_json' => '["Reliable fluid/gas leakage prevention", "Reduces wear compared with traditional packing", "Improves operating efficiency", "Low maintenance when correctly selected", "Suitable for broad industrial media"]',
            'applications_json' => '["Pumps", "Mixers", "Compressors", "Chemical process equipment", "Water treatment equipment", "Power and general industry rotating equipment"]',
            'materials_json' => '["Seal faces selected by media and duty", "Elastomers selected by chemical/temperature service", "Metal parts selected by corrosion requirement"]',
            'technical_specs_json' => '["Selection depends on shaft size, pressure, temperature, speed, and media"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_products',
            'slug' => 'coupling',
            'url_path' => '/product/coupling/',
            'title' => 'Coupling',
            'summary' => 'Mechanical couplings for connecting shafts and transmitting torque while accommodating alignment and vibration conditions.',
            'content_html' => '<h1>Coupling</h1><p>Mechanical couplings for connecting shafts and transmitting torque while accommodating alignment and vibration conditions.</p><h2>Key Features and Benefits</h2><ul><li>Smooth torque transfer</li><li>Compensates misalignment depending on type</li><li>Reduces shock load transmission</li><li>Multiple type options for different equipment duty</li><li>Supports maintenance and reliability of rotating machinery</li></ul><h2>Applications</h2><ul><li>Pumps</li><li>Motors</li><li>Gearboxes</li><li>Compressors</li><li>Conveyors</li><li>General rotating equipment</li></ul><h2>Construction and Material</h2><ul><li>Rigid coupling options</li><li>Flexible coupling options</li><li>Gear coupling options</li><li>Grid coupling options</li><li>Fluid coupling options</li></ul><h2>Technical Notes</h2><ul><li>Selection depends on torque, speed, shaft size, alignment, and operating environment</li></ul>',
            'key_features_json' => '["Smooth torque transfer", "Compensates misalignment depending on type", "Reduces shock load transmission", "Multiple type options for different equipment duty", "Supports maintenance and reliability of rotating machinery"]',
            'applications_json' => '["Pumps", "Motors", "Gearboxes", "Compressors", "Conveyors", "General rotating equipment"]',
            'materials_json' => '["Rigid coupling options", "Flexible coupling options", "Gear coupling options", "Grid coupling options", "Fluid coupling options"]',
            'technical_specs_json' => '["Selection depends on torque, speed, shaft size, alignment, and operating environment"]',
            'needs_manual_review' => false,
            'notes' => 'Cleaned product content prepared for Laravel import. Review flags mean exact old page content could not be fully confirmed from crawl output.',
        ],
        [
            'table' => 'public_product_categories',
            'slug' => 'corrosion-protection',
            'url_path' => '/product-category/corrosion-protection/',
            'title' => 'Corrosion Protection',
            'summary' => 'Products and services for protecting industrial equipment against corrosion, abrasion, chemical attack, and severe operating conditions.',
            'content_html' => '<h1>Corrosion Protection</h1><p>Products and services for protecting industrial equipment against corrosion, abrasion, chemical attack, and severe operating conditions.</p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Category intro text prepared to reduce thin archive risk.',
        ],
        [
            'table' => 'public_product_categories',
            'slug' => 'coating',
            'url_path' => '/product-category/coating/',
            'title' => 'Coating',
            'summary' => 'Ceramic coating and PTFE coating options for surface protection in industrial applications.',
            'content_html' => '<h1>Coating</h1><p>Ceramic coating and PTFE coating options for surface protection in industrial applications.</p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Category intro text prepared to reduce thin archive risk.',
        ],
        [
            'table' => 'public_product_categories',
            'slug' => 'rubber-hose',
            'url_path' => '/product-category/rubber-hose/',
            'title' => 'Rubber Hose',
            'summary' => 'Industrial rubber hose products for air, water, oil, fuel, steam, chemical, food-grade, and general transfer applications.',
            'content_html' => '<h1>Rubber Hose</h1><p>Industrial rubber hose products for air, water, oil, fuel, steam, chemical, food-grade, and general transfer applications.</p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Category intro text prepared to reduce thin archive risk.',
        ],
        [
            'table' => 'public_product_categories',
            'slug' => 'ptfe-expansion-joint',
            'url_path' => '/product-category/ptfe-expansion-joint/',
            'title' => 'PTFE Expansion Joint',
            'summary' => 'PTFE expansion joint products for chemical-resistant, clean, and high-purity piping applications.',
            'content_html' => '<h1>PTFE Expansion Joint</h1><p>PTFE expansion joint products for chemical-resistant, clean, and high-purity piping applications.</p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Category intro text prepared to reduce thin archive risk.',
        ],
        [
            'table' => 'public_product_categories',
            'slug' => 'sealing-system',
            'url_path' => '/product-category/sealing-system/',
            'title' => 'Sealing System',
            'summary' => 'Industrial sealing products including gland packing, oil seals, O-rings, gasket sheets, and mechanical seals.',
            'content_html' => '<h1>Sealing System</h1><p>Industrial sealing products including gland packing, oil seals, O-rings, gasket sheets, and mechanical seals.</p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Category intro text prepared to reduce thin archive risk.',
        ],
        [
            'table' => 'public_product_categories',
            'slug' => 'gasket-sheet',
            'url_path' => '/product-category/gasket-sheet/',
            'title' => 'Gasket Sheet',
            'summary' => 'Gasket sheet materials and custom-cut gasket supply for industrial sealing applications.',
            'content_html' => '<h1>Gasket Sheet</h1><p>Gasket sheet materials and custom-cut gasket supply for industrial sealing applications.</p>',
            'key_features_json' => null,
            'applications_json' => null,
            'materials_json' => null,
            'technical_specs_json' => null,
            'needs_manual_review' => false,
            'notes' => 'Category intro text prepared to reduce thin archive risk.',
        ]
    ];

        foreach ($rows as $row) {
            $table = $row['table'];
            unset($row['table']);

            $summaryColumn = $table === 'public_pages' ? 'excerpt' : 'summary';
            $contentColumn = $table === 'public_product_categories' ? 'description_html' : 'content_html';

            $payload = [
                $summaryColumn => $row['summary'] ?? null,
                $contentColumn => $row['content_html'] ?? null,
                'updated_at' => $now,
            ];

            if ($table === 'public_products') {
                $payload['key_features'] = $row['key_features_json'] ? json_decode($row['key_features_json'], true) : null;
                $payload['applications'] = $row['applications_json'] ? json_decode($row['applications_json'], true) : null;
                $payload['materials'] = $row['materials_json'] ? json_decode($row['materials_json'], true) : null;
                $payload['technical_specs'] = $row['technical_specs_json'] ? json_decode($row['technical_specs_json'], true) : null;
            }

            DB::table($table)->where('url_path', $row['url_path'])->update($payload);
        }
    }
}
