<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PublicSiteSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $pages = [
            [
                'page_type' => 'home', 'slug' => 'home', 'url_path' => '/',
                'title' => 'PT Misuba Guna Indonesia - Build on Trust, Driving on Excellence',
                'headline' => 'PT Misuba Guna Indonesia',
                'excerpt' => 'Partner with PT Misuba Guna Indonesia for reliable, high-quality technical solutions. We drive business forward with innovation, excellence, and trust.',
                'content_html' => null, 'sections' => null,
                'meta_title' => 'PT Misuba Guna Indonesia - Build on Trust, Driving on Excellence',
                'meta_description' => 'Partner with PT Misuba Guna Indonesia for reliable, high-quality technical solutions. We drive business forward with innovation, excellence, and trust.',
                'canonical_url' => 'https://misubaguna.com/',
                'og_title' => 'PT Misuba Guna Indonesia - Build on Trust, Driving on Excellence',
                'og_description' => 'Partner with PT Misuba Guna Indonesia for reliable, high-quality technical solutions. We drive business forward with innovation, excellence, and trust.',
                'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true,
                'sitemap_include' => true, 'sitemap_priority' => '1.0', 'sitemap_changefreq' => 'weekly',
                'schema_json' => null, 'is_published' => true, 'published_at' => null, 'sort_order' => 1,
            ],
            [
                'page_type' => 'page', 'slug' => 'about-us', 'url_path' => '/about-us/',
                'title' => 'About Misuba | Quality Engineering Products & Services',
                'headline' => 'About Us / About Misuba',
                'excerpt' => 'PT Misuba Guna Indonesia Providing quality engineering products & services at competitive prices with fast delivery and trusted global partnerships since 2020.',
                'content_html' => null, 'sections' => null,
                'meta_title' => 'About Misuba | Quality Engineering Products & Services',
                'meta_description' => 'PT Misuba Guna Indonesia Providing quality engineering products & services at competitive prices with fast delivery and trusted global partnerships since 2020.',
                'canonical_url' => 'https://misubaguna.com/about-us/',
                'og_title' => 'About Misuba | Quality Engineering Products & Services',
                'og_description' => 'PT Misuba Guna Indonesia Providing quality engineering products & services at competitive prices with fast delivery and trusted global partnerships since 2020.',
                'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true,
                'sitemap_include' => true, 'sitemap_priority' => '0.8', 'sitemap_changefreq' => 'monthly',
                'schema_json' => null, 'is_published' => true, 'published_at' => null, 'sort_order' => 2,
            ],
            [
                'page_type' => 'project_list', 'slug' => 'project-list', 'url_path' => '/project-list/',
                'title' => 'Project List - PT Misuba Guna Indonesia',
                'headline' => 'Project List',
                'excerpt' => 'MGI supports industrial customers through project-based supply, fabrication, repair, and technical sourcing across multiple product groups.',
                'content_html' => null, 'sections' => null,
                'meta_title' => 'Project List - PT Misuba Guna Indonesia',
                'meta_description' => 'MGI supports industrial customers through project-based supply, fabrication, repair, and technical sourcing across multiple product groups.',
                'canonical_url' => 'https://misubaguna.com/project-list/',
                'og_title' => 'Project List - PT Misuba Guna Indonesia',
                'og_description' => 'MGI supports industrial customers through project-based supply, fabrication, repair, and technical sourcing across multiple product groups.',
                'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true,
                'sitemap_include' => true, 'sitemap_priority' => '0.8', 'sitemap_changefreq' => 'monthly',
                'schema_json' => null, 'is_published' => true, 'published_at' => null, 'sort_order' => 3,
            ],
            [
                'page_type' => 'contact', 'slug' => 'contact-us', 'url_path' => '/contact-us/',
                'title' => 'Contact Us - Get in Touch with PT Misuba Guna Indonesia',
                'headline' => 'Contact Us / Get in Touch',
                'excerpt' => 'Contact page with operational office, warehouse, billing address, telephone, WhatsApp, email, website, and inquiry form.',
                'content_html' => null, 'sections' => null,
                'meta_title' => 'Contact Us - Get in Touch with PT Misuba Guna Indonesia',
                'meta_description' => 'Contact PT Misuba Guna Indonesia for engineering products and services. Office, warehouse, telephone, WhatsApp, email, and sales inquiries.',
                'canonical_url' => 'https://misubaguna.com/contact-us/',
                'og_title' => 'Contact Us - Get in Touch with PT Misuba Guna Indonesia',
                'og_description' => 'Contact PT Misuba Guna Indonesia for engineering products and services.',
                'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true,
                'sitemap_include' => true, 'sitemap_priority' => '0.8', 'sitemap_changefreq' => 'monthly',
                'schema_json' => null, 'is_published' => true, 'published_at' => null, 'sort_order' => 4,
            ],
            [
                'page_type' => 'career', 'slug' => 'career', 'url_path' => '/career/',
                'title' => 'Careers at Misuba | Join Our Team & Grow With Us',
                'headline' => 'Careers at Misuba / Join Our Team & Grow With Us',
                'excerpt' => 'Careers at Misuba – Join our team and grow with us. Explore exciting opportunities in engineering, marketing, supply chain, and more.',
                'content_html' => null, 'sections' => null,
                'meta_title' => 'Careers at Misuba | Join Our Team & Grow With Us',
                'meta_description' => 'Careers at Misuba – Join our team and grow with us. Explore exciting opportunities in engineering, marketing, supply chain, and more.',
                'canonical_url' => 'https://misubaguna.com/career/',
                'og_title' => 'Careers at Misuba | Join Our Team & Grow With Us',
                'og_description' => 'Careers at Misuba – Join our team and grow with us. Explore exciting opportunities in engineering, marketing, supply chain, and more.',
                'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true,
                'sitemap_include' => true, 'sitemap_priority' => '0.8', 'sitemap_changefreq' => 'monthly',
                'schema_json' => null, 'is_published' => true, 'published_at' => null, 'sort_order' => 5,
            ],
            [
                'page_type' => 'catalog', 'slug' => 'catalog', 'url_path' => '/catalog/',
                'title' => 'Catalog - PT Misuba Guna Indonesia',
                'headline' => 'Catalog',
                'excerpt' => 'Download or view PT Misuba Guna Indonesia company profile and product catalog documents.',
                'content_html' => null, 'sections' => null,
                'meta_title' => 'Catalog - PT Misuba Guna Indonesia',
                'meta_description' => 'Download or view PT Misuba Guna Indonesia company profile and product catalog documents.',
                'canonical_url' => 'https://misubaguna.com/catalog/',
                'og_title' => 'Catalog - PT Misuba Guna Indonesia',
                'og_description' => 'Download or view PT Misuba Guna Indonesia company profile and product catalog documents.',
                'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true,
                'sitemap_include' => true, 'sitemap_priority' => '0.8', 'sitemap_changefreq' => 'monthly',
                'schema_json' => null, 'is_published' => true, 'published_at' => null, 'sort_order' => 6,
            ],
            [
                'page_type' => 'services', 'slug' => 'services', 'url_path' => '/services/',
                'title' => 'Industrial Engineering & Technical Services | PT Misuba Guna Indonesia',
                'headline' => 'Industrial Engineering & Technical Services',
                'excerpt' => 'PT Misuba Guna Indonesia provides expert industrial services including cooling tower repair, heat exchanger service, thermal spray coating, rubber lining, FRP repair, PTFE bonding, expansion joint installation, and mechanical maintenance.',
                'content_html' => null, 'sections' => null,
                'meta_title' => 'Industrial Engineering & Technical Services | PT Misuba Guna Indonesia',
                'meta_description' => 'Explore industrial engineering and field services by PT Misuba Guna Indonesia: cooling tower repair, heat exchanger service, thermal spray coating, rubber/FRP/PTFE lining, expansion joint replacement, and mechanical maintenance.',
                'canonical_url' => 'https://misubaguna.com/services/',
                'og_title' => 'Industrial Engineering & Technical Services | PT Misuba Guna Indonesia',
                'og_description' => 'Explore industrial engineering and field services by PT Misuba Guna Indonesia: cooling tower repair, heat exchanger service, thermal spray coating, rubber/FRP/PTFE lining, expansion joint replacement, and mechanical maintenance.',
                'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true,
                'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'weekly',
                'schema_json' => null, 'is_published' => true, 'published_at' => null, 'sort_order' => 7,
            ],
        ];

        foreach ($pages as $page) {
            DB::table('public_pages')->updateOrInsert(
                ['url_path' => $page['url_path']],
                array_merge($page, ['created_at' => $now, 'updated_at' => $now])
            );
        }

        $services = [
            [
                'slug' => 'cooling-tower-repair',
                'url_path' => '/services/cooling-tower-repair/',
                'name' => 'Cooling Tower Repair & Refurbishment',
                'service_group' => 'Thermal & Cooling Systems',
                'headline' => 'Cooling Tower Repair, Overhaul & Refurbishment Services',
                'summary' => 'Comprehensive repair, thermal overhaul, fill replacement, structural waterproofing, and fan drive maintenance for industrial cooling towers.',
                'key_features' => json_encode(['Complete thermal capability restoration', 'High-efficiency fill and drift eliminator replacement', 'FRP and concrete basin structural leak repairs', 'Fan assembly, gearbox, and drive shaft alignment']),
                'typical_problems' => json_encode(['Scale buildup and fouled fill media lowering cooling efficiency', 'Corrosion, cracking, and water leakage in basin structure', 'Vibration or mechanical failure in fan blades and gearboxes', 'Drift loss and high water consumption']),
                'scope_of_work' => json_encode(['On-site inspection and thermal capacity audit', 'Removal and eco-disposal of degraded fill packs', 'High-pressure cleaning and basin surface re-coating', 'Installation of new high-performance PVC/PP fill packs', 'Dynamic balancing and shaft alignment for fan drives']),
                'industries_served' => json_encode(['Power Generation Plants', 'Petrochemical Refineries', 'HVAC & Commercial Refrigeration', 'Manufacturing & Steel Works', 'Palm Oil Mills']),
                'materials_equipment' => json_encode(['FRP Casing & Basin Liners', 'High-Efficiency PVC Fill Packs', 'SS316 Mechanical Fasteners', 'Laser Shaft Alignment Equipment']),
                'related_products' => json_encode(['cooling-tower', 'heat-exchanger']),
                'sort_order' => 1,
                'meta_title' => 'Cooling Tower Repair & Refurbishment Services - PT Misuba Guna Indonesia',
                'meta_description' => 'Expert cooling tower repair, fill replacement, basin waterproofing, and mechanical overhaul services in Indonesia.',
                'canonical_url' => 'https://misubaguna.com/services/cooling-tower-repair/',
                'og_title' => 'Cooling Tower Repair & Refurbishment Services - PT Misuba Guna Indonesia',
                'og_description' => 'Expert cooling tower repair, fill replacement, basin waterproofing, and mechanical overhaul services in Indonesia.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.8',
                'sitemap_changefreq' => 'monthly',
                'is_published' => true,
            ],
            [
                'slug' => 'heat-exchanger-repair',
                'url_path' => '/services/heat-exchanger-repair/',
                'name' => 'Heat Exchanger Service & Repair',
                'service_group' => 'Thermal & Cooling Systems',
                'headline' => 'Heat Exchanger Overhaul, Retubing & Plate Cleaning Services',
                'summary' => 'On-site and workshop repair services for shell & tube and plate heat exchangers including retubing, hydrostatic testing, and re-gasket service.',
                'key_features' => json_encode(['Complete tube bundle pull and hydro-jetting', 'Precision retubing and tube sheet expansion', 'Plate pack disassembly, chemical cleaning, and re-gasketing', 'ASME/TEMA hydrostatic pressure testing']),
                'typical_problems' => json_encode(['Tube leakages causing cross-contamination of fluids', 'Heavy fouling, scaling, and pressure drop increase', 'Gasket deterioration leading to external leakage', 'Erosion-corrosion at tube inlet and tube sheet joints']),
                'scope_of_work' => json_encode(['Nondestructive testing (NDT) and eddy current tube inspection', 'High-pressure water jet cleaning of tubes and channels', 'Extraction of worn tubes and precision expansion of new tubes', 'Plate pack chemical bath dipping and fluorescent crack detection', 'Hydrostatic pressure test certification']),
                'industries_served' => json_encode(['Chemical Processing', 'Oil & Gas Refineries', 'Marine & Offshore Engineering', 'Food & Dairy Processing', 'Fertilizer Manufacturing']),
                'materials_equipment' => json_encode(['SS304 / SS316L / Titanium Tubes & Plates', 'EPDM / NBR / Viton Gaskets', 'Hydrostatic Test Rigs', 'Pneumatic Tube Expanders']),
                'related_products' => json_encode(['heat-exchanger', 'plate-heat-exchanger', 'oil-cooler']),
                'sort_order' => 2,
                'meta_title' => 'Heat Exchanger Service & Repair - PT Misuba Guna Indonesia',
                'meta_description' => 'Professional heat exchanger repair, retubing, plate pack cleaning, and pressure testing services for industrial plants.',
                'canonical_url' => 'https://misubaguna.com/services/heat-exchanger-repair/',
                'og_title' => 'Heat Exchanger Service & Repair - PT Misuba Guna Indonesia',
                'og_description' => 'Professional heat exchanger repair, retubing, plate pack cleaning, and pressure testing services for industrial plants.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.8',
                'sitemap_changefreq' => 'monthly',
                'is_published' => true,
            ],
            [
                'slug' => 'thermal-spray-coating',
                'url_path' => '/services/thermal-spray-coating/',
                'name' => 'Thermal Spray Coating',
                'service_group' => 'Protective Lining & Coating',
                'headline' => 'Thermal Spray & Metal Spraying Services for Wear & Corrosion Protection',
                'summary' => 'High-performance thermal spray coating and metal spraying solutions to restore worn components and protect against extreme abrasion, heat, and corrosion.',
                'key_features' => json_encode(['Restores worn shaft journals, impellers, and valve seats', 'Delivers superior wear and oxidation resistance', 'Cold process application prevents thermal distortion of parent metal', 'High bond strength with custom alloy selection']),
                'typical_problems' => json_encode(['Severe surface wear, scoring, and dimensional loss on critical shafts', 'High-temperature oxidation and hot corrosion on turbine components', 'Cavitation erosion on pump impellers and hydraulic housings']),
                'scope_of_work' => json_encode(['Pre-machining and surface grit blasting to Sa 2.5 cleanliness', 'Precision metal spray coating application using wire flame or HVOF systems', 'Post-spray sealant application for inter-particle sealing', 'Final precision grinding and finish machining to exact tolerances']),
                'industries_served' => json_encode(['Pulp & Paper Mills', 'Mining & Material Handling', 'Power Generation', 'Heavy Equipment Repair', 'Marine Thrusters & Shafts']),
                'materials_equipment' => json_encode(['Stainless Steel Wire', 'Alumina-Titania Ceramics', 'Nickel-Cr-Mo Alloys', 'Metal Spraying Systems & HVOF Equipment']),
                'related_products' => json_encode(['ceramic-coating', 'ptfe-coating']),
                'sort_order' => 3,
                'meta_title' => 'Thermal Spray Coating & Metal Spraying Services - PT Misuba Guna Indonesia',
                'meta_description' => 'High-performance thermal spray coating and metal spraying services for shaft restoration, corrosion resistance, and wear protection.',
                'canonical_url' => 'https://misubaguna.com/services/thermal-spray-coating/',
                'og_title' => 'Thermal Spray Coating & Metal Spraying Services - PT Misuba Guna Indonesia',
                'og_description' => 'High-performance thermal spray coating and metal spraying services for shaft restoration, corrosion resistance, and wear protection.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.8',
                'sitemap_changefreq' => 'monthly',
                'is_published' => true,
            ],
            [
                'slug' => 'rubber-lining',
                'url_path' => '/services/rubber-lining/',
                'name' => 'Rubber Lining',
                'service_group' => 'Protective Lining & Coating',
                'headline' => 'Industrial Rubber Lining Services for Acid Tanks & Pipe Assemblies',
                'summary' => 'Workshop and field application of rubber lining sheets for tanks, vessels, pipes, and agitators to resist chemical attack and heavy abrasion.',
                'key_features' => json_encode(['Seamless protection against acids, alkalis, and slurries', 'Cold bonding and hot vulcanization techniques', 'High impact and sound dampening properties', 'Spark testing to ensure 100% pinhole-free barrier']),
                'typical_problems' => json_encode(['Corrosive pitting and chemical erosion of steel storage tanks', 'Rapid wear of slurry transfer pipe elbows in mining operations', 'Chemical attack on water treatment neutralization vessels']),
                'scope_of_work' => json_encode(['Abrasive blast cleaning of metal substrate', 'Primer and two-part adhesive application', 'Precision hand-tailored rubber sheet lay-up and seam rolling', 'Autoclave or ambient temperature vulcanization', 'High-voltage holiday spark testing (10kV–20kV)']),
                'industries_served' => json_encode(['Mining & Mineral Processing', 'Acid Storage & Chemical Plants', 'Water & Wastewater Treatment', 'Steel Pickling Lines']),
                'materials_equipment' => json_encode(['Natural Rubber', 'Neoprene Elastomers', 'EPDM & Nitrile Vulcanizates', 'High-Voltage Spark Tester']),
                'related_products' => json_encode(['rubber-lining', 'rubber-expansion-joint', 'rubber-hose']),
                'sort_order' => 4,
                'meta_title' => 'Rubber Lining Services - PT Misuba Guna Indonesia',
                'meta_description' => 'Custom industrial rubber lining services for tanks, pipes, and vessels providing chemical and abrasion protection.',
                'canonical_url' => 'https://misubaguna.com/services/rubber-lining/',
                'og_title' => 'Rubber Lining Services - PT Misuba Guna Indonesia',
                'og_description' => 'Custom industrial rubber lining services for tanks, pipes, and vessels providing chemical and abrasion protection.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.8',
                'sitemap_changefreq' => 'monthly',
                'is_published' => true,
            ],
            [
                'slug' => 'frp-lining-repair',
                'url_path' => '/services/frp-lining-repair/',
                'name' => 'FRP Lining & Repair',
                'service_group' => 'Protective Lining & Coating',
                'headline' => 'FRP Lining, Tank Relining & Composite Repair Services',
                'summary' => 'Fiberglass Reinforced Plastic (FRP) lining and structural relining for chemical tanks, scrubber ducts, trenches, and containment bunds.',
                'key_features' => json_encode(['High chemical resistance to aggressive fumes and liquids', 'Lightweight structural reinforcement of corroded tanks', 'Seamless hand lay-up application', 'Fast turnaround time for industrial plant shutdowns']),
                'typical_problems' => json_encode(['Structural weakening and micro-cracking of aged chemical vessels', 'Corrosion of concrete containment dikes exposed to chemical spills', 'Fume leakage in exhaust ducts and scrubber columns']),
                'scope_of_work' => json_encode(['Substrate grinding, cleaning, and surface profile preparation', 'Vinyl ester or epoxy resin primer coat application', 'Multi-layer glass mat lay-up and resin saturation', 'Topcoat veil application with wax barrier for air release', 'Barcol hardness and thickness quality verification']),
                'industries_served' => json_encode(['Textile & Dyeing Industries', 'Chemical Dosing Plants', 'Power Plant Scrubbers & Chimneys', 'Water Neutralization Basins']),
                'materials_equipment' => json_encode(['Vinyl Ester Resin', 'E-Glass Chopped Strand Mat', 'Synthetic Surfacing Veils', 'Barcol Hardness Tester']),
                'related_products' => json_encode(['frp-lining', 'ceramic-lining']),
                'sort_order' => 5,
                'meta_title' => 'FRP Lining & Structural Repair Services - PT Misuba Guna Indonesia',
                'meta_description' => 'Professional FRP lining, tank relining, and fiberglass composite repair services for chemical containment and ducting.',
                'canonical_url' => 'https://misubaguna.com/services/frp-lining-repair/',
                'og_title' => 'FRP Lining & Structural Repair Services - PT Misuba Guna Indonesia',
                'og_description' => 'Professional FRP lining, tank relining, and fiberglass composite repair services for chemical containment and ducting.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.8',
                'sitemap_changefreq' => 'monthly',
                'is_published' => true,
            ],
            [
                'slug' => 'ptfe-lining-bonding',
                'url_path' => '/services/ptfe-lining-bonding/',
                'name' => 'PTFE Lining & Bonding',
                'service_group' => 'Protective Lining & Coating',
                'headline' => 'PTFE / PFA Corrosion Lining & Sheet Bonding Services',
                'summary' => 'Expert bonding and sleeve fitting of PTFE and PFA liners for piping, columns, valves, and ultra-pure chemical process equipment.',
                'key_features' => json_encode(['Unmatched resistance to full-range concentrated acids and solvents', 'Non-stick, ultra-clean surface preventing product build-up', 'Etched sheet bonding for high-vacuum resistance', '100% electrostatic spark tested']),
                'typical_problems' => json_encode(['Rapid degradation of standard coatings in concentrated nitric or sulfuric acid lines', 'Process fluid contamination from elastomer or metal leaching', 'Vacuum collapse of unbonded thin liners']),
                'scope_of_work' => json_encode(['Chemical etching of PTFE sheet backer', 'Precision bonding using temperature-resistant adhesive systems', 'Thermo-forming and flanging of liner sleeves over steel stub ends', 'Spark testing and vacuum decay verification']),
                'industries_served' => json_encode(['Semiconductor & High-Purity Chemicals', 'Pharmaceutical Manufacturing', 'Petrochemical Acid Lines', 'Hazardous Waste Processing']),
                'materials_equipment' => json_encode(['Virgin PTFE Sheet', 'PFA Molded Sleeves', 'Specialized Etching Reagents', 'Electrostatic Spark Tester']),
                'related_products' => json_encode(['ptfe-lining', 'ptfe-coating', 'ptfe-expansion-joint', 'ptfe-lined-rubber-metal-expansion-joint']),
                'sort_order' => 6,
                'meta_title' => 'PTFE Lining & Sheet Bonding Services - PT Misuba Guna Indonesia',
                'meta_description' => 'Precision PTFE and PFA lining, sheet bonding, and flanging services for ultra-corrosive chemical process systems.',
                'canonical_url' => 'https://misubaguna.com/services/ptfe-lining-bonding/',
                'og_title' => 'PTFE Lining & Sheet Bonding Services - PT Misuba Guna Indonesia',
                'og_description' => 'Precision PTFE and PFA lining, sheet bonding, and flanging services for ultra-corrosive chemical process systems.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.8',
                'sitemap_changefreq' => 'monthly',
                'is_published' => true,
            ],
            [
                'slug' => 'expansion-joint-installation',
                'url_path' => '/services/expansion-joint-installation/',
                'name' => 'Expansion Joint Installation & Replacement',
                'service_group' => 'Mechanical & Field Services',
                'headline' => 'Turnkey Installation, Replacement & Supervision for Metallic & Fabric Expansion Joints',
                'summary' => 'Field installation, splicing, alignment, and emergency replacement services for metal, fabric, rubber, and PTFE expansion joints.',
                'key_features' => json_encode(['Turnkey removal of failed joints and precise fitting of replacements', 'On-site thermal splicing of fabric expansion joints', 'Pre-installation piping stress and alignment verification', 'Cold-draw and shipping bar management']),
                'typical_problems' => json_encode(['Premature bellows failure due to piping misalignment or unrecorded thermal expansion', 'Fabric joint tearing and hot flue gas leakage in ductwork', 'Improper shipping bar removal leading to joint binding']),
                'scope_of_work' => json_encode(['Pre-installation survey of flange alignment and pipe anchors', 'Safe removal of old expansion joint assembly', 'Field positioning, bolting, and torqueing to engineering specification', 'On-site hot vulcanization or stitching of multi-layer fabric belts', 'Removal of shipping restraints and post-commissioning thermal inspection']),
                'industries_served' => json_encode(['Power Generation Plants', 'Cement & Lime Plants', 'Petrochemical Complex', 'Pulp & Paper Mills', 'Steel Smelters']),
                'materials_equipment' => json_encode(['Hot Splicing Irons', 'Torque Wrenches', 'Laser Misalignment Gauge', 'High-Temp Fabric Belt Assemblies']),
                'related_products' => json_encode(['fabric-expansion-joint', 'metal-expansion-joint', 'rubber-expansion-joint', 'ptfe-expansion-joint', 'ptfe-lined-rubber-metal-expansion-joint']),
                'sort_order' => 7,
                'meta_title' => 'Expansion Joint Installation & Replacement Services - PT Misuba Guna Indonesia',
                'meta_description' => 'Turnkey field installation, fabric splicing, alignment, and replacement services for industrial expansion joints.',
                'canonical_url' => 'https://misubaguna.com/services/expansion-joint-installation/',
                'og_title' => 'Expansion Joint Installation & Replacement Services - PT Misuba Guna Indonesia',
                'og_description' => 'Turnkey field installation, fabric splicing, alignment, and replacement services for industrial expansion joints.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.8',
                'sitemap_changefreq' => 'monthly',
                'is_published' => true,
            ],
            [
                'slug' => 'mechanical-maintenance',
                'url_path' => '/services/mechanical-maintenance/',
                'name' => 'Mechanical Maintenance & Repair',
                'service_group' => 'Mechanical & Field Services',
                'headline' => 'Industrial Mechanical Equipment Overhaul, Coupling Alignment & Sealing Maintenance',
                'summary' => 'Preventive and corrective mechanical maintenance services for pumps, valves, rotating shafts, couplings, and mechanical seals.',
                'key_features' => json_encode(['Comprehensive overhaul of pumps, mixers, and drive units', 'Precision laser shaft alignment to eliminate vibration', 'Mechanical seal and gland packing replacement', 'Preventive plant shutdown maintenance support']),
                'typical_problems' => json_encode(['Excessive vibration and premature bearing wear due to shaft misalignment', 'Process liquid leaking past worn gland packing or mechanical seals', 'Coupling element failure causing unscheduled machine stoppage']),
                'scope_of_work' => json_encode(['Disassembly, cleaning, and dimensional checking of rotating equipment', 'Replacement of worn bearings, oil seals, gaskets, and couplings', 'Installation of high-performance mechanical seals or gland packing', 'Precision laser alignment of motor-driven shaft assemblies', 'Vibration analysis and trial run verification']),
                'industries_served' => json_encode(['General Manufacturing', 'Palm Oil Refineries', 'Chemical Processing Facilities', 'Water Supply & Wastewater Stations']),
                'materials_equipment' => json_encode(['Laser Alignment Tool', 'Vibration Analyzer', 'Mechanical Seal Kits', 'Braided Gland Packing']),
                'related_products' => json_encode(['coupling', 'gland-packing', 'mechanical-seal', 'oil-seal', 'o-ring', 'gasket-sheet']),
                'sort_order' => 8,
                'meta_title' => 'Mechanical Maintenance & Repair Services - PT Misuba Guna Indonesia',
                'meta_description' => 'Industrial mechanical overhaul, pump repair, laser shaft alignment, and seal maintenance services.',
                'canonical_url' => 'https://misubaguna.com/services/mechanical-maintenance/',
                'og_title' => 'Mechanical Maintenance & Repair Services - PT Misuba Guna Indonesia',
                'og_description' => 'Industrial mechanical overhaul, pump repair, laser shaft alignment, and seal maintenance services.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.8',
                'sitemap_changefreq' => 'monthly',
                'is_published' => true,
            ],
            [
                'slug' => 'onsite-inspection',
                'url_path' => '/services/onsite-inspection/',
                'name' => 'On-Site Inspection & Troubleshooting',
                'service_group' => 'Mechanical & Field Services',
                'headline' => 'Engineering Technical Inspection, NDT & Field Troubleshooting',
                'summary' => 'On-site technical evaluation, root cause failure analysis, NDT inspection, and shutdown consultation for critical plant equipment.',
                'key_features' => json_encode(['Rapid response for emergency plant troubleshooting', 'Non-destructive testing (NDT) including spark and ultrasonic thickness measurement', 'Detailed engineering inspection report with actionable recommendations', 'Root cause failure analysis for recurring breakdowns']),
                'typical_problems' => json_encode(['Unexplained vibration or noise in fluid transfer systems', 'Recurring premature failure of seals, joints, or lining layers', 'Unknown corrosion rate or wall thickness reduction on critical piping']),
                'scope_of_work' => json_encode(['On-site physical and visual inspection by experienced technical specialists', 'Ultrasonic wall thickness measurement and flaw detection', 'High-voltage spark testing of protective linings', 'Operating parameters and thermal survey data gathering', 'Delivery of comprehensive diagnostic report with engineered solutions']),
                'industries_served' => json_encode(['Power & Energy Sector', 'Petrochemical & Gas Processing', 'Mining & Slurry Transportation', 'Industrial Plant Operations']),
                'materials_equipment' => json_encode(['Ultrasonic Thickness Gauge', 'Infrared Thermal Imager', 'Holiday Spark Tester', 'Vibration Analysis Meter']),
                'related_products' => json_encode(['cooling-tower', 'heat-exchanger', 'metal-expansion-joint', 'ptfe-lining', 'gland-packing']),
                'sort_order' => 9,
                'meta_title' => 'On-Site Inspection & Troubleshooting Services - PT Misuba Guna Indonesia',
                'meta_description' => 'On-site engineering inspection, NDT testing, plant troubleshooting, and root cause failure analysis.',
                'canonical_url' => 'https://misubaguna.com/services/onsite-inspection/',
                'og_title' => 'On-Site Inspection & Troubleshooting Services - PT Misuba Guna Indonesia',
                'og_description' => 'On-site engineering inspection, NDT testing, plant troubleshooting, and root cause failure analysis.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.8',
                'sitemap_changefreq' => 'monthly',
                'is_published' => true,
            ],
            [
                'slug' => 'valve-repair',
                'url_path' => '/services/valve-repair/',
                'name' => 'Valve Repair & Overhaul',
                'service_group' => 'Mechanical & Field Services',
                'headline' => 'Industrial Valve Maintenance, Seat Lapping & Pressure Testing Services',
                'summary' => 'Complete workshop and on-site repair, seat lapping, seal replacement, and pressure testing for control valves, safety valves, gate/globe valves, and actuators.',
                'key_features' => json_encode(['Control valve calibration and actuator overhaul', 'Precision seat lapping, grinding, and re-facing', 'Soft & hard seal replacement (PTFE, Stellite, Graphite)', 'API 598 hydrostatic and pneumatic seat leakage testing']),
                'typical_problems' => json_encode(['Internal seat leakage causing fluid loss and safety hazards', 'Stem scoring, packing deterioration, and gland leakage', 'Actuator diaphragm rupture or positioner signal drift', 'Severe cavitation pitting in high-pressure steam and acid lines']),
                'scope_of_work' => json_encode(['Disassembly, chemical decontamination, and dimensional measurement', 'Abrasive grit blasting of valve body and internal components', 'CNC machining or portable lapping of seating surfaces', 'Installation of new gland packings, bonnet gaskets, and O-rings', 'API 598 hydrostatic pressure body and seat leakage certification']),
                'industries_served' => json_encode(['Oil & Gas Refineries', 'Chemical & Petrochemical Plants', 'Power Generation Utilities', 'Pulp & Paper Mills', 'Fertilizer Manufacturing']),
                'materials_equipment' => json_encode(['Stellite Hardfacing Alloy', 'Flexible Graphite Packing', 'Spiral Wound Gaskets', 'Valve Hydrostatic Test Rig', 'Portable Seat Lapping Machine']),
                'related_products' => json_encode(['gland-packing', 'gasket-sheet', 'mechanical-seal', 'o-ring']),
                'sort_order' => 10,
                'meta_title' => 'Industrial Valve Repair & Overhaul Services - PT Misuba Guna Indonesia',
                'meta_description' => 'Professional industrial valve repair, seat lapping, control valve calibration, and hydrostatic pressure testing services.',
                'canonical_url' => 'https://misubaguna.com/services/valve-repair/',
                'og_title' => 'Industrial Valve Repair & Overhaul Services - PT Misuba Guna Indonesia',
                'og_description' => 'Professional industrial valve repair, seat lapping, control valve calibration, and hydrostatic pressure testing services.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.8',
                'sitemap_changefreq' => 'monthly',
                'is_published' => true,
            ],
            [
                'slug' => 'gearbox-repair',
                'url_path' => '/services/gearbox-repair/',
                'name' => 'Gearbox Repair & Rebuilding',
                'service_group' => 'Mechanical & Field Services',
                'headline' => 'Industrial Gearbox Overhaul, Gear Re-Machining & Bearing Replacement',
                'summary' => 'Comprehensive overhaul and rebuilding of helical, planetary, worm, and bevel industrial gearboxes, including gear re-machining, shaft alignment, and seal replacement.',
                'key_features' => json_encode(['Overhaul of spur, helical, planetary, and bevel gearboxes', 'Precision shaft journal restoration via thermal spray grinding', 'Heavy-duty bearing and radial oil seal replacement', 'Full-load run testing, vibration analysis, and backlash check']),
                'typical_problems' => json_encode(['Gear tooth pitting, spalling, and tooth breakage from shock loads', 'Bearing failure causing shaft misalignment and excessive vibration', 'Oil leakage from damaged shaft radial oil seals', 'Overheating due to lubrication breakdown or improper gear mesh']),
                'scope_of_work' => json_encode(['Teardown, ultrasonic cleaning, and magnetic particle inspection (MPI)', 'Gear tooth re-grinding or precision gear set replacement', 'Shaft journal thermal spray restoration and dynamic balancing', 'Installation of new premium bearings and Viton oil seals', 'No-load and full-load test run with temperature and vibration logging']),
                'industries_served' => json_encode(['Mining & Material Handling', 'Palm Oil Mills & Extruders', 'Cement & Steel Rolling Mills', 'Rubber & Plastic Mixers', 'Power Generation Drives']),
                'materials_equipment' => json_encode(['Alloy Steel Gears (20CrMnTi / 42CrMo)', 'Viton Oil Seals', 'Dynamic Balancing Bench', 'Vibration Analyzer', 'Gear Hobbing Machine']),
                'related_products' => json_encode(['coupling', 'oil-seal', 'o-ring']),
                'sort_order' => 11,
                'meta_title' => 'Industrial Gearbox Repair & Rebuilding - PT Misuba Guna Indonesia',
                'meta_description' => 'Complete industrial gearbox overhaul, gear re-machining, shaft thermal spray restoration, and bearing replacement services.',
                'canonical_url' => 'https://misubaguna.com/services/gearbox-repair/',
                'og_title' => 'Industrial Gearbox Repair & Rebuilding - PT Misuba Guna Indonesia',
                'og_description' => 'Complete industrial gearbox overhaul, gear re-machining, shaft thermal spray restoration, and bearing replacement services.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.8',
                'sitemap_changefreq' => 'monthly',
                'is_published' => true,
            ],
            [
                'slug' => 'pump-repair',
                'url_path' => '/services/pump-repair/',
                'name' => 'Pump & Rotating Equipment Repair',
                'service_group' => 'Mechanical & Field Services',
                'headline' => 'Industrial Pump Overhaul, Impeller Balancing & Seal Retrofitting',
                'summary' => 'Field and workshop repair of centrifugal, slurry, positive displacement, and vacuum pumps including dynamic impeller balancing and mechanical seal retrofitting.',
                'key_features' => json_encode(['Dynamic balancing of impellers and thermal spray coating', 'Mechanical seal conversion and gland packing maintenance', 'Casing wear ring clearance adjustment and volumetric repair', 'Laser shaft alignment for pump-motor drivelines']),
                'typical_problems' => json_encode(['Cavitation erosion on impellers reducing discharge flow', 'Mechanical seal failure leading to liquid leakage and bearing contamination', 'High vibration and shaft deflection from misalignment', 'Corrosive chemical thinning of pump volute casing walls']),
                'scope_of_work' => json_encode(['Teardown, cleaning, and non-destructive casing wall thickness testing', 'Ceramic anti-erosion coating application on impeller and volute', 'Shaft journal restoration and dynamic balancing', 'Precision mechanical seal installation and pressure check', 'Laser driveline alignment during on-site commissioning']),
                'industries_served' => json_encode(['Chemical & Acid Processing', 'Mining Slurry Operations', 'Water & Wastewater Utilities', 'Power Plant Boiler Feed', 'Food & Beverage Processing']),
                'materials_equipment' => json_encode(['Duplex Stainless Steel', 'Ceramic Epoxy Coatings', 'Laser Shaft Alignment System', 'Dynamic Balancing Rig']),
                'related_products' => json_encode(['mechanical-seal', 'gland-packing', 'coupling', 'o-ring', 'ceramic-coating']),
                'sort_order' => 12,
                'meta_title' => 'Industrial Pump & Rotating Equipment Repair - PT Misuba Guna Indonesia',
                'meta_description' => 'Expert pump overhaul, impeller dynamic balancing, mechanical seal retrofitting, and laser alignment services.',
                'canonical_url' => 'https://misubaguna.com/services/pump-repair/',
                'og_title' => 'Industrial Pump & Rotating Equipment Repair - PT Misuba Guna Indonesia',
                'og_description' => 'Expert pump overhaul, impeller dynamic balancing, mechanical seal retrofitting, and laser alignment services.',
                'robots_index' => true,
                'robots_follow' => true,
                'sitemap_include' => true,
                'sitemap_priority' => '0.8',
                'sitemap_changefreq' => 'monthly',
                'is_published' => true,
            ],
        ];

        foreach ($services as $service) {
            DB::table('public_services')->updateOrInsert(
                ['url_path' => $service['url_path']],
                array_merge($service, ['created_at' => $now, 'updated_at' => $now])
            );
        }

        $categories = [
            ['slug' => 'corrosion-protection', 'url_path' => '/product-category/corrosion-protection/', 'name' => 'Corrosion Protection', 'summary' => 'Products and services for protecting industrial equipment against corrosion, abrasion, chemical attack, and severe operating conditions.', 'description_html' => null, 'parent_group' => 'Corrosion Protection', 'sort_order' => 1, 'meta_title' => 'Corrosion Protection Products - PT Misuba Guna Indonesia', 'meta_description' => 'Products and services for protecting industrial equipment against corrosion, abrasion, chemical attack, and severe operating conditions.', 'canonical_url' => 'https://misubaguna.com/product-category/corrosion-protection/', 'og_title' => 'Corrosion Protection Products - PT Misuba Guna Indonesia', 'og_description' => 'Products and services for protecting industrial equipment against corrosion, abrasion, chemical attack, and severe operating conditions.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.5', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'coating', 'url_path' => '/product-category/coating/', 'name' => 'Coating', 'summary' => 'Ceramic coating and PTFE coating options for surface protection in industrial applications.', 'description_html' => null, 'parent_group' => null, 'sort_order' => 2, 'meta_title' => 'Coating Products - PT Misuba Guna Indonesia', 'meta_description' => 'Ceramic coating and PTFE coating options for surface protection in industrial applications.', 'canonical_url' => 'https://misubaguna.com/product-category/coating/', 'og_title' => 'Coating Products - PT Misuba Guna Indonesia', 'og_description' => 'Ceramic coating and PTFE coating options for surface protection in industrial applications.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.5', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'rubber-hose', 'url_path' => '/product-category/rubber-hose/', 'name' => 'Rubber Hose', 'summary' => 'Industrial rubber hose products for air, water, oil, fuel, steam, chemical, food-grade, and general transfer applications.', 'description_html' => null, 'parent_group' => null, 'sort_order' => 3, 'meta_title' => 'Rubber Hose Products - PT Misuba Guna Indonesia', 'meta_description' => 'Industrial rubber hose products for air, water, oil, fuel, steam, chemical, food-grade, and general transfer applications.', 'canonical_url' => 'https://misubaguna.com/product-category/rubber-hose/', 'og_title' => 'Rubber Hose Products - PT Misuba Guna Indonesia', 'og_description' => 'Industrial rubber hose products for air, water, oil, fuel, steam, chemical, food-grade, and general transfer applications.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.5', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'ptfe-expansion-joint', 'url_path' => '/product-category/ptfe-expansion-joint/', 'name' => 'PTFE Expansion Joint', 'summary' => 'PTFE expansion joint products for chemical-resistant, clean, and high-purity piping applications.', 'description_html' => null, 'parent_group' => null, 'sort_order' => 4, 'meta_title' => 'PTFE Expansion Joint Products - PT Misuba Guna Indonesia', 'meta_description' => 'PTFE expansion joint products for chemical-resistant, clean, and high-purity piping applications.', 'canonical_url' => 'https://misubaguna.com/product-category/ptfe-expansion-joint/', 'og_title' => 'PTFE Expansion Joint Products - PT Misuba Guna Indonesia', 'og_description' => 'PTFE expansion joint products for chemical-resistant, clean, and high-purity piping applications.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.5', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'sealing-system', 'url_path' => '/product-category/sealing-system/', 'name' => 'Sealing System', 'summary' => 'Industrial sealing products including gland packing, oil seals, O-rings, gasket sheets, and mechanical seals.', 'description_html' => null, 'parent_group' => 'Sealing System', 'sort_order' => 5, 'meta_title' => 'Sealing System Products - PT Misuba Guna Indonesia', 'meta_description' => 'Industrial sealing products including gland packing, oil seals, O-rings, gasket sheets, and mechanical seals.', 'canonical_url' => 'https://misubaguna.com/product-category/sealing-system/', 'og_title' => 'Sealing System Products - PT Misuba Guna Indonesia', 'og_description' => 'Industrial sealing products including gland packing, oil seals, O-rings, gasket sheets, and mechanical seals.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.5', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'gasket-sheet', 'url_path' => '/product-category/gasket-sheet/', 'name' => 'Gasket Sheet', 'summary' => 'Gasket sheet materials and custom-cut gasket supply for industrial sealing applications.', 'description_html' => null, 'parent_group' => null, 'sort_order' => 6, 'meta_title' => 'Gasket Sheet Products - PT Misuba Guna Indonesia', 'meta_description' => 'Gasket sheet materials and custom-cut gasket supply for industrial sealing applications.', 'canonical_url' => 'https://misubaguna.com/product-category/gasket-sheet/', 'og_title' => 'Gasket Sheet Products - PT Misuba Guna Indonesia', 'og_description' => 'Gasket sheet materials and custom-cut gasket supply for industrial sealing applications.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.5', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'thermal-systems', 'url_path' => '/product-category/thermal-systems/', 'name' => 'Thermal Systems', 'summary' => 'Industrial thermal equipment including cooling towers, heat exchangers, plate heat exchangers, and oil coolers.', 'description_html' => null, 'parent_group' => 'Thermal Systems', 'sort_order' => 7, 'meta_title' => 'Thermal Systems Products - PT Misuba Guna Indonesia', 'meta_description' => 'Industrial thermal equipment including cooling towers, heat exchangers, plate heat exchangers, and oil coolers.', 'canonical_url' => 'https://misubaguna.com/product-category/thermal-systems/', 'og_title' => 'Thermal Systems Products - PT Misuba Guna Indonesia', 'og_description' => 'Industrial thermal equipment including cooling towers, heat exchangers, plate heat exchangers, and oil coolers.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.5', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
        ];

        foreach ($categories as $category) {
            DB::table('public_product_categories')->updateOrInsert(
                ['url_path' => $category['url_path']],
                array_merge($category, ['created_at' => $now, 'updated_at' => $now])
            );
        }

        $products = [
            ['slug' => 'fabric-expansion-joint', 'url_path' => '/product/fabric-expansion-joint/', 'name' => 'Fabric Expansion Joint', 'product_group' => 'Flexible Joint', 'product_subgroup' => null, 'headline' => 'Fabric Expansion Joint', 'summary' => 'Flexible non-metallic expansion joints for ducting and piping systems that need movement absorption, vibration isolation, and high-temperature sealing.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 1, 'meta_title' => 'Fabric Expansion Joint - PT Misuba Guna Indonesia', 'meta_description' => 'Flexible non-metallic expansion joints for ducting and piping systems that need movement absorption, vibration isolation, and high-temperature sealing.', 'canonical_url' => 'https://misubaguna.com/product/fabric-expansion-joint/', 'og_title' => 'Fabric Expansion Joint - PT Misuba Guna Indonesia', 'og_description' => 'Flexible non-metallic expansion joints for ducting and piping systems that need movement absorption, vibration isolation, and high-temperature sealing.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'metal-expansion-joint', 'url_path' => '/product/metal-expansion-joint/', 'name' => 'Metal Expansion Joint', 'product_group' => 'Flexible Joint', 'product_subgroup' => null, 'headline' => 'Metal Expansion Joint', 'summary' => 'Precision-engineered metal bellows expansion joints for absorbing thermal expansion, vibration, and mechanical movement in piping and duct systems.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 2, 'meta_title' => 'Metal Expansion Joint - PT Misuba Guna Indonesia', 'meta_description' => 'Precision-engineered metal bellows expansion joints for absorbing thermal expansion, vibration, and mechanical movement in piping and duct systems.', 'canonical_url' => 'https://misubaguna.com/product/metal-expansion-joint/', 'og_title' => 'Metal Expansion Joint - PT Misuba Guna Indonesia', 'og_description' => 'Precision-engineered metal bellows expansion joints for absorbing thermal expansion, vibration, and mechanical movement in piping and duct systems.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'rubber-expansion-joint', 'url_path' => '/product/rubber-expansion-joint/', 'name' => 'Rubber Expansion Joint', 'product_group' => 'Flexible Joint', 'product_subgroup' => null, 'headline' => 'Rubber Expansion Joint', 'summary' => 'Flexible rubber connectors for piping systems that absorb movement, isolate vibration, and compensate for thermal expansion or misalignment.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 3, 'meta_title' => 'Rubber Expansion Joint - PT Misuba Guna Indonesia', 'meta_description' => 'Flexible rubber connectors for piping systems that absorb movement, isolate vibration, and compensate for thermal expansion or misalignment.', 'canonical_url' => 'https://misubaguna.com/product/rubber-expansion-joint/', 'og_title' => 'Rubber Expansion Joint - PT Misuba Guna Indonesia', 'og_description' => 'Flexible rubber connectors for piping systems that absorb movement, isolate vibration, and compensate for thermal expansion or misalignment.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'ptfe-expansion-joint', 'url_path' => '/product/ptfe-expansion-joint/', 'name' => 'PTFE Expansion Joint', 'product_group' => 'Flexible Joint', 'product_subgroup' => null, 'headline' => 'PTFE Expansion Joint', 'summary' => 'PTFE expansion joints for clean, corrosive, high-purity, and chemically aggressive service where non-stick and chemical resistance are required.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 4, 'meta_title' => 'PTFE Expansion Joint - PT Misuba Guna Indonesia', 'meta_description' => 'PTFE expansion joints for clean, corrosive, high-purity, and chemically aggressive service where non-stick and chemical resistance are required.', 'canonical_url' => 'https://misubaguna.com/product/ptfe-expansion-joint/', 'og_title' => 'PTFE Expansion Joint - PT Misuba Guna Indonesia', 'og_description' => 'PTFE expansion joints for clean, corrosive, high-purity, and chemically aggressive service where non-stick and chemical resistance are required.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'ptfe-lined-rubber-metal-expansion-joint', 'url_path' => '/product/ptfe-lined-rubber-metal-expansion-joint/', 'name' => 'PTFE Lined Expansion Joint (Rubber and Metal)', 'product_group' => 'Flexible Joint', 'product_subgroup' => null, 'headline' => 'PTFE Lined Expansion Joint (Rubber and Metal)', 'summary' => 'PTFE-lined rubber or metal expansion joints that combine movement absorption with internal chemical protection for aggressive media.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 5, 'meta_title' => 'PTFE Lined Expansion Joint (Rubber and Metal) - PT Misuba Guna Indonesia', 'meta_description' => 'PTFE-lined rubber or metal expansion joints that combine movement absorption with internal chemical protection for aggressive media.', 'canonical_url' => 'https://misubaguna.com/product/ptfe-lined-rubber-metal-expansion-joint/', 'og_title' => 'PTFE Lined Expansion Joint (Rubber and Metal) - PT Misuba Guna Indonesia', 'og_description' => 'PTFE-lined rubber or metal expansion joints that combine movement absorption with internal chemical protection for aggressive media.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'rubber-hose', 'url_path' => '/product/rubber-hose/', 'name' => 'Rubber Hose', 'product_group' => 'Flexible Joint', 'product_subgroup' => null, 'headline' => 'Rubber Hose', 'summary' => 'Industrial rubber hoses for transferring air, water, oil, fuel, steam, chemicals, food-grade materials, and other process media.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 6, 'meta_title' => 'Rubber Hose - PT Misuba Guna Indonesia', 'meta_description' => 'Industrial rubber hoses for transferring air, water, oil, fuel, steam, chemicals, food-grade materials, and other process media.', 'canonical_url' => 'https://misubaguna.com/product/rubber-hose/', 'og_title' => 'Rubber Hose - PT Misuba Guna Indonesia', 'og_description' => 'Industrial rubber hoses for transferring air, water, oil, fuel, steam, chemicals, food-grade materials, and other process media.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'flexible-metal-hose', 'url_path' => '/product/flexible-metal-hose/', 'name' => 'Flexible Metal Hose', 'product_group' => 'Flexible Joint', 'product_subgroup' => null, 'headline' => 'Flexible Metal Hose', 'summary' => 'Stainless steel flexible metal hoses designed for demanding temperature, pressure, vibration, and corrosive service.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 7, 'meta_title' => 'Flexible Metal Hose - PT Misuba Guna Indonesia', 'meta_description' => 'Stainless steel flexible metal hoses designed for demanding temperature, pressure, vibration, and corrosive service.', 'canonical_url' => 'https://misubaguna.com/product/flexible-metal-hose/', 'og_title' => 'Flexible Metal Hose - PT Misuba Guna Indonesia', 'og_description' => 'Stainless steel flexible metal hoses designed for demanding temperature, pressure, vibration, and corrosive service.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'ptfe-lining', 'url_path' => '/product/ptfe-lining/', 'name' => 'PTFE Lining', 'product_group' => 'Corrosion Protection', 'product_subgroup' => 'Lining', 'headline' => 'PTFE Lining', 'summary' => 'PTFE lining for corrosive, reactive, or ultra-pure media where chemical resistance and a smooth non-stick surface are required.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 8, 'meta_title' => 'PTFE Lining - PT Misuba Guna Indonesia', 'meta_description' => 'PTFE lining for corrosive, reactive, or ultra-pure media where chemical resistance and a smooth non-stick surface are required.', 'canonical_url' => 'https://misubaguna.com/product/ptfe-lining/', 'og_title' => 'PTFE Lining - PT Misuba Guna Indonesia', 'og_description' => 'PTFE lining for corrosive, reactive, or ultra-pure media where chemical resistance and a smooth non-stick surface are required.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'rubber-lining', 'url_path' => '/product/rubber-lining/', 'name' => 'Rubber Lining', 'product_group' => 'Corrosion Protection', 'product_subgroup' => 'Lining', 'headline' => 'Rubber Lining', 'summary' => 'Protective rubber lining applied to equipment surfaces to resist corrosion, abrasion, impact, and chemical attack.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 9, 'meta_title' => 'Rubber Lining - PT Misuba Guna Indonesia', 'meta_description' => 'Protective rubber lining applied to equipment surfaces to resist corrosion, abrasion, impact, and chemical attack.', 'canonical_url' => 'https://misubaguna.com/product/rubber-lining/', 'og_title' => 'Rubber Lining - PT Misuba Guna Indonesia', 'og_description' => 'Protective rubber lining applied to equipment surfaces to resist corrosion, abrasion, impact, and chemical attack.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'ceramic-lining', 'url_path' => '/product/ceramic-lining/', 'name' => 'Ceramic Lining', 'product_group' => 'Corrosion Protection', 'product_subgroup' => 'Lining', 'headline' => 'Ceramic Lining', 'summary' => 'Ceramic lining for industrial equipment that needs high abrasion and wear protection in severe service.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 10, 'meta_title' => 'Ceramic Lining - PT Misuba Guna Indonesia', 'meta_description' => 'Ceramic lining for industrial equipment that needs high abrasion and wear protection in severe service.', 'canonical_url' => 'https://misubaguna.com/product/ceramic-lining/', 'og_title' => 'Ceramic Lining - PT Misuba Guna Indonesia', 'og_description' => 'Ceramic lining for industrial equipment that needs high abrasion and wear protection in severe service.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'frp-lining', 'url_path' => '/product/frp-lining/', 'name' => 'FRP Lining', 'product_group' => 'Corrosion Protection', 'product_subgroup' => 'Lining', 'headline' => 'FRP Lining', 'summary' => 'FRP lining for corrosion-resistant protection of tanks, vessels, ducts, and process equipment.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 11, 'meta_title' => 'FRP Lining - PT Misuba Guna Indonesia', 'meta_description' => 'FRP lining for corrosion-resistant protection of tanks, vessels, ducts, and process equipment.', 'canonical_url' => 'https://misubaguna.com/product/frp-lining/', 'og_title' => 'FRP Lining - PT Misuba Guna Indonesia', 'og_description' => 'FRP lining for corrosion-resistant protection of tanks, vessels, ducts, and process equipment.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'ceramic-coating', 'url_path' => '/product/ceramic-coating/', 'name' => 'Ceramic Coating', 'product_group' => 'Corrosion Protection', 'product_subgroup' => 'Coating', 'headline' => 'Ceramic Coating', 'summary' => 'Ceramic coating for surface protection against heat, corrosion, wear, and chemical exposure.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 12, 'meta_title' => 'Ceramic Coating - PT Misuba Guna Indonesia', 'meta_description' => 'Ceramic coating for surface protection against heat, corrosion, wear, and chemical exposure.', 'canonical_url' => 'https://misubaguna.com/product/ceramic-coating/', 'og_title' => 'Ceramic Coating - PT Misuba Guna Indonesia', 'og_description' => 'Ceramic coating for surface protection against heat, corrosion, wear, and chemical exposure.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'ptfe-coating', 'url_path' => '/product/ptfe-coating/', 'name' => 'PTFE Coating', 'product_group' => 'Corrosion Protection', 'product_subgroup' => 'Coating', 'headline' => 'PTFE Coating', 'summary' => 'PTFE coating for chemical-resistant, non-stick, low-friction surface protection in industrial applications.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 13, 'meta_title' => 'PTFE Coating - PT Misuba Guna Indonesia', 'meta_description' => 'PTFE coating for chemical-resistant, non-stick, low-friction surface protection in industrial applications.', 'canonical_url' => 'https://misubaguna.com/product/ptfe-coating/', 'og_title' => 'PTFE Coating - PT Misuba Guna Indonesia', 'og_description' => 'PTFE coating for chemical-resistant, non-stick, low-friction surface protection in industrial applications.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'gland-packing', 'url_path' => '/product/gland-packing/', 'name' => 'Gland Packing', 'product_group' => 'Sealing System', 'product_subgroup' => null, 'headline' => 'Gland Packing', 'summary' => 'Braided or woven gland packing for preventing leakage along shafts in pumps, valves, mixers, and other rotating or reciprocating equipment.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => json_encode(['/images/products/gland packing/Glandpacking1 (1).webp', '/images/products/gland packing/Glandpacking1 (2).webp', '/images/products/gland packing/Glandpacking1 (3).webp']), 'sort_order' => 14, 'meta_title' => 'Gland Packing - PT Misuba Guna Indonesia', 'meta_description' => 'Braided or woven gland packing for preventing leakage along shafts in pumps, valves, mixers, and other rotating or reciprocating equipment.', 'canonical_url' => 'https://misubaguna.com/product/gland-packing/', 'og_title' => 'Gland Packing - PT Misuba Guna Indonesia', 'og_description' => 'Braided or woven gland packing for preventing leakage along shafts in pumps, valves, mixers, and other rotating or reciprocating equipment.', 'og_image_path' => '/images/products/gland packing/Glandpacking1 (1).webp', 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'oil-seal', 'url_path' => '/product/oil-seal/', 'name' => 'Oil Seal', 'product_group' => 'Sealing System', 'product_subgroup' => null, 'headline' => 'Oil Seal', 'summary' => 'Rotary shaft/radial lip seals for retaining lubricants and preventing dirt, dust, and moisture from entering machinery.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 15, 'meta_title' => 'Oil Seal - PT Misuba Guna Indonesia', 'meta_description' => 'Rotary shaft/radial lip seals for retaining lubricants and preventing dirt, dust, and moisture from entering machinery.', 'canonical_url' => 'https://misubaguna.com/product/oil-seal/', 'og_title' => 'Oil Seal - PT Misuba Guna Indonesia', 'og_description' => 'Rotary shaft/radial lip seals for retaining lubricants and preventing dirt, dust, and moisture from entering machinery.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'o-ring', 'url_path' => '/product/o-ring/', 'name' => 'O-Ring', 'product_group' => 'Sealing System', 'product_subgroup' => null, 'headline' => 'O-Ring', 'summary' => 'Elastomer O-rings for sealing fluids or gases in static and dynamic applications across pumps, valves, cylinders, and industrial systems.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 16, 'meta_title' => 'O-Ring - PT Misuba Guna Indonesia', 'meta_description' => 'Elastomer O-rings for sealing fluids or gases in static and dynamic applications across pumps, valves, cylinders, and industrial systems.', 'canonical_url' => 'https://misubaguna.com/product/o-ring/', 'og_title' => 'O-Ring - PT Misuba Guna Indonesia', 'og_description' => 'Elastomer O-rings for sealing fluids or gases in static and dynamic applications across pumps, valves, cylinders, and industrial systems.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'gasket-sheet', 'url_path' => '/product/gasket-sheet/', 'name' => 'Gasket Sheet', 'product_group' => 'Sealing System', 'product_subgroup' => null, 'headline' => 'Gasket Sheet', 'summary' => 'Gasket sheet materials for cutting seals used between flanges, pipe joints, equipment covers, and machinery surfaces.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 17, 'meta_title' => 'Gasket Sheet - PT Misuba Guna Indonesia', 'meta_description' => 'Gasket sheet materials for cutting seals used between flanges, pipe joints, equipment covers, and machinery surfaces.', 'canonical_url' => 'https://misubaguna.com/product/gasket-sheet/', 'og_title' => 'Gasket Sheet - PT Misuba Guna Indonesia', 'og_description' => 'Gasket sheet materials for cutting seals used between flanges, pipe joints, equipment covers, and machinery surfaces.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'mechanical-seal', 'url_path' => '/product/mechanical-seal/', 'name' => 'Mechanical Seal', 'product_group' => 'Sealing System', 'product_subgroup' => null, 'headline' => 'Mechanical Seal', 'summary' => 'Mechanical seals for preventing leakage in rotating equipment such as pumps, mixers, and compressors.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 18, 'meta_title' => 'Mechanical Seal - PT Misuba Guna Indonesia', 'meta_description' => 'Mechanical seals for preventing leakage in rotating equipment such as pumps, mixers, and compressors.', 'canonical_url' => 'https://misubaguna.com/product/mechanical-seal/', 'og_title' => 'Mechanical Seal - PT Misuba Guna Indonesia', 'og_description' => 'Mechanical seals for preventing leakage in rotating equipment such as pumps, mixers, and compressors.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'coupling', 'url_path' => '/product/coupling/', 'name' => 'Coupling', 'product_group' => 'Power Transfer', 'product_subgroup' => null, 'headline' => 'Coupling', 'summary' => 'Mechanical couplings for connecting shafts and transmitting torque while accommodating alignment and vibration conditions.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 19, 'meta_title' => 'Coupling - PT Misuba Guna Indonesia', 'meta_description' => 'Mechanical couplings for connecting shafts and transmitting torque while accommodating alignment and vibration conditions.', 'canonical_url' => 'https://misubaguna.com/product/coupling/', 'og_title' => 'Coupling - PT Misuba Guna Indonesia', 'og_description' => 'Mechanical couplings for connecting shafts and transmitting torque while accommodating alignment and vibration conditions.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'cooling-tower', 'url_path' => '/product/cooling-tower/', 'name' => 'Cooling Tower', 'product_group' => 'Thermal Systems', 'product_subgroup' => null, 'headline' => 'Cooling Tower', 'summary' => 'High-efficiency cooling towers for heat rejection in industrial processes and HVAC systems.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 20, 'meta_title' => 'Cooling Tower - PT Misuba Guna Indonesia', 'meta_description' => 'High-efficiency cooling towers for heat rejection in industrial processes and HVAC systems.', 'canonical_url' => 'https://misubaguna.com/product/cooling-tower/', 'og_title' => 'Cooling Tower - PT Misuba Guna Indonesia', 'og_description' => 'High-efficiency cooling towers for heat rejection in industrial processes and HVAC systems.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'heat-exchanger', 'url_path' => '/product/heat-exchanger/', 'name' => 'Heat Exchanger', 'product_group' => 'Thermal Systems', 'product_subgroup' => null, 'headline' => 'Heat Exchanger', 'summary' => 'Custom-built shell and tube heat exchangers for efficient thermal energy transfer across process fluids.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 21, 'meta_title' => 'Heat Exchanger - PT Misuba Guna Indonesia', 'meta_description' => 'Custom-built shell and tube heat exchangers for efficient thermal energy transfer across process fluids.', 'canonical_url' => 'https://misubaguna.com/product/heat-exchanger/', 'og_title' => 'Heat Exchanger - PT Misuba Guna Indonesia', 'og_description' => 'Custom-built shell and tube heat exchangers for efficient thermal energy transfer across process fluids.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'plate-heat-exchanger', 'url_path' => '/product/plate-heat-exchanger/', 'name' => 'Plate Heat Exchanger', 'product_group' => 'Thermal Systems', 'product_subgroup' => null, 'headline' => 'Plate Heat Exchanger', 'summary' => 'Compact and high-performance plate heat exchangers designed for rapid heat transfer and easy maintenance.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 22, 'meta_title' => 'Plate Heat Exchanger - PT Misuba Guna Indonesia', 'meta_description' => 'Compact and high-performance plate heat exchangers designed for rapid heat transfer and easy maintenance.', 'canonical_url' => 'https://misubaguna.com/product/plate-heat-exchanger/', 'og_title' => 'Plate Heat Exchanger - PT Misuba Guna Indonesia', 'og_description' => 'Compact and high-performance plate heat exchangers designed for rapid heat transfer and easy maintenance.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
            ['slug' => 'oil-cooler', 'url_path' => '/product/oil-cooler/', 'name' => 'Oil Cooler', 'product_group' => 'Thermal Systems', 'product_subgroup' => null, 'headline' => 'Oil Cooler', 'summary' => 'Industrial oil coolers for regulating hydraulic, engine, and lubricating oil temperatures.', 'content_html' => null, 'key_features' => null, 'applications' => null, 'materials' => null, 'technical_specs' => null, 'gallery' => null, 'sort_order' => 23, 'meta_title' => 'Oil Cooler - PT Misuba Guna Indonesia', 'meta_description' => 'Industrial oil coolers for regulating hydraulic, engine, and lubricating oil temperatures.', 'canonical_url' => 'https://misubaguna.com/product/oil-cooler/', 'og_title' => 'Oil Cooler - PT Misuba Guna Indonesia', 'og_description' => 'Industrial oil coolers for regulating hydraulic, engine, and lubricating oil temperatures.', 'og_image_path' => null, 'robots_index' => true, 'robots_follow' => true, 'sitemap_include' => true, 'sitemap_priority' => '0.9', 'sitemap_changefreq' => 'monthly', 'schema_json' => null, 'is_published' => true],
        ];

        foreach ($products as $product) {
            DB::table('public_products')->updateOrInsert(
                ['url_path' => $product['url_path']],
                array_merge($product, ['created_at' => $now, 'updated_at' => $now])
            );
        }

        $redirects = [
            [
                'source_path' => '/indexpage/',
                'target_url' => '/',
                'status_code' => 301,
                'is_active' => false,
                'note' => 'Legacy duplicate homepage-like page. Enable after checking Google Search Console traffic/backlinks.',
            ],
        ];

        foreach ($redirects as $redirect) {
            DB::table('public_redirects')->updateOrInsert(
                ['source_path' => $redirect['source_path']],
                array_merge($redirect, ['created_at' => $now, 'updated_at' => $now])
            );
        }

        $settings = [
            ['key' => 'company_name', 'value' => 'PT Misuba Guna Indonesia', 'type' => 'string', 'description' => 'Public company name for SEO/schema.'],
            ['key' => 'company_email', 'value' => 'marketing@misubaguna.com', 'type' => 'string', 'description' => 'Public contact email.'],
            ['key' => 'company_phone', 'value' => '+62 21 55660700', 'type' => 'string', 'description' => 'Public telephone.'],
            ['key' => 'company_whatsapp', 'value' => '+62 811-8715-671', 'type' => 'string', 'description' => 'Public WhatsApp.'],
            ['key' => 'company_website', 'value' => 'https://misubaguna.com', 'type' => 'string', 'description' => 'Public website URL.'],
            ['key' => 'operational_address', 'value' => 'Ruko Mutiara Karawaci Blok C29, Bencongan Indah, Kecamatan Kelapa Dua, Tangerang, Banten 15810', 'type' => 'string', 'description' => 'Operational address from current public site.'],
            ['key' => 'warehouse_address', 'value' => 'Ruko Mutiara Karawaci Blok B36, Bencongan Indah, Kecamatan Kelapa Dua, Tangerang, Banten 15810', 'type' => 'string', 'description' => 'Warehouse address.'],
            ['key' => 'billing_address', 'value' => 'NEEDS_CONFIRMATION: public site has conflict between STC Senayan Lantai 4 No 80 and Lantai 2 No 89', 'type' => 'string', 'description' => 'Fix before rendering schema or footer.'],
        ];

        foreach ($settings as $setting) {
            DB::table('site_settings')->updateOrInsert(
                ['key' => $setting['key']],
                array_merge($setting, ['created_at' => $now, 'updated_at' => $now])
            );
        }
    }
}
