<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PublicSiteSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $pages = [
        [
            'page_type' => 'home',
            'slug' => 'home',
            'url_path' => '/',
            'title' => 'PT Misuba Guna Indonesia - Build on Trust, Driving on Excellence',
            'headline' => 'PT Misuba Guna Indonesia',
            'excerpt' => 'Homepage positions MGI as a reliable industrial technical solution supplier; shows about preview, product groups, clients/locations, partners and contact footer.',
            'content_html' => null,
            'sections' => null,
            'meta_title' => 'PT Misuba Guna Indonesia - Build on Trust, Driving on Excellence',
            'meta_description' => 'Partner with PT Misuba Guna Indonesia for reliable, high-quality technical solutions. We drive business forward with innovation, excellence, and trust.',
            'canonical_url' => 'https://misubaguna.com/',
            'og_title' => 'PT Misuba Guna Indonesia - Build on Trust, Driving on Excellence',
            'og_description' => 'Partner with PT Misuba Guna Indonesia for reliable, high-quality technical solutions. We drive business forward with innovation, excellence, and trust.',
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '1.0',
            'sitemap_changefreq' => 'weekly',
            'schema_json' => null,
            'is_published' => true,
            'published_at' => null,
            'sort_order' => 1,
        ],
        [
            'page_type' => 'page',
            'slug' => 'about-us',
            'url_path' => '/about-us/',
            'title' => 'About Misuba | Quality Engineering Products & Services',
            'headline' => 'About Us / About Misuba',
            'excerpt' => 'About page says MGI was established in 2020 and focuses on quality goods/services, reasonable prices, fast and precise delivery, global manufacturer partnerships, and trust.',
            'content_html' => null,
            'sections' => null,
            'meta_title' => 'About Misuba | Quality Engineering Products & Services',
            'meta_description' => 'PT Misuba Guna Indonesia Providing quality engineering products & services at competitive prices with fast delivery and trusted global partnerships since 2020.',
            'canonical_url' => 'https://misubaguna.com/about-us/',
            'og_title' => 'About Misuba | Quality Engineering Products & Services',
            'og_description' => 'PT Misuba Guna Indonesia Providing quality engineering products & services at competitive prices with fast delivery and trusted global partnerships since 2020.',
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.8',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
            'published_at' => null,
            'sort_order' => 2,
        ],
        [
            'page_type' => 'project_list',
            'slug' => 'project-list',
            'url_path' => '/project-list/',
            'title' => 'Project List - PT Misuba Guna Indonesia',
            'headline' => 'Project List',
            'excerpt' => 'Project/category listing page covers expansion joints, corrosion/abrasion, material handling, sealing systems, heat transfer, pumps, valves, conveyor parts and other industrial supply examples.',
            'content_html' => null,
            'sections' => null,
            'meta_title' => 'Project List - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/project-list/',
            'og_title' => 'Project List - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.8',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
            'published_at' => null,
            'sort_order' => 3,
        ],
        [
            'page_type' => 'contact',
            'slug' => 'contact-us',
            'url_path' => '/contact-us/',
            'title' => 'Contact Us - Get in Touch withPT Misuba Guna Indonesia',
            'headline' => 'Contact Us / Get in Touch',
            'excerpt' => 'Contact page lists operational office, warehouse, billing address, telephone, WhatsApp, email, website and sales contact details.',
            'content_html' => null,
            'sections' => null,
            'meta_title' => 'Contact Us - Get in Touch withPT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/contact-us/',
            'og_title' => 'Contact Us - Get in Touch withPT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.8',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
            'published_at' => null,
            'sort_order' => 4,
        ],
        [
            'page_type' => 'career',
            'slug' => 'career',
            'url_path' => '/career/',
            'title' => 'Careers at Misuba | Join Our Team & Grow With Us',
            'headline' => 'Careers at Misuba / Join Our Team & Grow With Us',
            'excerpt' => 'Career page presents careers and recruitment information for MGI.',
            'content_html' => null,
            'sections' => null,
            'meta_title' => 'Careers at Misuba | Join Our Team & Grow With Us',
            'meta_description' => 'Careers at Misuba – Join our team and grow with us. Explore exciting opportunities in engineering, marketing, supply chain, and more.',
            'canonical_url' => 'https://misubaguna.com/career/',
            'og_title' => 'Careers at Misuba | Join Our Team & Grow With Us',
            'og_description' => 'Careers at Misuba – Join our team and grow with us. Explore exciting opportunities in engineering, marketing, supply chain, and more.',
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.8',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
            'published_at' => null,
            'sort_order' => 5,
        ],
        [
            'page_type' => 'catalog',
            'slug' => 'catalog',
            'url_path' => '/catalog/',
            'title' => 'Catalog - VERIFY',
            'headline' => 'Catalog - VERIFY',
            'excerpt' => 'Catalog link exists in navigation. Prior web click returned an internal error in the ChatGPT browsing environment; exact live browser status must be verified.',
            'content_html' => null,
            'sections' => null,
            'meta_title' => 'Catalog - VERIFY',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/catalog/',
            'og_title' => 'Catalog - VERIFY',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.8',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
            'published_at' => null,
            'sort_order' => 6,
        ],
    ];

        foreach ($pages as $page) {
            DB::table('public_pages')->updateOrInsert(
                ['url_path' => $page['url_path']],
                array_merge($page, ['created_at' => $now, 'updated_at' => $now])
            );
        }

        $categories = [
        [
            'slug' => 'corrosion-protection',
            'url_path' => '/product-category/corrosion-protection/',
            'name' => 'Corrosion Protection',
            'summary' => 'Category archive listing corrosion protection products.',
            'description_html' => null,
            'parent_group' => 'Corrosion Protection',
            'sort_order' => 1,
            'meta_title' => 'Product Category: Corrosion Protection',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product-category/corrosion-protection/',
            'og_title' => 'Product Category: Corrosion Protection',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.5',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'coating',
            'url_path' => '/product-category/coating/',
            'name' => 'Coating',
            'summary' => 'Category archive listing coating products.',
            'description_html' => null,
            'parent_group' => null,
            'sort_order' => 2,
            'meta_title' => 'Product Category: Coating',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product-category/coating/',
            'og_title' => 'Product Category: Coating',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.5',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'rubber-hose',
            'url_path' => '/product-category/rubber-hose/',
            'name' => 'Rubber Hose',
            'summary' => 'Category archive for rubber hose.',
            'description_html' => null,
            'parent_group' => null,
            'sort_order' => 3,
            'meta_title' => 'Product Category: Rubber Hose',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product-category/rubber-hose/',
            'og_title' => 'Product Category: Rubber Hose',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.5',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'ptfe-expansion-joint',
            'url_path' => '/product-category/ptfe-expansion-joint/',
            'name' => 'PTFE Expansion Joint',
            'summary' => 'Category archive for PTFE expansion joint.',
            'description_html' => null,
            'parent_group' => null,
            'sort_order' => 4,
            'meta_title' => 'Product Category: PTFE Expansion Joint',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product-category/ptfe-expansion-joint/',
            'og_title' => 'Product Category: PTFE Expansion Joint',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.5',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'sealing-system',
            'url_path' => '/product-category/sealing-system/',
            'name' => 'Sealing System',
            'summary' => 'Category archive listing sealing system products.',
            'description_html' => null,
            'parent_group' => 'Sealing System',
            'sort_order' => 5,
            'meta_title' => 'Product Category: Sealing System',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product-category/sealing-system/',
            'og_title' => 'Product Category: Sealing System',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.5',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'gasket-sheet',
            'url_path' => '/product-category/gasket-sheet/',
            'name' => 'Gasket Sheet',
            'summary' => 'Category archive for gasket sheet found in search result.',
            'description_html' => null,
            'parent_group' => null,
            'sort_order' => 6,
            'meta_title' => 'Product Category: Gasket Sheet',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product-category/gasket-sheet/',
            'og_title' => 'Product Category: Gasket Sheet',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.5',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
    ];

        foreach ($categories as $category) {
            DB::table('public_product_categories')->updateOrInsert(
                ['url_path' => $category['url_path']],
                array_merge($category, ['created_at' => $now, 'updated_at' => $now])
            );
        }

        $products = [
        [
            'slug' => 'fabric-expansion-joint',
            'url_path' => '/product/fabric-expansion-joint/',
            'name' => 'Fabric Expansion Joint',
            'product_group' => 'Flexible Joint',
            'product_subgroup' => null,
            'headline' => 'Fabric Expansion Joint',
            'summary' => 'Fabric expansion joint page for flexible sealing and vibration absorption; includes product images, engineering expertise, on-site installation/repair messaging.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 1,
            'meta_title' => 'Fabric Expansion Joint - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/fabric-expansion-joint/',
            'og_title' => 'Fabric Expansion Joint - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'metal-expansion-joint',
            'url_path' => '/product/metal-expansion-joint/',
            'name' => 'Metal Expansion Joint',
            'product_group' => 'Flexible Joint',
            'product_subgroup' => null,
            'headline' => 'Metal Expansion Joint',
            'summary' => 'Metal expansion joints for absorbing thermal expansion, mechanical movement and vibration in piping/duct systems.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 2,
            'meta_title' => 'Metal Expansion Joint - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/metal-expansion-joint/',
            'og_title' => 'Metal Expansion Joint - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'rubber-expansion-joint',
            'url_path' => '/product/rubber-expansion-joint/',
            'name' => 'Rubber Expansion Joint',
            'product_group' => 'Flexible Joint',
            'product_subgroup' => null,
            'headline' => 'Rubber Expansion Joint',
            'summary' => 'Rubber expansion joints for absorbing movement, isolating vibration and compensating thermal expansion/misalignment.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 3,
            'meta_title' => 'Rubber Expansion Joint - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/rubber-expansion-joint/',
            'og_title' => 'Rubber Expansion Joint - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'ptfe-expansion-joint',
            'url_path' => '/product/ptfe-expansion-joint/',
            'name' => 'PTFE Expansion Joint',
            'product_group' => 'Flexible Joint',
            'product_subgroup' => null,
            'headline' => 'PTFE Expansion Joint',
            'summary' => 'PTFE expansion joints for chemical resistance, non-stick, clean/corrosive/high-purity environments.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 4,
            'meta_title' => 'PTFE Expansion Joint - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/ptfe-expansion-joint/',
            'og_title' => 'PTFE Expansion Joint - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'ptfe-lined-rubber-metal-expansion-joint',
            'url_path' => '/product/ptfe-lined-rubber-metal-expansion-joint/',
            'name' => 'PTFE Lined Expansion Joint (Rubber and Metal)',
            'product_group' => 'Flexible Joint',
            'product_subgroup' => null,
            'headline' => 'PTFE Lined Expansion Joint (Rubber and Metal)',
            'summary' => 'PTFE-lined rubber/metal expansion joints for flexibility, pressure resistance and chemical protection.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 5,
            'meta_title' => 'PTFE Lined Expansion Joint (Rubber and Metal) - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/ptfe-lined-rubber-metal-expansion-joint/',
            'og_title' => 'PTFE Lined Expansion Joint (Rubber and Metal) - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'rubber-hose',
            'url_path' => '/product/rubber-hose/',
            'name' => 'Rubber Hose',
            'product_group' => 'Flexible Joint',
            'product_subgroup' => null,
            'headline' => 'Rubber Hose',
            'summary' => 'Rubber hose page for industrial fluid/air/chemical/material transfer applications.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 6,
            'meta_title' => 'Rubber Hose - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/rubber-hose/',
            'og_title' => 'Rubber Hose - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'flexible-metal-hose',
            'url_path' => '/product/flexible-metal-hose/',
            'name' => 'Flexible Metal Hose',
            'product_group' => 'Flexible Joint',
            'product_subgroup' => null,
            'headline' => 'Flexible Metal Hose',
            'summary' => 'Flexible metal hose page; includes DN6-DN100, pressure up to 300 bar and temperature range -200°C to +600°C in fetched content.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 7,
            'meta_title' => 'Flexible Metal Hose - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/flexible-metal-hose/',
            'og_title' => 'Flexible Metal Hose - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'ptfe-lining',
            'url_path' => '/product/ptfe-lining/',
            'name' => 'PTFE Lining',
            'product_group' => 'Corrosion Protection',
            'product_subgroup' => 'Lining',
            'headline' => 'PTFE Lining',
            'summary' => 'PTFE lining for corrosion protection; fetched content includes DN15-DN300, -70°C to +260°C, up to 20 bar.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 8,
            'meta_title' => 'PTFE Lining - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/ptfe-lining/',
            'og_title' => 'PTFE Lining - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'rubber-lining',
            'url_path' => '/product/rubber-lining/',
            'name' => 'Rubber Lining',
            'product_group' => 'Corrosion Protection',
            'product_subgroup' => 'Lining',
            'headline' => 'Rubber Lining',
            'summary' => 'Rubber lining applies protective rubber to equipment surfaces to prevent corrosion, abrasion and chemical attack.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 9,
            'meta_title' => 'Rubber Lining - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/rubber-lining/',
            'og_title' => 'Rubber Lining - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'ceramic-lining',
            'url_path' => '/product/ceramic-lining/',
            'name' => 'Ceramic Lining',
            'product_group' => 'Corrosion Protection',
            'product_subgroup' => 'Lining',
            'headline' => 'Ceramic Lining',
            'summary' => 'Ceramic lining page found but search extraction mostly showed duplicated navigation/footer, not detailed body text.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 10,
            'meta_title' => 'Ceramic Lining - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/ceramic-lining/',
            'og_title' => 'Ceramic Lining - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'frp-lining',
            'url_path' => '/product/frp-lining/',
            'name' => 'FRP Lining',
            'product_group' => 'Corrosion Protection',
            'product_subgroup' => 'Lining',
            'headline' => 'FRP Lining',
            'summary' => 'FRP lining page found; search snippet indicates strength/corrosion resistance but fetched text mostly navigation/footer.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 11,
            'meta_title' => 'FRP Lining - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/frp-lining/',
            'og_title' => 'FRP Lining - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'ceramic-coating',
            'url_path' => '/product/ceramic-coating/',
            'name' => 'Ceramic Coating',
            'product_group' => 'Corrosion Protection',
            'product_subgroup' => 'Coating',
            'headline' => 'Ceramic Coating',
            'summary' => 'Ceramic coating page found; content should cover heat/corrosion/wear/chemical protective coating.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 12,
            'meta_title' => 'Ceramic Coating - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/ceramic-coating/',
            'og_title' => 'Ceramic Coating - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'ptfe-coating',
            'url_path' => '/product/ptfe-coating/',
            'name' => 'PTFE Coating',
            'product_group' => 'Corrosion Protection',
            'product_subgroup' => 'Coating',
            'headline' => 'PTFE Coating',
            'summary' => 'PTFE coating page found; content should cover corrosion/non-stick/chemical protection applications.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 13,
            'meta_title' => 'PTFE Coating - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/ptfe-coating/',
            'og_title' => 'PTFE Coating - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'gland-packing',
            'url_path' => '/product/gland-packing/',
            'name' => 'Gland Packing',
            'product_group' => 'Sealing System',
            'product_subgroup' => null,
            'headline' => 'Gland Packing',
            'summary' => 'Gland packing page for leakage prevention along shafts in pumps, valves and rotating/reciprocating equipment.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 14,
            'meta_title' => 'Gland Packing - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/gland-packing/',
            'og_title' => 'Gland Packing - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'oil-seal',
            'url_path' => '/product/oil-seal/',
            'name' => 'Oil Seal',
            'product_group' => 'Sealing System',
            'product_subgroup' => null,
            'headline' => 'Oil Seal',
            'summary' => 'Oil seal page for preventing lubricant leakage and contaminant entry around rotating shafts.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 15,
            'meta_title' => 'Oil Seal - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/oil-seal/',
            'og_title' => 'Oil Seal - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'o-ring',
            'url_path' => '/product/o-ring/',
            'name' => 'O-Ring',
            'product_group' => 'Sealing System',
            'product_subgroup' => null,
            'headline' => 'O-Ring',
            'summary' => 'O-Rings for sealing fluids/gases in static/dynamic applications using NBR, Viton, EPDM, silicone and other elastomers.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 16,
            'meta_title' => 'O-Ring - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/o-ring/',
            'og_title' => 'O-Ring - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'gasket-sheet',
            'url_path' => '/product/gasket-sheet/',
            'name' => 'Gasket Sheet',
            'product_group' => 'Sealing System',
            'product_subgroup' => null,
            'headline' => 'Gasket Sheet',
            'summary' => 'Gasket sheet page for sealing flanges/pipe joints/machinery surfaces.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 17,
            'meta_title' => 'Gasket Sheet - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/gasket-sheet/',
            'og_title' => 'Gasket Sheet - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'mechanical-seal',
            'url_path' => '/product/mechanical-seal/',
            'name' => 'Mechanical Seal',
            'product_group' => 'Sealing System',
            'product_subgroup' => null,
            'headline' => 'Mechanical Seal',
            'summary' => 'Mechanical seal page for preventing leakage in rotating equipment such as pumps, mixers and compressors.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 18,
            'meta_title' => 'Mechanical Seal - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/mechanical-seal/',
            'og_title' => 'Mechanical Seal - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
        [
            'slug' => 'coupling',
            'url_path' => '/product/coupling/',
            'name' => 'Coupling',
            'product_group' => 'Power Transfer',
            'product_subgroup' => null,
            'headline' => 'Coupling',
            'summary' => 'Coupling page for connecting shafts and transmitting power, accommodating misalignment and reducing shock loads.',
            'content_html' => null,
            'key_features' => null,
            'applications' => null,
            'materials' => null,
            'technical_specs' => null,
            'gallery' => null,
            'sort_order' => 19,
            'meta_title' => 'Coupling - PT Misuba Guna Indonesia',
            'meta_description' => null,
            'canonical_url' => 'https://misubaguna.com/product/coupling/',
            'og_title' => 'Coupling - PT Misuba Guna Indonesia',
            'og_description' => null,
            'og_image_path' => null,
            'robots_index' => true,
            'robots_follow' => true,
            'sitemap_include' => true,
            'sitemap_priority' => '0.9',
            'sitemap_changefreq' => 'monthly',
            'schema_json' => null,
            'is_published' => true,
        ],
    ];

        foreach ($products as $product) {
            DB::table('public_products')->updateOrInsert(
                ['url_path' => $product['url_path']],
                array_merge($product, ['created_at' => $now, 'updated_at' => $now])
            );
        }

        $redirects = [
        [
            'source_path' => '/indexpage/',
            'target_url' => '/',
            'status_code' => 301,
            'is_active' => false,
            'note' => 'Legacy duplicate homepage-like page. Enable after checking Google Search Console traffic/backlinks.',
        ],
    ];

        foreach ($redirects as $redirect) {
            DB::table('public_redirects')->updateOrInsert(
                ['source_path' => $redirect['source_path']],
                array_merge($redirect, ['created_at' => $now, 'updated_at' => $now])
            );
        }

        $settings = [
        [
            'key' => 'company_name',
            'value' => 'PT Misuba Guna Indonesia',
            'type' => 'string',
            'description' => 'Public company name for SEO/schema.',
        ],
        [
            'key' => 'company_email',
            'value' => 'marketing@misubaguna.com',
            'type' => 'string',
            'description' => 'Public contact email.',
        ],
        [
            'key' => 'company_phone',
            'value' => '+62 21 55660700',
            'type' => 'string',
            'description' => 'Public telephone.',
        ],
        [
            'key' => 'company_whatsapp',
            'value' => '+62 811-8715-671',
            'type' => 'string',
            'description' => 'Public WhatsApp.',
        ],
        [
            'key' => 'company_website',
            'value' => 'https://misubaguna.com',
            'type' => 'string',
            'description' => 'Public website URL.',
        ],
        [
            'key' => 'operational_address',
            'value' => 'Ruko Mutiara Karawaci Blok C29, Bencongan Indah, Kecamatan Kelapa Dua, Tangerang, Banten 15810',
            'type' => 'string',
            'description' => 'Operational address from current public site.',
        ],
        [
            'key' => 'billing_address',
            'value' => 'NEEDS_CONFIRMATION: public site has conflict between STC Senayan Lantai 4 No 80 and Lantai 2 No 89',
            'type' => 'string',
            'description' => 'Fix before rendering schema or footer.',
        ],
    ];

        foreach ($settings as $setting) {
            DB::table('site_settings')->updateOrInsert(
                ['key' => $setting['key']],
                array_merge($setting, ['created_at' => $now, 'updated_at' => $now])
            );
        }
    }
}
